/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"This version of {0} does not have release notes online",
	"Welcome to {0} v{1}! Would you like to read the Release Notes?",
	"Release Notes",
	"Updates are disabled because you are running the user-scope installation of {0} as Administrator.",
	"Learn More",
	"New {0} update available.",
	"Checking for Updates...",
	"Downloading...",
	"Updating...",
	"Update Service",
	"There are currently no updates available.",
	"There is an available update.",
	"Download Update",
	"Later",
	"Release Notes",
	"There's an update available: {0} {1}",
	"Install Update",
	"Later",
	"Release Notes",
	"Update Now",
	"Later",
	"Release Notes",
	"Restart {0} to apply the latest update.",
	"Check for Updates...",
	"Checking for Updates...",
	"Download Update (1)",
	"Downloading Update...",
	"Install Update... (1)",
	"Installing Update...",
	"Show Update Release Notes",
	"Restart to Update (1)",
	"Switch to Insiders Version...",
	"Switch to Stable Version...",
	"Changing the version requires a reload to take effect",
	"Press the reload button to switch to the Insiders version of VS Code.",
	"Press the reload button to switch to the Stable version of VS Code.",
	"&&Reload",
	"Choose the settings sync service to use after changing the version",
	"The Insiders version of VS Code will synchronize your settings, keybindings, extensions, snippets and UI State using separate insiders settings sync service by default.",
	"&&Insiders",
	"&&Stable (current)"
]);