/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'update.noReleaseNotesOnline',
	'read the release notes',
	'releaseNotes',
	'update service disabled',
	'learn more',
	'updateIsReady',
	'checkingForUpdates',
	'downloading',
	'updating',
	'update service',
	'noUpdatesAvailable',
	'thereIsUpdateAvailable',
	'download update',
	'later',
	'releaseNotes',
	'updateAvailable',
	'installUpdate',
	'later',
	'releaseNotes',
	'updateNow',
	'later',
	'releaseNotes',
	'updateAvailableAfterRestart',
	'checkForUpdates',
	'checkingForUpdates',
	'download update_1',
	'DownloadingUpdate',
	'installUpdate...',
	'installingUpdate',
	'showUpdateReleaseNotes',
	'restartToUpdate',
	'switchToInsiders',
	'switchToStable',
	'relaunchMessage',
	'relaunchDetailInsiders',
	'relaunchDetailStable',
	{ key: 'reload', comment: ['&& denotes a mnemonic'] },
	'selectSyncService.message',
	'selectSyncService.detail',
	{ key: 'use insiders', comment: ['&& denotes a mnemonic'] },
	{ key: 'use stable', comment: ['&& denotes a mnemonic'] }
]);