/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Error while writing to {0}. {1}",
	"Open Tasks Configuration",
	"Open Launch Configuration",
	"Open Settings",
	"Open Tasks Configuration",
	"Open Launch Configuration",
	"Save and Retry",
	"Save and Retry",
	"Open Settings",
	"Unable to write {0} because it is configured in system policy.",
	"Unable to write to {0} because {1} is not a registered configuration.",
	"Unable to write {0} to Workspace Settings. This setting can be written only into User settings.",
	"Unable to write {0} to Workspace Settings. This setting can be written only into User settings.",
	"Unable to write to Folder Settings because {0} does not support the folder resource scope.",
	"Unable to write to User Settings because {0} does not support for global scope.",
	"Unable to write to Workspace Settings because {0} does not support for workspace scope in a multi folder workspace.",
	"Unable to write to Folder Settings because no resource is provided.",
	"Unable to write to Language Settings because {0} is not a resource language setting.",
	"Unable to write to {0} because no workspace is opened. Please open a workspace first and try again.",
	"Unable to write into the tasks configuration file. Please open it to correct errors/warnings in it and try again.",
	"Unable to write into the launch configuration file. Please open it to correct errors/warnings in it and try again.",
	"Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.",
	"Unable to write into remote user settings. Please open the remote user settings to correct errors/warnings in it and try again.",
	"Unable to write into workspace settings. Please open the workspace settings to correct errors/warnings in the file and try again.",
	"Unable to write into folder settings. Please open the '{0}' folder settings to correct errors/warnings in it and try again.",
	"Unable to write into tasks configuration file because the file has unsaved changes. Please save it first and then try again.",
	"Unable to write into launch configuration file because the file has unsaved changes. Please save it first and then try again.",
	"Unable to write into user settings because the file has unsaved changes. Please save the user settings file first and then try again.",
	"Unable to write into remote user settings because the file has unsaved changes. Please save the remote user settings file first and then try again.",
	"Unable to write into workspace settings because the file has unsaved changes. Please save the workspace settings file first and then try again.",
	"Unable to write into folder settings because the file has unsaved changes. Please save the '{0}' folder settings file first and then try again.",
	"Unable to write into tasks configuration file because the content of the file is newer.",
	"Unable to write into launch configuration file because the content of the file is newer.",
	"Unable to write into user settings because the content of the file is newer.",
	"Unable to write into remote user settings because the content of the file is newer.",
	"Unable to write into workspace settings because the content of the file is newer.",
	"Unable to write into folder settings because the content of the file is newer.",
	"Unable to write to {0} because of an internal error.",
	"User Settings",
	"Remote User Settings",
	"Workspace Settings",
	"Folder Settings"
]);