/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'in {0}',
	'now',
	'{0} second ago',
	'{0} sec ago',
	'{0} seconds ago',
	'{0} secs ago',
	'{0} second',
	'{0} sec',
	'{0} seconds',
	'{0} secs',
	'{0} minute ago',
	'{0} min ago',
	'{0} minutes ago',
	'{0} mins ago',
	'{0} minute',
	'{0} min',
	'{0} minutes',
	'{0} mins',
	'{0} hour ago',
	'{0} hr ago',
	'{0} hours ago',
	'{0} hrs ago',
	'{0} hour',
	'{0} hr',
	'{0} hours',
	'{0} hrs',
	'{0} day ago',
	'{0} days ago',
	'{0} day',
	'{0} days',
	'{0} week ago',
	'{0} wk ago',
	'{0} weeks ago',
	'{0} wks ago',
	'{0} week',
	'{0} wk',
	'{0} weeks',
	'{0} wks',
	'{0} month ago',
	'{0} mo ago',
	'{0} months ago',
	'{0} mos ago',
	'{0} month',
	'{0} mo',
	'{0} months',
	'{0} mos',
	'{0} year ago',
	'{0} yr ago',
	'{0} years ago',
	'{0} yrs ago',
	'{0} year',
	'{0} yr',
	'{0} years',
	'{0} yrs'
]);