/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	{ key: 'miNewTerminal', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSplitTerminal', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRunActiveFile', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRunSelectedText', comment: ['&& denotes a mnemonic'] },
	'workbench.action.terminal.copySelection.short',
	'workbench.action.terminal.copySelectionAsHtml',
	'workbench.action.terminal.paste.short',
	'workbench.action.terminal.clear',
	'workbench.action.terminal.selectAll',
	'workbench.action.terminal.copySelection.short',
	'workbench.action.terminal.copySelectionAsHtml',
	'workbench.action.terminal.paste.short',
	'workbench.action.terminal.clear',
	'workbench.action.terminal.selectAll',
	'workbench.action.terminal.newWithProfile.short',
	'workbench.action.terminal.selectDefaultProfile',
	'workbench.action.terminal.openSettings',
	'workbench.action.tasks.runTask',
	'workbench.action.tasks.configureTaskRunner',
	'workbench.action.terminal.switchTerminal',
	'workbench.action.terminal.clearLong',
	'workbench.action.terminal.runActiveFile',
	'workbench.action.terminal.runSelectedText',
	'workbench.action.terminal.renameInstance',
	'workbench.action.terminal.changeIcon',
	'workbench.action.terminal.changeColor',
	'workbench.action.terminal.sizeToContentWidthInstance',
	'workbench.action.terminal.joinInstance',
	'defaultTerminalProfile',
	'defaultTerminalProfile',
	'defaultTerminalProfile',
	'splitTerminal'
]);