/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Task",
	"Local",
	'Terminal input',
	'Use the accessible buffer {0} to manually review output',
	'Use the Terminal: Focus Accessible Buffer command to manually review output',
	"Bell",
	"Some keybindings don't go to the terminal by default and are handled by {0} instead.",
	"Configure Terminal Settings",
	"Preview:",
	"Are you sure you want to paste {0} lines of text into the terminal?",
	"&&Paste",
	"Do not ask me again",
	"Lost connection to process",
	"Cannot launch a terminal process in an untrusted workspace",
	"Cannot launch a terminal process in an untrusted workspace with cwd {0} and userHome {1}",
	'Disabling shell integration in user settings might help.',
	"Learn more about shell integration",
	"Open user settings",
	"Creating a terminal process requires executing code",
	"Terminal {0}, {1}",
	"Terminal {0}",
	"Run the command: Toggle Screen Reader Accessibility Mode for an optimized screen reader experience",
	"Use {0} for terminal accessibility help",
	"Set Fixed Dimensions: Column",
	"Set Fixed Dimensions: Row",
	"Terminal {0} environment is stale, run the 'Show Environment Information' command for more information",
	'Select an icon for the terminal',
	'Select a color for the terminal',
	"The terminal process \"{0}\" failed to launch (exit code: {1}).",
	"The terminal process failed to launch (exit code: {0}).",
	"The terminal process \"{0}\" terminated with exit code: {1}.",
	"The terminal process terminated with exit code: {0}.",
	"The terminal process failed to launch: {0}."
]);