/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Show Tabs",
	"Select current working directory for new terminal",
	"Open Help",
	"Create New Terminal (In Active Workspace)",
	"Create New Terminal in Editor Area",
	"Create New Terminal in Editor Area",
	"Create New Terminal in Editor Area to the Side",
	"Focus Previous Terminal in Terminal Group",
	"Focus Next Terminal in Terminal Group",
	"Run Recent Command...",
	'Copy Last Command Output',
	"Go to Recent Directory...",
	"Resize Terminal Left",
	"Resize Terminal Right",
	"Resize Terminal Up",
	"Resize Terminal Down",
	"Focus Terminal Tabs View",
	"Focus Next Terminal Group",
	"Focus Previous Terminal Group",
	"Run Selected Text In Active Terminal",
	"Run Active File In Active Terminal",
	'Only files on disk can be run in the terminal',
	"Scroll Down (Line)",
	"Scroll Down (Page)",
	"Scroll to Bottom",
	"Scroll Up (Line)",
	"Scroll Up (Page)",
	"Scroll to Top",
	"Clear Selection",
	"Detach Session",
	"Attach to Session",
	'There are no unattached terminals to attach to',
	"Switch Active Terminal",
	"Scroll To Previous Command",
	"Scroll To Next Command",
	"Select To Previous Command",
	"Select To Next Command",
	"Select To Previous Line",
	"Select To Next Line",
	"The sequence of text to send to the terminal",
	"The directory to start the terminal at",
	"The new name for the terminal",
	"No name argument provided",
	"Relaunch Active Terminal",
	"Join Terminals",
	"Join Terminals",
	'Insufficient terminals for the join action',
	'All terminals are joined already',
	"Split Terminal (In Active Workspace)",
	"Select All",
	"Create New Terminal",
	"Kill the Active Terminal Instance",
	"Kill All Terminals",
	"Kill the Active Terminal in Editor Area",
	"Clear",
	"Select Default Profile",
	"Configure Terminal Settings",
	"Set Fixed Dimensions",
	"Toggle Size to Content Width",
	"Clear Previous Session History",
	"Select the Previous Suggestion",
	"Select the Previous Page Suggestion",
	"Select the Next Suggestion",
	"Select the Next Page Suggestion",
	"Accept Selected Suggestion",
	"Hide Suggest Widget",
	"Copy Selection",
	"Copy and Clear Selection",
	"Copy Selection as HTML",
	"Paste into Active Terminal",
	"Paste Selection into Active Terminal",
	"Switch Terminal",
	"Providing no name will reset it to the default value",
	"Create New Terminal (With Profile)",
	"The name of the profile to create",
	"Select current working directory for new terminal",
	"(Overriden) {0}",
	"Select current working directory for new terminal",
	"Enter terminal name"
]);