/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"The Command Palette",
	"The touch bar (macOS only)",
	"The editor title menu",
	"Run submenu inside the editor title menu",
	"The editor context menu",
	"'Copy as' submenu in the editor context menu",
	"'Share' submenu in the editor context menu",
	"The file explorer context menu",
	"'Share' submenu in the file explorer context menu",
	"The editor tabs context menu",
	"'Share' submenu inside the editor title context menu",
	"The debug callstack view context menu",
	"The debug variables view context menu",
	"The debug toolbar menu",
	"The home indicator context menu (web only)",
	"'Copy as' submenu in the top level Edit menu",
	"The Source Control title menu",
	"The Source Control menu",
	"The Source Control resource state context menu",
	"The Source Control resource folder context menu",
	"The Source Control resource group context menu",
	"The Source Control inline change menu",
	"The remote indicator menu in the status bar",
	"The terminal context menu",
	"The terminal tabs context menu",
	"The contributed view title menu",
	"The contributed view item context menu",
	"The contributed comment editor actions",
	"The contributed comment thread title menu",
	"The contributed comment thread context menu, rendered as buttons below the comment editor",
	"The contributed comment thread context menu, rendered as buttons below the comment editor",
	"The contributed comment thread title's peek context menu, rendered as a right click menu on the comment thread's peek title.",
	"The contributed comment title menu",
	"The contributed comment context menu, rendered as buttons below the comment editor",
	"The contributed comment context menu, rendered as a right click menu on the an individual comment in the comment thread's peek view.",
	"The contributed notebook toolbar menu",
	"The contributed notebook kernel sources menu",
	"The contributed notebook cell title menu",
	"The contributed notebook cell execution menu",
	"The contributed interactive toolbar menu",
	"The contributed interactive cell title menu",
	"The contributed test item menu",
	"The menu for a gutter decoration for a test item",
	"A prominent button overlaying editor content where the message is displayed",
	"Context menu for the message in the results tree",
	"The extension context menu",
	"The Timeline view title menu",
	"The Timeline view item context menu",
	"The Ports view item context menu",
	"The Ports view item origin inline menu",
	"The Ports view item port inline menu",
	"The 'New File...' quick pick, shown on welcome page and File menu.",
	"The webview context menu",
	"Share submenu shown in the top level File menu.",
	"The actions shown when hovering on an inline completion",
	"The prominent button in an editor, overlays its content",
	"The contributed editor line number context menu",
	"The result toolbar of the merge editor",
	"property `{0}` is mandatory and must be of type `string`",
	"property `{0}` can be omitted or must be of type `string`",
	"property `{0}` can be omitted or must be of type `string`",
	"property `{0}` can be omitted or must be of type `string`",
	"property `{0}` is mandatory and must be of type `string`",
	"property `{0}` can be omitted or must be of type `string`",
	"property `{0}` can be omitted or must be of type `string`",
	"submenu items must be an array",
	"submenu items must be an object",
	"property `{0}` is mandatory and must be of type `string`",
	"property `{0}` is mandatory and must be of type `string`",
	'Identifier of the command to execute. The command must be declared in the \'commands\'-section',
	'Identifier of an alternative command to execute. The command must be declared in the \'commands\'-section',
	'Condition which must be true to show this item',
	'Group into which this item belongs',
	'Identifier of the submenu to display in this item.',
	'Condition which must be true to show this item',
	'Group into which this item belongs',
	'Identifier of the menu to display as a submenu.',
	'The label of the menu item which leads to this submenu.',
	'(Optional) Icon which is used to represent the submenu in the UI. Either a file path, an object with file paths for dark and light themes, or a theme icon references, like `\\$(zap)`',
	'Icon path when a light theme is used',
	'Icon path when a dark theme is used',
	"Contributes menu items to the editor",
	"Proposed API, requires `enabledApiProposal: [\"{0}\"]` - {1}",
	"Contributes submenu items to the editor",
	"expected non-empty value.",
	"property `{0}` is mandatory and must be of type `string`",
	"property `{0}` can be omitted or must be of type `string`",
	"property `icon` can be omitted or must be either a string or a literal like `{dark, light}`",
	"property `{0}` is mandatory and must be of type `string` or `object`",
	"property `{0}` is mandatory and must be of type `string`",
	"properties `{0}` and `{1}` are mandatory and must be of type `string`",
	'Identifier of the command to execute',
	'Title by which the command is represented in the UI',
	'(Optional) Short title by which the command is represented in the UI. Menus pick either `title` or `shortTitle` depending on the context in which they show commands.',
	'(Optional) Category string by which the command is grouped in the UI',
	'(Optional) Condition which must be true to enable the command in the UI (menu and keybindings). Does not prevent executing the command by other means, like the `executeCommand`-api.',
	'(Optional) Icon which is used to represent the command in the UI. Either a file path, an object with file paths for dark and light themes, or a theme icon references, like `\\$(zap)`',
	'Icon path when a light theme is used',
	'Icon path when a dark theme is used',
	"Contributes commands to the command palette.",
	"Command `{0}` already registered by {1} ({2})",
	"Command `{0}` already registered",
	"`{0}` is not a valid submenu identifier",
	"The `{0}` submenu was already previously registered.",
	"`{0}` is not a valid submenu label",
	"{0} is a proposed menu identifier. It requires 'package.json#enabledApiProposals: [\"{1}\"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api {2}",
	"Menu item references a command `{0}` which is not defined in the 'commands' section.",
	"Menu item references an alt-command `{0}` which is not defined in the 'commands' section.",
	"Menu item references the same command as default and alt-command",
	"Menu item references a submenu for a menu which doesn't have submenu support.",
	"Menu item references a submenu `{0}` which is not defined in the 'submenus' section.",
	"The `{0}` submenu was already contributed to the `{1}` menu."
]);