/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Continue Working On...",
	"Open In Local Folder",
	'Show Log',
	'Install additional development environment options',
	'Resuming working changes...',
	'Storing current working changes...',
	'Check for pending cloud changes',
	'Storing working changes...',
	"Show Cloud Changes",
	'Storing your working changes...',
	"Resume Latest Changes from Cloud",
	"Resume Changes from Serialized Data",
	"Store Working Changes in Cloud",
	'Storing working changes...',
	'Checking for pending cloud changes...',
	'There are no changes to resume from the cloud.',
	'Could not resume changes from the cloud for ID {0}.',
	"Please upgrade to a newer version of {0} to resume your working changes from the cloud.",
	'Resuming your working changes from the cloud will overwrite the following {0} files. Do you want to proceed?',
	'Resuming your working changes from the cloud will overwrite {0}. Do you want to proceed?',
	"Failed to resume your working changes from the cloud.",
	'You have pending working changes in the cloud for this workspace. Would you like to resume them?',
	'Resume',
	'Your working changes exceed the size limit and cannot be stored.',
	'Skipped storing working changes in the cloud as there are no edits to store.',
	'Your working changes exceed the size limit and cannot be stored.',
	'Your working changes cannot be stored.',
	"Select whether to bring your working changes with you",
	"Yes, continue with my working changes",
	"No, continue without my working changes",
	'Select a local folder to continue working in',
	'Continue Working in Existing Local Folder',
	"Select a development environment to continue working on {0} in",
	'Open in Local Folder',
	'Built-in',
	'Learn More',
	'Contributes options for continuing the current edit session in a different environment',
	'Identifier of the command to execute. The command must be declared in the \'commands\'-section and return a URI representing a different environment where the current edit session can be continued.',
	'Group into which this item belongs.',
	'A fully qualified name for this item which is used for display in menus.',
	"The url, or a command that returns the url, to the option's documentation page.",
	'Group into which this item belongs in the remote indicator.',
	'Condition which must be true to show this item.',
	"Automatically store current working changes in the cloud on window close.",
	"Never attempt to automatically store working changes in the cloud.",
	"Controls whether to automatically store available working changes in the cloud for the current workspace. This setting has no effect in the web.",
	"Automatically resume available working changes from the cloud on window reload.",
	"Never attempt to resume working changes from the cloud.",
	"Controls whether to automatically resume available working changes stored in the cloud for the current workspace.",
	'Prompt the user to sign in to store working changes in the cloud with Continue Working On.',
	'Do not store working changes in the cloud with Continue Working On unless the user has already turned on Cloud Changes.',
	'Controls whether to prompt the user to store working changes in the cloud when using Continue Working On.',
	"Controls whether to surface cloud changes which partially match the current session."
]);