/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'continue working on',
	'continue edit session in local folder',
	'show log',
	'continueOn.installAdditional',
	'resuming working changes window',
	'autoStoreWorkingChanges',
	'check for pending cloud changes',
	'store working changes',
	'show cloud changes',
	'store your working changes',
	'resume latest cloud changes',
	'resume cloud changes',
	'store working changes in cloud',
	'storing working changes',
	'checkingForWorkingChanges',
	'no cloud changes',
	'no cloud changes for ref',
	'client too old',
	'resume edit session warning many',
	'resume edit session warning 1',
	'resume failed',
	'editSessionPartialMatch',
	'resume',
	'payload too large',
	'no working changes to store',
	'payload too large',
	'payload failed',
	'continue with cloud changes',
	'with cloud changes',
	'without cloud changes',
	'continueEditSession.openLocalFolder.title.v2',
	'continueWorkingOn.existingLocalFolder',
	'continueEditSessionPick.title.v2',
	'continueEditSessionItem.openInLocalFolder.v2',
	'continueEditSessionItem.builtin',
	'learnMoreTooltip',
	'continueEditSessionExtPoint',
	'continueEditSessionExtPoint.command',
	'continueEditSessionExtPoint.group',
	'continueEditSessionExtPoint.qualifiedName',
	'continueEditSessionExtPoint.description',
	'continueEditSessionExtPoint.remoteGroup',
	'continueEditSessionExtPoint.when',
	'autoStoreWorkingChanges.onShutdown',
	'autoStoreWorkingChanges.off',
	'autoStoreWorkingChangesDescription',
	'autoResumeWorkingChanges.onReload',
	'autoResumeWorkingChanges.off',
	'autoResumeWorkingChanges',
	'continueOnCloudChanges.promptForAuth',
	'continueOnCloudChanges.off',
	'continueOnCloudChanges',
	'cloudChangesPartialMatchesEnabled'
]);