/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Editor",
	"The number of spaces a tab is equal to. This setting is overridden based on the file contents when {0} is on.",
	"The number of spaces used for indentation or `\"tabSize\"` to use the value from `#editor.tabSize#`. This setting is overridden based on the file contents when `#editor.detectIndentation#` is on.",
	"Insert spaces when pressing `Tab`. This setting is overridden based on the file contents when {0} is on.",
	"Controls whether {0} and {1} will be automatically detected when a file is opened based on the file contents.",
	"Remove trailing auto inserted whitespace.",
	"Special handling for large files to disable certain memory intensive features.",
	"Controls whether completions should be computed based on words in the document.",
	'Only suggest words from the active document.',
	'Suggest words from all open documents of the same language.',
	'Suggest words from all open documents.',
	"Controls from which documents word based completions are computed.",
	'Semantic highlighting enabled for all color themes.',
	'Semantic highlighting disabled for all color themes.',
	'Semantic highlighting is configured by the current color theme\'s `semanticHighlighting` setting.',
	"Controls whether the semanticHighlighting is shown for the languages that support it.",
	"Keep peek editors open even when double-clicking their content or when hitting `Escape`.",
	"Lines above this length will not be tokenized for performance reasons",
	"Controls whether the tokenization should happen asynchronously on a web worker.",
	"Controls whether async tokenization should be logged. For debugging only.",
	"Controls whether async tokenization should be verified against legacy background tokenization. Might slow down tokenization. For debugging only.",
	'Defines the bracket symbols that increase or decrease the indentation.',
	'The opening bracket character or string sequence.',
	'The closing bracket character or string sequence.',
	'Defines the bracket pairs that are colorized by their nesting level if bracket pair colorization is enabled.',
	'The opening bracket character or string sequence.',
	'The closing bracket character or string sequence.',
	"Timeout in milliseconds after which diff computation is cancelled. Use 0 for no timeout.",
	"Maximum file size in MB for which to compute diffs. Use 0 for no limit.",
	"Controls whether the diff editor shows the diff side by side or inline.",
	"If the diff editor width is smaller than this value, the inline view is used.",
	"If enabled and the editor width is too small, the inline view is used.",
	"When enabled, the diff editor shows arrows in its glyph margin to revert changes.",
	"When enabled, the diff editor ignores changes in leading or trailing whitespace.",
	"Controls whether the diff editor shows +/- indicators for added/removed changes.",
	"Controls whether the editor shows CodeLens.",
	"Lines will never wrap.",
	"Lines will wrap at the viewport width.",
	"Lines will wrap according to the {0} setting.",
	"Uses the legacy diffing algorithm.",
	"Uses the advanced diffing algorithm.",
	"Controls whether the diff editor shows unchanged regions.",
	"Controls how many lines are used for unchanged regions.",
	"Controls how many lines are used as a minimum for unchanged regions.",
	"Controls how many lines are used as context when comparing unchanged regions.",
	"Controls whether the diff editor should show detected code moves.",
	"Controls whether the diff editor shows empty decorations to see where characters got inserted or deleted."
]);