/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Use platform APIs to detect when a Screen Reader is attached",
	"Optimize for usage with a Screen Reader",
	"Assume a screen reader is not attached",
	"Controls if the UI should run in a mode where it is optimized for screen readers.",
	"Controls whether a space character is inserted when commenting.",
	'Controls if empty lines should be ignored with toggle, add or remove actions for line comments.',
	"Controls whether copying without a selection copies the current line.",
	"Controls whether the cursor should jump to find matches while typing.",
	'Never seed search string from the editor selection.',
	'Always seed search string from the editor selection, including word at cursor position.',
	'Only seed search string from the editor selection.',
	"Controls whether the search string in the Find Widget is seeded from the editor selection.",
	'Never turn on Find in Selection automatically (default).',
	'Always turn on Find in Selection automatically.',
	'Turn on Find in Selection automatically when multiple lines of content are selected.',
	"Controls the condition for turning on Find in Selection automatically.",
	"Controls whether the Find Widget should read or modify the shared find clipboard on macOS.",
	"Controls whether the Find Widget should add extra lines on top of the editor. When true, you can scroll beyond the first line when the Find Widget is visible.",
	"Controls whether the search automatically restarts from the beginning (or the end) when no further matches can be found.",
	"Enables/Disables font ligatures ('calt' and 'liga' font features). Change this to a string for fine-grained control of the 'font-feature-settings' CSS property.",
	"Explicit 'font-feature-settings' CSS property. A boolean can be passed instead if one only needs to turn on/off ligatures.",
	"Configures font ligatures or font features. Can be either a boolean to enable/disable ligatures or a string for the value of the CSS 'font-feature-settings' property.",
	"Enables/Disables the translation from font-weight to font-variation-settings. Change this to a string for fine-grained control of the 'font-variation-settings' CSS property.",
	"Explicit 'font-variation-settings' CSS property. A boolean can be passed instead if one only needs to translate font-weight to font-variation-settings.",
	"Configures font variations. Can be either a boolean to enable/disable the translation from font-weight to font-variation-settings or a string for the value of the CSS 'font-variation-settings' property.",
	"Controls the font size in pixels.",
	"Only \"normal\" and \"bold\" keywords or numbers between 1 and 1000 are allowed.",
	"Controls the font weight. Accepts \"normal\" and \"bold\" keywords or numbers between 1 and 1000.",
	'Show Peek view of the results (default)',
	'Go to the primary result and show a Peek view',
	'Go to the primary result and enable Peek-less navigation to others',
	"This setting is deprecated, please use separate settings like 'editor.editor.gotoLocation.multipleDefinitions' or 'editor.editor.gotoLocation.multipleImplementations' instead.",
	"Controls the behavior the 'Go to Definition'-command when multiple target locations exist.",
	"Controls the behavior the 'Go to Type Definition'-command when multiple target locations exist.",
	"Controls the behavior the 'Go to Declaration'-command when multiple target locations exist.",
	"Controls the behavior the 'Go to Implementations'-command when multiple target locations exist.",
	"Controls the behavior the 'Go to References'-command when multiple target locations exist.",
	"Alternative command id that is being executed when the result of 'Go to Definition' is the current location.",
	"Alternative command id that is being executed when the result of 'Go to Type Definition' is the current location.",
	"Alternative command id that is being executed when the result of 'Go to Declaration' is the current location.",
	"Alternative command id that is being executed when the result of 'Go to Implementation' is the current location.",
	"Alternative command id that is being executed when the result of 'Go to Reference' is the current location.",
	"Controls whether the hover is shown.",
	"Controls the delay in milliseconds after which the hover is shown.",
	"Controls whether the hover should remain visible when mouse is moved over it.",
	"Controls the delay in milliseconds after thich the hover is hidden. Requires `editor.hover.sticky` to be enabled.",
	"Prefer showing hovers above the line, if there's space.",
	"Assumes that all characters are of the same width. This is a fast algorithm that works correctly for monospace fonts and certain scripts (like Latin characters) where glyphs are of equal width.",
	"Delegates wrapping points computation to the browser. This is a slow algorithm, that might cause freezes for large files, but it works correctly in all cases.",
	"Controls the algorithm that computes wrapping points. Note that when in accessibility mode, advanced will be used for the best experience.",
	"Enables the Code Action lightbulb in the editor.",
	"Shows the nested current scopes during the scroll at the top of the editor.",
	"Defines the maximum number of sticky lines to show.",
	"Defines the model to use for determining which lines to stick. If the outline model does not exist, it will fall back on the folding provider model which falls back on the indentation model. This order is respected in all three cases.",
	"Enable scrolling of the sticky scroll widget with the editor's horizontal scrollbar.",
	"Enables the inlay hints in the editor.",
	"Inlay hints are enabled",
	"Inlay hints are showing by default and hide when holding {0}",
	"Inlay hints are hidden by default and show when holding {0}",
	"Inlay hints are disabled",
	"Controls font size of inlay hints in the editor. As default the {0} is used when the configured value is less than {1} or greater than the editor font size.",
	"Controls font family of inlay hints in the editor. When set to empty, the {0} is used.",
	"Enables the padding around the inlay hints in the editor.",
	"Controls the line height. \n - Use 0 to automatically compute the line height from the font size.\n - Values between 0 and 8 will be used as a multiplier with the font size.\n - Values greater than or equal to 8 will be used as effective values.",
	"Controls whether the minimap is shown.",
	"Controls whether the minimap is hidden automatically.",
	"The minimap has the same size as the editor contents (and might scroll).",
	"The minimap will stretch or shrink as necessary to fill the height of the editor (no scrolling).",
	"The minimap will shrink as necessary to never be larger than the editor (no scrolling).",
	"Controls the size of the minimap.",
	"Controls the side where to render the minimap.",
	"Controls when the minimap slider is shown.",
	"Scale of content drawn in the minimap: 1, 2 or 3.",
	"Render the actual characters on a line as opposed to color blocks.",
	"Limit the width of the minimap to render at most a certain number of columns.",
	"Controls the amount of space between the top edge of the editor and the first line.",
	"Controls the amount of space between the bottom edge of the editor and the last line.",
	"Enables a pop-up that shows parameter documentation and type information as you type.",
	"Controls whether the parameter hints menu cycles or closes when reaching the end of the list.",
	"Quick suggestions show inside the suggest widget",
	"Quick suggestions show as ghost text",
	"Quick suggestions are disabled",
	"Enable quick suggestions inside strings.",
	"Enable quick suggestions inside comments.",
	"Enable quick suggestions outside of strings and comments.",
	"Controls whether suggestions should automatically show up while typing. This can be controlled for typing in comments, strings, and other code. Quick suggestion can be configured to show as ghost text or with the suggest widget. Also be aware of the '{0}'-setting which controls if suggestions are triggered by special characters.",
	"Line numbers are not rendered.",
	"Line numbers are rendered as absolute number.",
	"Line numbers are rendered as distance in lines to cursor position.",
	"Line numbers are rendered every 10 lines.",
	"Controls the display of line numbers.",
	"Number of monospace characters at which this editor ruler will render.",
	"Color of this editor ruler.",
	"Render vertical rulers after a certain number of monospace characters. Use multiple values for multiple rulers. No rulers are drawn if array is empty.",
	"The vertical scrollbar will be visible only when necessary.",
	"The vertical scrollbar will always be visible.",
	"The vertical scrollbar will always be hidden.",
	"Controls the visibility of the vertical scrollbar.",
	"The horizontal scrollbar will be visible only when necessary.",
	"The horizontal scrollbar will always be visible.",
	"The horizontal scrollbar will always be hidden.",
	"Controls the visibility of the horizontal scrollbar.",
	"The width of the vertical scrollbar.",
	"The height of the horizontal scrollbar.",
	"Controls whether clicks scroll by page or jump to click position.",
	"Controls whether all non-basic ASCII characters are highlighted. Only characters between U+0020 and U+007E, tab, line-feed and carriage-return are considered basic ASCII.",
	"Controls whether characters that just reserve space or have no width at all are highlighted.",
	"Controls whether characters are highlighted that can be confused with basic ASCII characters, except those that are common in the current user locale.",
	"Controls whether characters in comments should also be subject to Unicode highlighting.",
	"Controls whether characters in strings should also be subject to Unicode highlighting.",
	"Defines allowed characters that are not being highlighted.",
	"Unicode characters that are common in allowed locales are not being highlighted.",
	"Controls whether to automatically show inline suggestions in the editor.",
	"Show the inline suggestion toolbar whenever an inline suggestion is shown.",
	"Show the inline suggestion toolbar when hovering over an inline suggestion.",
	"Controls when to show the inline suggestion toolbar.",
	"Controls how inline suggestions interact with the suggest widget. If enabled, the suggest widget is not shown automatically when inline suggestions are available.",
	"Controls whether bracket pair colorization is enabled or not. Use {0} to override the bracket highlight colors.",
	"Controls whether each bracket type has its own independent color pool.",
	"Enables bracket pair guides.",
	"Enables bracket pair guides only for the active bracket pair.",
	"Disables bracket pair guides.",
	"Controls whether bracket pair guides are enabled or not.",
	"Enables horizontal guides as addition to vertical bracket pair guides.",
	"Enables horizontal guides only for the active bracket pair.",
	"Disables horizontal bracket pair guides.",
	"Controls whether horizontal bracket pair guides are enabled or not.",
	"Controls whether the editor should highlight the active bracket pair.",
	"Controls whether the editor should render indent guides.",
	"Highlights the active indent guide.",
	"Highlights the active indent guide even if bracket guides are highlighted.",
	"Do not highlight the active indent guide.",
	"Controls whether the editor should highlight the active indent guide.",
	"Insert suggestion without overwriting text right of the cursor.",
	"Insert suggestion and overwrite text right of the cursor.",
	"Controls whether words are overwritten when accepting completions. Note that this depends on extensions opting into this feature.",
	"Controls whether filtering and sorting suggestions accounts for small typos.",
	"Controls whether sorting favors words that appear close to the cursor.",
	"Controls whether remembered suggestion selections are shared between multiple workspaces and windows (needs `#editor.suggestSelection#`).",
	"Always select a suggestion when automatically triggering IntelliSense.",
	"Never select a suggestion when automatically triggering IntelliSense.",
	"Select a suggestion only when triggering IntelliSense from a trigger character.",
	"Select a suggestion only when triggering IntelliSense as you type.",
	"Controls whether a suggestion is selected when the widget shows. Note that this only applies to automatically triggered suggestions (`#editor.quickSuggestions#` and `#editor.suggestOnTriggerCharacters#`) and that a suggestion is always selected when explicitly invoked, e.g via `Ctrl+Space`.",
	"Controls whether an active snippet prevents quick suggestions.",
	"Controls whether to show or hide icons in suggestions.",
	"Controls the visibility of the status bar at the bottom of the suggest widget.",
	"Controls whether to preview the suggestion outcome in the editor.",
	"Controls whether suggest details show inline with the label or only in the details widget.",
	"This setting is deprecated. The suggest widget can now be resized.",
	"This setting is deprecated, please use separate settings like 'editor.suggest.showKeywords' or 'editor.suggest.showSnippets' instead.",
	"When enabled IntelliSense shows `method`-suggestions.",
	"When enabled IntelliSense shows `function`-suggestions.",
	"When enabled IntelliSense shows `constructor`-suggestions.",
	"When enabled IntelliSense shows `deprecated`-suggestions.",
	"When enabled IntelliSense filtering requires that the first character matches on a word start. For example, `c` on `Console` or `WebContext` but _not_ on `description`. When disabled IntelliSense will show more results but still sorts them by match quality.",
	"When enabled IntelliSense shows `field`-suggestions.",
	"When enabled IntelliSense shows `variable`-suggestions.",
	"When enabled IntelliSense shows `class`-suggestions.",
	"When enabled IntelliSense shows `struct`-suggestions.",
	"When enabled IntelliSense shows `interface`-suggestions.",
	"When enabled IntelliSense shows `module`-suggestions.",
	"When enabled IntelliSense shows `property`-suggestions.",
	"When enabled IntelliSense shows `event`-suggestions.",
	"When enabled IntelliSense shows `operator`-suggestions.",
	"When enabled IntelliSense shows `unit`-suggestions.",
	"When enabled IntelliSense shows `value`-suggestions.",
	"When enabled IntelliSense shows `constant`-suggestions.",
	"When enabled IntelliSense shows `enum`-suggestions.",
	"When enabled IntelliSense shows `enumMember`-suggestions.",
	"When enabled IntelliSense shows `keyword`-suggestions.",
	"When enabled IntelliSense shows `text`-suggestions.",
	"When enabled IntelliSense shows `color`-suggestions.",
	"When enabled IntelliSense shows `file`-suggestions.",
	"When enabled IntelliSense shows `reference`-suggestions.",
	"When enabled IntelliSense shows `customcolor`-suggestions.",
	"When enabled IntelliSense shows `folder`-suggestions.",
	"When enabled IntelliSense shows `typeParameter`-suggestions.",
	"When enabled IntelliSense shows `snippet`-suggestions.",
	"When enabled IntelliSense shows `user`-suggestions.",
	"When enabled IntelliSense shows `issues`-suggestions.",
	"Whether leading and trailing whitespace should always be selected.",
	"Whether subwords (like 'foo' in 'fooBar' or 'foo_bar') should be selected.",
	"No indentation. Wrapped lines begin at column 1.",
	"Wrapped lines get the same indentation as the parent.",
	"Wrapped lines get +1 indentation toward the parent.",
	"Wrapped lines get +2 indentation toward the parent.",
	"Controls the indentation of wrapped lines.",
	"Controls whether you can drag and drop a file into a text editor by holding down `shift` (instead of opening the file in an editor).",
	"Controls if a widget is shown when dropping files into the editor. This widget lets you control how the file is dropped.",
	"Show the drop selector widget after a file is dropped into the editor.",
	"Never show the drop selector widget. Instead the default drop provider is always used.",
	"Controls whether you can paste content in different ways.",
	"Controls if a widget is shown when pasting content in to the editor. This widget lets you control how the file is pasted.",
	"Show the paste selector widget after content is pasted into the editor.",
	"Never show the paste selector widget. Instead the default pasting behavior is always used.",
	"Controls whether suggestions should be accepted on commit characters. For example, in JavaScript, the semi-colon (`;`) can be a commit character that accepts a suggestion and types that character.",
	"Only accept a suggestion with `Enter` when it makes a textual change.",
	"Controls whether suggestions should be accepted on `Enter`, in addition to `Tab`. Helps to avoid ambiguity between inserting new lines or accepting suggestions.",
	"Controls the number of lines in the editor that can be read out by a screen reader at once. When we detect a screen reader we automatically set the default to be 500. Warning: this has a performance implication for numbers larger than the default.",
	"Editor content",
	"Control whether inline suggestions are announced by a screen reader.",
	"Use language configurations to determine when to autoclose brackets.",
	"Autoclose brackets only when the cursor is to the left of whitespace.",
	"Controls whether the editor should automatically close brackets after the user adds an opening bracket.",
	"Use language configurations to determine when to autoclose comments.",
	"Autoclose comments only when the cursor is to the left of whitespace.",
	"Controls whether the editor should automatically close comments after the user adds an opening comment.",
	"Remove adjacent closing quotes or brackets only if they were automatically inserted.",
	"Controls whether the editor should remove adjacent closing quotes or brackets when deleting.",
	"Type over closing quotes or brackets only if they were automatically inserted.",
	"Controls whether the editor should type over closing quotes or brackets.",
	"Use language configurations to determine when to autoclose quotes.",
	"Autoclose quotes only when the cursor is to the left of whitespace.",
	"Controls whether the editor should automatically close quotes after the user adds an opening quote.",
	"The editor will not insert indentation automatically.",
	"The editor will keep the current line's indentation.",
	"The editor will keep the current line's indentation and honor language defined brackets.",
	"The editor will keep the current line's indentation, honor language defined brackets and invoke special onEnterRules defined by languages.",
	"The editor will keep the current line's indentation, honor language defined brackets, invoke special onEnterRules defined by languages, and honor indentationRules defined by languages.",
	"Controls whether the editor should automatically adjust the indentation when users type, paste, move or indent lines.",
	"Use language configurations to determine when to automatically surround selections.",
	"Surround with quotes but not brackets.",
	"Surround with brackets but not quotes.",
	"Controls whether the editor should automatically surround selections when typing quotes or brackets.",
	"Emulate selection behavior of tab characters when using spaces for indentation. Selection will stick to tab stops.",
	"Controls whether the editor shows CodeLens.",
	"Controls the font family for CodeLens.",
	"Controls the font size in pixels for CodeLens. When set to 0, 90% of `#editor.fontSize#` is used.",
	"Controls whether the editor should render the inline color decorators and color picker.",
	"Make the color picker appear both on click and hover of the color decorator",
	"Make the color picker appear on hover of the color decorator",
	"Make the color picker appear on click of the color decorator",
	"Controls the condition to make a color picker appear from a color decorator",
	"Controls the max number of color decorators that can be rendered in an editor at once.",
	"Enable that the selection with the mouse and keys is doing column selection.",
	"Controls whether syntax highlighting should be copied into the clipboard.",
	"Control the cursor animation style.",
	"Smooth caret animation is disabled.",
	"Smooth caret animation is enabled only when the user moves the cursor with an explicit gesture.",
	"Smooth caret animation is always enabled.",
	"Controls whether the smooth caret animation should be enabled.",
	"Controls the cursor style.",
	"Controls the minimal number of visible leading lines (minimum 0) and trailing lines (minimum 1) surrounding the cursor. Known as 'scrollOff' or 'scrollOffset' in some other editors.",
	"`cursorSurroundingLines` is enforced only when triggered via the keyboard or API.",
	"`cursorSurroundingLines` is enforced always.",
	"Controls when `#cursorSurroundingLines#` should be enforced.",
	"Controls the width of the cursor when `#editor.cursorStyle#` is set to `line`.",
	"Controls whether the editor should allow moving selections via drag and drop.",
	"Use a new rendering method with svgs.",
	"Use a new rendering method with font characters.",
	"Use the stable rendering method.",
	"Controls whether whitespace is rendered with a new, experimental method.",
	"Scrolling speed multiplier when pressing `Alt`.",
	"Controls whether the editor has code folding enabled.",
	"Use a language-specific folding strategy if available, else the indentation-based one.",
	"Use the indentation-based folding strategy.",
	"Controls the strategy for computing folding ranges.",
	"Controls whether the editor should highlight folded ranges.",
	"Controls whether the editor automatically collapses import ranges.",
	"The maximum number of foldable regions. Increasing this value may result in the editor becoming less responsive when the current source has a large number of foldable regions.",
	"Controls whether clicking on the empty content after a folded line will unfold the line.",
	"Controls the font family.",
	"Controls whether the editor should automatically format the pasted content. A formatter must be available and the formatter should be able to format a range in a document.",
	"Controls whether the editor should automatically format the line after typing.",
	"Controls whether the editor should render the vertical glyph margin. Glyph margin is mostly used for debugging.",
	"Controls whether the cursor should be hidden in the overview ruler.",
	"Controls the letter spacing in pixels.",
	"Controls whether the editor has linked editing enabled. Depending on the language, related symbols such as HTML tags, are updated while editing.",
	"Controls whether the editor should detect links and make them clickable.",
	"Highlight matching brackets.",
	"A multiplier to be used on the `deltaX` and `deltaY` of mouse wheel scroll events.",
	"Zoom the font of the editor when using mouse wheel and holding `Ctrl`.",
	"Merge multiple cursors when they are overlapping.",
	"Maps to `Control` on Windows and Linux and to `Command` on macOS.",
	"Maps to `Alt` on Windows and Linux and to `Option` on macOS.",
	"The modifier to be used to add multiple cursors with the mouse. The Go to Definition and Open Link mouse gestures will adapt such that they do not conflict with the [multicursor modifier](https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier).",
	"Each cursor pastes a single line of the text.",
	"Each cursor pastes the full text.",
	"Controls pasting when the line count of the pasted text matches the cursor count.",
	"Controls the max number of cursors that can be in an active editor at once.",
	"Controls whether the editor should highlight semantic symbol occurrences.",
	"Controls whether a border should be drawn around the overview ruler.",
	"Focus the tree when opening peek",
	"Focus the editor when opening peek",
	"Controls whether to focus the inline editor or the tree in the peek widget.",
	"Controls whether the Go to Definition mouse gesture always opens the peek widget.",
	"Controls the delay in milliseconds after which quick suggestions will show up.",
	"Controls whether the editor auto renames on type.",
	"Deprecated, use `editor.linkedEditing` instead.",
	"Controls whether the editor should render control characters.",
	"Render last line number when the file ends with a newline.",
	"Highlights both the gutter and the current line.",
	"Controls how the editor should render the current line highlight.",
	"Controls if the editor should render the current line highlight only when the editor is focused.",
	"Render whitespace characters except for single spaces between words.",
	"Render whitespace characters only on selected text.",
	"Render only trailing whitespace characters.",
	"Controls how the editor should render whitespace characters.",
	"Controls whether selections should have rounded corners.",
	"Controls the number of extra characters beyond which the editor will scroll horizontally.",
	"Controls whether the editor will scroll beyond the last line.",
	"Scroll only along the predominant axis when scrolling both vertically and horizontally at the same time. Prevents horizontal drift when scrolling vertically on a trackpad.",
	"Controls whether the Linux primary clipboard should be supported.",
	"Controls whether the editor should highlight matches similar to the selection.",
	"Always show the folding controls.",
	"Never show the folding controls and reduce the gutter size.",
	"Only show the folding controls when the mouse is over the gutter.",
	"Controls when the folding controls on the gutter are shown.",
	"Controls fading out of unused code.",
	"Controls strikethrough deprecated variables.",
	"Show snippet suggestions on top of other suggestions.",
	"Show snippet suggestions below other suggestions.",
	"Show snippets suggestions with other suggestions.",
	"Do not show snippet suggestions.",
	"Controls whether snippets are shown with other suggestions and how they are sorted.",
	"Controls whether the editor will scroll using an animation.",
	"Controls whether the accessibility hint should be provided to screen reader users when an inline completion is shown.",
	"Font size for the suggest widget. When set to {0}, the value of {1} is used.",
	"Line height for the suggest widget. When set to {0}, the value of {1} is used. The minimum value is 8.",
	"Controls whether suggestions should automatically show up when typing trigger characters.",
	"Always select the first suggestion.",
	"Select recent suggestions unless further typing selects one, e.g. `console.| -> console.log` because `log` has been completed recently.",
	"Select suggestions based on previous prefixes that have completed those suggestions, e.g. `co -> console` and `con -> const`.",
	"Controls how suggestions are pre-selected when showing the suggest list.",
	"Tab complete will insert the best matching suggestion when pressing tab.",
	"Disable tab completions.",
	"Tab complete snippets when their prefix match. Works best when 'quickSuggestions' aren't enabled.",
	"Enables tab completions.",
	"Unusual line terminators are automatically removed.",
	"Unusual line terminators are ignored.",
	"Unusual line terminators prompt to be removed.",
	"Remove unusual line terminators that might cause problems.",
	"Inserting and deleting whitespace follows tab stops.",
	"Use the default line break rule.",
	"Word breaks should not be used for Chinese/Japanese/Korean (CJK) text. Non-CJK text behavior is the same as for normal.",
	"Controls the word break rules used for Chinese/Japanese/Korean (CJK) text.",
	"Characters that will be used as word separators when doing word related navigations or operations.",
	"Lines will never wrap.",
	"Lines will wrap at the viewport width.",
	"Lines will wrap at `#editor.wordWrapColumn#`.",
	"Lines will wrap at the minimum of viewport and `#editor.wordWrapColumn#`.",
	"Controls how lines should wrap.",
	"Controls the wrapping column of the editor when `#editor.wordWrap#` is `wordWrapColumn` or `bounded`.",
	"Controls whether inline color decorations should be shown using the default document color provider",
	"Controls whether the editor receives tabs or defers them to the workbench for navigation."
]);