/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'An optional set of arguments to run the shell executable with.',
	'Controls whether or not the profile name overrides the auto detected one.',
	'A codicon ID to associate with the terminal icon.',
	'A theme color ID to associate with the terminal icon.',
	"An object with environment variables that will be added to the terminal profile process. Set to `null` to delete environment variables from the base environment.",
	'A single path to a shell executable or an array of paths that will be used as fallbacks when one fails.',
	'A single path to a shell executable.',
	"A set of terminal profile customizations for {0} which allows adding, removing or changing how terminals are launched. Profiles are made up of a mandatory path, optional arguments and other presentation options.\n\nTo override an existing profile use its profile name as the key, for example:\n\n{1}\n\n{2}Read more about configuring profiles{3}.",
	"Integrated Terminal",
	"The terminal profile to use on Linux for automation-related terminal usage like tasks and debug.",
	"The terminal profile to use on macOS for automation-related terminal usage like tasks and debug.",
	"The terminal profile to use for automation-related terminal usage like tasks and debug. This setting will currently be ignored if {0} (now deprecated) is set.",
	'A profile source that will auto detect the paths to the shell. Note that non-standard executable locations are not supported and must be created manually in a new profile.',
	'The extension that contributed this profile.',
	'The id of the extension terminal',
	'The name of the extension terminal',
	'The extension that contributed this profile.',
	'The id of the extension terminal',
	'The name of the extension terminal',
	'The extension that contributed this profile.',
	'The id of the extension terminal',
	'The name of the extension terminal',
	'Controls whether or not WSL distros are shown in the terminal dropdown',
	"Whether new shells should inherit their environment from VS Code, which may source a login shell to ensure $PATH and other development variables are initialized. This has no effect on Windows.",
	"Controls the maximum amount of lines that will be restored when reconnecting to a persistent terminal session. Increasing this will restore more lines of scrollback at the cost of more memory and increase the time it takes to connect to terminals on start up. This setting requires a restart to take effect and should be set to a value less than or equal to `#terminal.integrated.scrollback#`.",
	"Whether to show hovers for links in the terminal output.",
	"A set of process names to ignore when using the {0} setting.",
	"Integrated Terminal",
	"The default terminal profile on Linux.",
	"The default terminal profile on macOS.",
	"The default terminal profile on Windows."
]);