/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Add Port",
	"Private",
	"Port",
	"The label and remote port number of the forwarded port.",
	"Forwarded Address",
	"The address that the forwarded port is available at.",
	"option + click",
	"alt + click",
	"cmd + click",
	"ctrl + click",
	"Running Process",
	"The command line of the process that is using the port.",
	"Origin",
	"The source that a forwarded port originates from. Can be an extension, user forwarded, statically forwarded, or automatically forwarded.",
	"Visibility",
	"The availability of the forwarded port.",
	"Press Enter to confirm or Escape to cancel.",
	"Process information unavailable",
	"Remote port {0}:{1} forwarded to local address {2}. ",
	"Remote port {0}:{1} not forwarded. ",
	"Port has running process.",
	"No running process.",
	"Port labeled {0}. ",
	"Unknown",
	"Private",
	"Whether the Ports view has focus.",
	"Ports",
	"Tunnel View",
	"Set Port Label",
	"Port label",
	"Forwarded port should be a number or a host:port.",
	"Port number must be \u2265 0 and < {0}.",
	"May Require Sudo",
	"Port is already forwarded",
	"Forward a Port",
	"Forward Port",
	"Port number or address (eg. 3000 or 10.10.10.10:2000).",
	"Unable to forward {0}:{1}. The host may not be available or that remote port may already be forwarded",
	"Unable to forward {0}:{1}. {2}",
	"No ports currently forwarded. Try running the {0} command",
	"Stop Forwarding Port",
	"Choose a port to stop forwarding",
	"Open in Browser",
	"Preview in Editor",
	"Open Port in Browser",
	"No ports currently forwarded. Open the Ports view to get started.",
	"Open the Ports view...",
	"Choose the port to open",
	"Copy Local Address",
	"Copy Forwarded Port Address",
	"Choose a forwarded port",
	"Change Local Address Port",
	"Local port should be a number.",
	"The local port {0} is not available. Port number {1} has been used instead",
	"New local port",
	"HTTP",
	"HTTPS",
	"Port Visibility",
	"Change Port Protocol",
	"The color of the icon for a port that has an associated running process."
]);