/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Record Keys",
	"Sort by Precedence (Highest first)",
	"Type to search in keybindings",
	"Recording Keys. Press Escape to exit",
	"Clear Keybindings Search Input",
	"Recording Keys",
	"Command",
	"Keybinding",
	"When",
	"Source",
	"Showing {0} Keybindings in precedence order",
	"Showing {0} Keybindings in alphabetical order",
	"Change Keybinding...",
	"Add Keybinding...",
	"Add Keybinding...",
	"Change When Expression",
	"Remove Keybinding",
	"Reset Keybinding",
	"Show Same Keybindings",
	"Copy",
	"Copy Command ID",
	"Copy Command Title",
	"Error '{0}' while editing the keybinding. Please open 'keybindings.json' file and check for errors.",
	"Change Keybinding {0}",
	"Change Keybinding",
	"Add Keybinding {0}",
	"Add Keybinding",
	"{0} ({1})",
	"Extension ({0})",
	"Keybindings",
	"No keybinding assigned",
	"No when context",
	"use space or enter to change the keybinding."
]);