/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'settingsEditor2',
	'keybindingsEditor',
	'openSettings2',
	'openUserSettingsJson',
	'openApplicationSettingsJson',
	'preferences',
	'settings',
	{ key: 'miOpenSettings', comment: ['&& denotes a mnemonic'] },
	'openSettings2',
	'openGlobalSettings',
	'openRawDefaultSettings',
	'openWorkspaceSettings',
	'openAccessibilitySettings',
	'openWorkspaceSettingsFile',
	'openFolderSettings',
	'openFolderSettingsFile',
	'openFolderSettings',
	{ key: 'miOpenOnlineSettings', comment: ['&& denotes a mnemonic'] },
	'filterUntrusted',
	{ key: 'miOpenTelemetrySettings', comment: ['&& denotes a mnemonic'] },
	'openRemoteSettings',
	'openRemoteSettingsJSON',
	'settings.focusSearch',
	'settings.clearResults',
	'settings.focusFile',
	'settings.focusFile',
	'settings.focusSettingsList',
	'settings.focusSettingsTOC',
	'settings.focusSettingControl',
	'settings.showContextMenu',
	'settings.focusLevelUp',
	'preferences',
	'openGlobalKeybindings',
	'keyboardShortcuts',
	'keyboardShortcuts',
	'openDefaultKeybindingsFile',
	'openGlobalKeybindingsFile',
	'showDefaultKeybindings',
	'showExtensionKeybindings',
	'showUserKeybindings',
	'clear',
	'clearHistory',
	'defineKeybinding.start',
	'openSettingsJson',
	{ key: 'miPreferences', comment: ['&& denotes a mnemonic'] }
]);