/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Settings Editor 2",
	"Keybindings Editor",
	"Open Settings (UI)",
	"Open User Settings (JSON)",
	"Open Application Settings (JSON)",
	"Preferences",
	"Settings",
	"&&Settings",
	"Open Settings (UI)",
	"Open User Settings",
	"Open Default Settings (JSON)",
	"Open Workspace Settings",
	"Open Accessibility Settings",
	"Open Workspace Settings (JSON)",
	"Open Folder Settings",
	"Open Folder Settings (JSON)",
	"Open Folder Settings",
	"&&Online Services Settings",
	"Show untrusted workspace settings",
	"&&Telemetry Settings",
	"Open Remote Settings ({0})",
	"Open Remote Settings (JSON) ({0})",
	"Focus Settings Search",
	"Clear Settings Search Results",
	"Focus settings file",
	"Focus settings file",
	"Focus settings list",
	"Focus Settings Table of Contents",
	"Focus Setting Control",
	"Show Setting Context Menu",
	"Move Focus Up One Level",
	"Preferences",
	"Open Keyboard Shortcuts",
	"Keyboard Shortcuts",
	"Keyboard Shortcuts",
	"Open Default Keyboard Shortcuts (JSON)",
	"Open Keyboard Shortcuts (JSON)",
	"Show System Keybindings",
	"Show Extension Keybindings",
	"Show User Keybindings",
	"Clear Search Results",
	"Clear Keyboard Shortcuts Search History",
	"Define Keybinding",
	"Open Settings (JSON)",
	"&&Preferences"
]);