/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Setting value not applied",
	"The setting value can only be applied in a trusted workspace.",
	"Manage Workspace Trust",
	'Not synced',
	"This setting is ignored during sync",
	"Default value changed",
	"User",
	"Workspace",
	"Remote",
	"Setting value not applied",
	"This setting is managed by your organization and its applied value cannot be changed.",
	"View policy settings",
	"Applies to all profiles",
	"The setting is not specific to the current profile, and will retain its value when switching profiles.",
	"Also modified in",
	"Modified in",
	"Also modified elsewhere",
	"Modified elsewhere",
	"The setting has also been modified in the following scopes:",
	"The setting has been modified in the following scopes:",
	"The following languages have default overrides:",
	"Default setting value overridden by {0}",
	"User",
	"Workspace",
	"Remote",
	"The {0} scope for {1}",
	"User",
	"Workspace",
	"Remote",
	"the {0} scope for {1}",
	"Workspace untrusted; setting value not applied",
	"Managed by organization policy; setting value not applied",
	"Setting value retained when switching profiles",
	"Also modified in",
	"Modified in",
	"Setting ignored during sync",
	"{0} overrides the default value",
	"Language-specific default values exist for {0}"
]);