/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"OK",
	"Cancel",
	"List item `{0}`",
	"List item `{0}` with sibling `${1}`",
	"Remove Item",
	"Edit Item",
	"Add Item",
	"Item...",
	"Sibling...",
	"Exclude files matching `{0}`",
	"Exclude files matching `{0}`, only when a file matching `{1}` is present",
	"Remove Exclude Item",
	"Edit Exclude Item",
	"Add Pattern",
	"Exclude Pattern...",
	"When Pattern Is Present...",
	"Include files matching `{0}`",
	"Include files matching `{0}`, only when a file matching `{1}` is present",
	"Remove Include Item",
	"Edit Include Item",
	"Add Pattern",
	"Include Pattern...",
	"When Pattern Is Present...",
	"OK",
	"Cancel",
	"Key",
	"Value",
	"The property `{0}` is set to `{1}`.",
	"Remove Item",
	"Reset Item",
	"Edit Item",
	"Add Item",
	"Item",
	"Value",
	"The property `{0}` is set to `{1}`.",
	"Remove Item",
	"Reset Item",
	"Edit Item",
	"Add Item",
	"Item",
	"Value"
]);