/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Breadcrumb Navigation",
	"Enable/disable navigation breadcrumbs.",
	"Controls whether and how file paths are shown in the breadcrumbs view.",
	"Show the file path in the breadcrumbs view.",
	"Do not show the file path in the breadcrumbs view.",
	"Only show the last element of the file path in the breadcrumbs view.",
	"Controls whether and how symbols are shown in the breadcrumbs view.",
	"Show all symbols in the breadcrumbs view.",
	"Do not show symbols in the breadcrumbs view.",
	"Only show the current symbol in the breadcrumbs view.",
	"Controls how symbols are sorted in the breadcrumbs outline view.",
	"Show symbol outline in file position order.",
	"Show symbol outline in alphabetical order.",
	"Show symbol outline in symbol type order.",
	"Render breadcrumb items with icons.",
	"When enabled breadcrumbs show `file`-symbols.",
	"When enabled breadcrumbs show `module`-symbols.",
	"When enabled breadcrumbs show `namespace`-symbols.",
	"When enabled breadcrumbs show `package`-symbols.",
	"When enabled breadcrumbs show `class`-symbols.",
	"When enabled breadcrumbs show `method`-symbols.",
	"When enabled breadcrumbs show `property`-symbols.",
	"When enabled breadcrumbs show `field`-symbols.",
	"When enabled breadcrumbs show `constructor`-symbols.",
	"When enabled breadcrumbs show `enum`-symbols.",
	"When enabled breadcrumbs show `interface`-symbols.",
	"When enabled breadcrumbs show `function`-symbols.",
	"When enabled breadcrumbs show `variable`-symbols.",
	"When enabled breadcrumbs show `constant`-symbols.",
	"When enabled breadcrumbs show `string`-symbols.",
	"When enabled breadcrumbs show `number`-symbols.",
	"When enabled breadcrumbs show `boolean`-symbols.",
	"When enabled breadcrumbs show `array`-symbols.",
	"When enabled breadcrumbs show `object`-symbols.",
	"When enabled breadcrumbs show `key`-symbols.",
	"When enabled breadcrumbs show `null`-symbols.",
	"When enabled breadcrumbs show `enumMember`-symbols.",
	"When enabled breadcrumbs show `struct`-symbols.",
	"When enabled breadcrumbs show `event`-symbols.",
	"When enabled breadcrumbs show `operator`-symbols.",
	"When enabled breadcrumbs show `typeParameter`-symbols."
]);