/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'textEditor',
	'textDiffEditor',
	'binaryDiffEditor',
	'sideBySideEditor',
	'editorQuickAccessPlaceholder',
	'activeGroupEditorsByMostRecentlyUsedQuickAccess',
	'editorQuickAccessPlaceholder',
	'allEditorsByAppearanceQuickAccess',
	'editorQuickAccessPlaceholder',
	'allEditorsByMostRecentlyUsedQuickAccess',
	'unlockGroupAction',
	'closeGroupAction',
	'splitUp',
	'splitDown',
	'splitLeft',
	'splitRight',
	'toggleLockGroup',
	'close',
	'splitUp',
	'splitDown',
	'splitLeft',
	'splitRight',
	'toggleTabs',
	'close',
	'closeOthers',
	'closeRight',
	'closeAllSaved',
	'closeAll',
	'reopenWith',
	'keepOpen',
	'pin',
	'unpin',
	'splitUp',
	'splitDown',
	'splitLeft',
	'splitRight',
	'splitInGroup',
	'joinInGroup',
	'inlineView',
	'showOpenedEditors',
	'closeAll',
	'closeAllSaved',
	'toggleTabs',
	'togglePreviewMode',
	'lockGroup',
	'splitEditorRight',
	'splitEditorDown',
	'splitEditorDown',
	'splitEditorRight',
	'toggleSplitEditorInGroupLayout',
	'close',
	'closeAll',
	'close',
	'closeAll',
	'unpin',
	'close',
	'unpin',
	'close',
	'unlockEditorGroup',
	'previousChangeIcon',
	'nextChangeIcon',
	'toggleWhitespace',
	'navigate.prev.label',
	'navigate.next.label',
	'ignoreTrimWhitespace.label',
	'keepEditor',
	'pinEditor',
	'unpinEditor',
	'closeEditor',
	'closePinnedEditor',
	'closeEditorsInGroup',
	'closeSavedEditors',
	'closeOtherEditors',
	'closeRightEditors',
	'closeEditorGroup',
	'reopenWith',
	{ key: 'miReopenClosedEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miClearRecentOpen', comment: ['&& denotes a mnemonic'] },
	'miShare',
	{ key: 'miEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miSplitEditorUpWithoutMnemonic',
	{ key: 'miSplitEditorUp', comment: ['&& denotes a mnemonic'] },
	'miSplitEditorDownWithoutMnemonic',
	{ key: 'miSplitEditorDown', comment: ['&& denotes a mnemonic'] },
	'miSplitEditorLeftWithoutMnemonic',
	{ key: 'miSplitEditorLeft', comment: ['&& denotes a mnemonic'] },
	'miSplitEditorRightWithoutMnemonic',
	{ key: 'miSplitEditorRight', comment: ['&& denotes a mnemonic'] },
	'miSplitEditorInGroupWithoutMnemonic',
	{ key: 'miSplitEditorInGroup', comment: ['&& denotes a mnemonic'] },
	'miJoinEditorInGroupWithoutMnemonic',
	{ key: 'miJoinEditorInGroup', comment: ['&& denotes a mnemonic'] },
	'miSingleColumnEditorLayoutWithoutMnemonic',
	{ key: 'miSingleColumnEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miTwoColumnsEditorLayoutWithoutMnemonic',
	{ key: 'miTwoColumnsEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miThreeColumnsEditorLayoutWithoutMnemonic',
	{ key: 'miThreeColumnsEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miTwoRowsEditorLayoutWithoutMnemonic',
	{ key: 'miTwoRowsEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miThreeRowsEditorLayoutWithoutMnemonic',
	{ key: 'miThreeRowsEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miTwoByTwoGridEditorLayoutWithoutMnemonic',
	{ key: 'miTwoByTwoGridEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miTwoRowsRightEditorLayoutWithoutMnemonic',
	{ key: 'miTwoRowsRightEditorLayout', comment: ['&& denotes a mnemonic'] },
	'miTwoColumnsBottomEditorLayoutWithoutMnemonic',
	{ key: 'miTwoColumnsBottomEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miLastEditLocation', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFirstSideEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSecondSideEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextRecentlyUsedEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousRecentlyUsedEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextUsedEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousUsedEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSwitchEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusFirstGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusSecondGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusThirdGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusFourthGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusFifthGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusLeftGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusRightGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusAboveGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusBelowGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSwitchGroup', comment: ['&& denotes a mnemonic'] }
]);