/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Ln {0}, Col {1} ({2} selected)",
	"Ln {0}, Col {1}",
	"{0} selections ({1} characters selected)",
	"{0} selections",
	"LF",
	"CRLF",
	"No text editor active at this time",
	"The active code editor is read-only.",
	"convert file",
	"change view",
	"Select Action",
	"Tab Moves Focus",
	"Accessibility Mode",
	"Disable Accessibility Mode",
	"Column Selection",
	"Column Selection Mode",
	"Disable Column Selection Mode",
	"Editor Selection",
	"Go to Line/Column",
	"Editor Indentation",
	"Select Indentation",
	"Editor Encoding",
	"Select Encoding",
	"Editor End of Line",
	"Select End of Line Sequence",
	"Editor Language",
	"Select Language Mode",
	"File Information",
	"File Information",
	"Spaces: {0}",
	"Spaces: {0} (Tab Size: {1})",
	"Tab Size: {0}",
	"Current Problem",
	"Current Problem",
	"Search Marketplace Extensions for '{0}'...",
	"Change Language Mode",
	"No text editor active at this time",
	"({0}) - Configured Language",
	"({0})",
	"languages (identifier)",
	"Configure '{0}' language based settings...",
	"Configure File Association for '{0}'...",
	"Auto Detect",
	"Select Language Mode",
	"Current Association",
	"Select Language Mode to Associate with '{0}'",
	"Change End of Line Sequence",
	"No text editor active at this time",
	"The active code editor is read-only.",
	"Select End of Line Sequence",
	"Change File Encoding",
	"No text editor active at this time",
	"No text editor active at this time",
	"No file active at this time",
	"Save with Encoding",
	"Reopen with Encoding",
	"Select Action",
	"Guessed from content",
	"Select File Encoding to Reopen File",
	"Select File Encoding to Save with"
]);