/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Split Editor",
	"Split Editor Orthogonal",
	"Split Editor Left",
	"Split Editor Right",
	"Split Editor Up",
	"Split Editor Up",
	"Split Editor Down",
	"Split Editor Down",
	"Join Editor Group with Next Group",
	"Join All Editor Groups",
	"Navigate Between Editor Groups",
	"Focus Active Editor Group",
	"Focus First Editor Group",
	"Focus Last Editor Group",
	"Focus Next Editor Group",
	"Focus Previous Editor Group",
	"Focus Left Editor Group",
	"Focus Right Editor Group",
	"Focus Editor Group Above",
	"Focus Editor Group Below",
	"Close Editor",
	"Unpin Editor",
	"Close",
	"Revert and Close Editor",
	"Close Editors to the Left in Group",
	"Close All Editors",
	"Close All Editor Groups",
	"Close Editors in Other Groups",
	"Close Editor in All Groups",
	"Move Editor Group Left",
	"Move Editor Group Right",
	"Move Editor Group Up",
	"Move Editor Group Down",
	"Duplicate Editor Group Left",
	"Duplicate Editor Group Right",
	"Duplicate Editor Group Up",
	"Duplicate Editor Group Down",
	"Maximize Editor Group",
	"Reset Editor Group Sizes",
	"Toggle Editor Group Sizes",
	"Maximize Editor Group and Hide Side Bars",
	"Open Next Editor",
	"Open Previous Editor",
	"Open Next Editor in Group",
	"Open Previous Editor in Group",
	"Open First Editor in Group",
	"Open Last Editor in Group",
	"Go Forward",
	"Go Forward",
	"&&Forward",
	"Go Back",
	"Go Back",
	"&&Back",
	"Go Previous",
	"Go Forward in Edit Locations",
	"Go Back in Edit Locations",
	"Go Previous in Edit Locations",
	"Go to Last Edit Location",
	"Go Forward in Navigation Locations",
	"Go Back in Navigation Locations",
	"Go Previous in Navigation Locations",
	"Go to Last Navigation Location",
	"Reopen Closed Editor",
	"Clear Recently Opened",
	"Do you want to clear all recently opened files and workspaces?",
	"This action is irreversible!",
	"&&Clear",
	"Show Editors in Active Group By Most Recently Used",
	"Show All Editors By Appearance",
	"Show All Editors By Most Recently Used",
	"Quick Open Previous Recently Used Editor",
	"Quick Open Least Recently Used Editor",
	"Quick Open Previous Recently Used Editor in Group",
	"Quick Open Least Recently Used Editor in Group",
	"Quick Open Previous Editor from History",
	"Open Next Recently Used Editor",
	"Open Previous Recently Used Editor",
	"Open Next Recently Used Editor In Group",
	"Open Previous Recently Used Editor In Group",
	"Clear Editor History",
	"Do you want to clear the history of recently opened editors?",
	"This action is irreversible!",
	"&&Clear",
	"Move Editor Left",
	"Move Editor Right",
	"Move Editor into Previous Group",
	"Move Editor into Next Group",
	"Move Editor into Group Above",
	"Move Editor into Group Below",
	"Move Editor into Left Group",
	"Move Editor into Right Group",
	"Move Editor into First Group",
	"Move Editor into Last Group",
	"Split Editor into Previous Group",
	"Split Editor into Next Group",
	"Split Editor into Group Above",
	"Split Editor into Group Below",
	"Split Editor into Left Group",
	"Split Editor into Left Group",
	"Split Editor into Right Group",
	"Split Editor into First Group",
	"Split Editor into Last Group",
	"Single Column Editor Layout",
	"Two Columns Editor Layout",
	"Three Columns Editor Layout",
	"Two Rows Editor Layout",
	"Three Rows Editor Layout",
	"Grid Editor Layout (2x2)",
	"Two Columns Bottom Editor Layout",
	"Two Rows Right Editor Layout",
	"New Editor Group to the Left",
	"New Editor Group to the Right",
	"New Editor Group Above",
	"New Editor Group Below",
	"Toggle Editor Type",
	"Reopen Editor With Text Editor"
]);