/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Conflicts",
	"Synced Machines",
	"Edit Name",
	"Turn off Settings Sync",
	"Sync Activity (Remote)",
	"Sync Activity (Local)",
	"Sync Activity (Developer)",
	"Extract Sync Activity",
	"Select Sync Activity File or Folder",
	"Show raw JSON sync data",
	"Compare with Local",
	"{0} ↔ {1}",
	"{0} (Remote)",
	"{0} (Local)",
	"Restore",
	"Would you like to replace your current {0} with selected?",
	"Troubleshoot",
	"Reset Synced Data",
	"{0} ↔ {1}",
	"Current",
	"Current",
	"No Machines",
	"Current",
	"machine not found with id: {0}",
	"Are you sure you want to turn off sync on selected machines?",
	"Are you sure you want to turn off sync on {0}?",
	"&&Turn off",
	"Enter the name of the machine",
	"machine not found with id: {0}",
	"Machine name should be unique and not empty",
	"Logs",
	"Last Synced Remotes",
	"Current"
]);