/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'stop sync',
	'configure sync',
	'sync now',
	'syncing',
	'synced with time',
	'sync settings',
	'show synced data',
	'conflicts detected',
	'replace remote',
	'replace local',
	'show conflicts',
	'accept failed',
	'accept failed',
	'session expired',
	'turn on sync',
	'turned off',
	'turn on sync',
	'too large',
	'too many profiles',
	'error upgrade required',
	'operationId',
	'method not found',
	'operationId',
	'show sync logs',
	'report issue',
	'error reset required',
	'reset',
	'show synced data action',
	'service switched to insiders',
	'service switched to stable',
	'using separate service',
	'service changed and turned off',
	'turn on sync',
	'operationId',
	'open file',
	'errorInvalidConfiguration',
	'open file',
	'has conflicts',
	'turning on syncing',
	'sign in to sync',
	'no authentication providers',
	'too large while starting sync',
	'error upgrade required while starting sync',
	'operationId',
	'error reset required while starting sync',
	'reset',
	'show synced data action',
	'auth failed',
	'turn on failed with user data sync error',
	{ key: 'turn on failed', comment: ['Substitution is for error reason'] },
	'sign in and turn on',
	'configure and turn on sync detail',
	'per platform',
	'configure sync title',
	'configure sync placeholder',
	'turn off sync confirmation',
	'turn off sync detail',
	{ key: 'turn off', comment: ['&& denotes a mnemonic'] },
	'turn off sync everywhere',
	'switchSyncService.title',
	'switchSyncService.description',
	'default',
	'insiders',
	'stable',
	'global activity turn on sync',
	'turnin on sync',
	'cancel turning on sync',
	'sign in global',
	'sign in accounts',
	'resolveConflicts_global',
	'sync is on',
	'turn off failed',
	'configure',
	'show sync log title',
	'show sync log toolrip',
	'complete merges title',
	'download sync activity title',
	'download sync activity dialog title',
	'download sync activity dialog open label',
	'workbench.actions.syncData.reset'
]);