/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Turn Off",
	"Configure...",
	"Sync Now",
	"syncing",
	"synced {0}",
	"Show Settings",
	"Show Synced Data",
	"Unable to sync due to conflicts in {0}. Please resolve them to continue.",
	"Replace Remote",
	"Replace Local",
	"Show Conflicts",
	"Error while accepting changes. Please check [logs]({0}) for more details.",
	"Error while accepting changes. Please check [logs]({0}) for more details.",
	"Settings sync was turned off because current session is expired, please sign in again to turn on sync.",
	"Turn on Settings Sync...",
	"Settings sync was turned off from another device, please turn on sync again.",
	"Turn on Settings Sync...",
	"Disabled syncing {0} because size of the {1} file to sync is larger than {2}. Please open the file and reduce the size and enable sync",
	"Disabled syncing profiles because there are too many profiles to sync. Settings Sync supports syncing maximum 20 profiles. Please reduce the number of profiles and enable sync",
	"Settings sync is disabled because the current version ({0}, {1}) is not compatible with the sync service. Please update before turning on sync.",
	"Operation Id: {0}",
	"Settings sync is disabled because the client is making invalid requests. Please report an issue with the logs.",
	"Operation Id: {0}",
	"Show Log",
	"Report Issue",
	"Settings sync is disabled because your data in the cloud is older than that of the client. Please clear your data in the cloud before turning on sync.",
	"Clear Data in Cloud...",
	"Show Synced Data",
	"Settings Sync has been switched to insiders service",
	"Settings Sync has been switched to stable service",
	"Settings sync now uses a separate service, more information is available in the [Settings Sync Documentation](https://aka.ms/vscode-settings-sync-help#_syncing-stable-versus-insiders).",
	"Settings sync was turned off because {0} now uses a separate service. Please turn on sync again.",
	"Turn on Settings Sync...",
	"Operation Id: {0}",
	"Open {0} File",
	"Unable to sync {0} because the content in the file is not valid. Please open the file and correct it.",
	"Open {0} File",
	"{0}: Conflicts Detected",
	"Turning on Settings Sync...",
	"Sign in to Sync Settings",
	"No authentication providers are available.",
	"Settings sync cannot be turned on because size of the {0} file to sync is larger than {1}. Please open the file and reduce the size and turn on sync",
	"Settings sync cannot be turned on because the current version ({0}, {1}) is not compatible with the sync service. Please update before turning on sync.",
	"Operation Id: {0}",
	"Settings sync cannot be turned on because your data in the cloud is older than that of the client. Please clear your data in the cloud before turning on sync.",
	"Clear Data in Cloud...",
	"Show Synced Data",
	"Error while turning on Settings Sync: Authentication failed.",
	"Error while turning on Settings Sync. Please check [logs]({0}) for more details.",
	"Error while turning on Settings Sync. {0}",
	"Sign in & Turn on",
	"Please sign in to synchronize your data across devices.",
	"for each platform",
	"{0}: Configure...",
	"Choose what to sync",
	"Do you want to turn off sync?",
	"Your settings, keybindings, extensions, snippets and UI State will no longer be synced.",
	"&&Turn off",
	"Turn off sync on all your devices and clear the data from the cloud.",
	"{0}: Select Service",
	"Ensure you are using the same settings sync service when syncing with multiple environments",
	"Default",
	"Insiders",
	"Stable",
	"Backup and Sync Settings...",
	"Turning on Settings Sync...",
	"Cancel",
	"Sign in to Sync Settings",
	"Sign in to Sync Settings (1)",
	"Show Conflicts ({0})",
	"Settings Sync is On",
	"Error while turning off Settings Sync. Please check [logs]({0}) for more details.",
	"Configure...",
	"{0}: Show Log",
	"Show Log",
	"Complete Merge",
	"Download Settings Sync Activity",
	"Select folder to download Settings Sync activity",
	"Save",
	"Clear Data in Cloud..."
]);