/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'manageExtensionIcon',
	'themes.selectMarketplaceTheme',
	'search.error',
	'installExtension.confirm',
	'installExtension.button.ok',
	'installing extensions',
	'selectTheme.label',
	'installColorThemes',
	'browseColorThemes',
	'themes.selectTheme',
	'themes.category.light',
	'themes.category.dark',
	'themes.category.hc',
	'selectIconTheme.label',
	'installIconThemes',
	'themes.selectIconTheme',
	'fileIconThemeCategory',
	'noIconThemeLabel',
	'noIconThemeDesc',
	'selectProductIconTheme.label',
	'installProductIconThemes',
	'browseProductIconThemes',
	'themes.selectProductIconTheme',
	'productIconThemeCategory',
	'defaultProductIconThemeLabel',
	'manage extension',
	'generateColorTheme.label',
	'toggleLightDarkThemes.label',
	'browseColorThemeInMarketPlace.label',
	'themes',
	{ key: 'miSelectTheme', comment: ['&& denotes a mnemonic'] },
	'selectTheme.label',
	'themes.selectIconTheme.label',
	'themes.selectProductIconTheme.label',
	'button.keep',
	'button.browse',
	'button.revert',
	{ key: 'themeUpdatedNotification', comment: ['{0} is the name of the new default theme'] },
	'button.tryTheme',
	'button.cancel',
	{ key: 'newThemeNotification', comment: ['{0} is the name of the new default theme'] }
]);