/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Icon for the \'Manage\' action in the theme selection quick pick.',
	"Type to Search More. Select to Install. Up/Down Keys to Preview",
	'Error while searching for themes: {0}',
	"This will install extension '{0}' published by '{1}'. Do you want to continue?",
	"OK",
	"Installing Extension {0}...",
	"Color Theme",
	"Install Additional Color Themes...",
	"Browse Additional Color Themes...",
	"Select Color Theme (Up/Down Keys to Preview)",
	"light themes",
	"dark themes",
	"high contrast themes",
	"File Icon Theme",
	"Install Additional File Icon Themes...",
	"Select File Icon Theme (Up/Down Keys to Preview)",
	'file icon themes',
	'None',
	'Disable File Icons',
	"Product Icon Theme",
	"Install Additional Product Icon Themes...",
	"Browse Additional Product Icon Themes...",
	"Select Product Icon Theme (Up/Down Keys to Preview)",
	'product icon themes',
	'Default',
	"Manage Extension",
	"Generate Color Theme From Current Settings",
	"Toggle between Light/Dark Themes",
	"Browse Color Themes in Marketplace",
	"Themes",
	"&&Theme",
	"Color Theme",
	"File Icon Theme",
	"Product Icon Theme",
	"Keep New Theme",
	"Browse Themes",
	"Revert",
	"Visual Studio Code now ships with a new default theme '{0}'. If you prefer, you can switch back to the old theme or try one of the many other color themes available.",
	"Try New Theme",
	"Cancel",
	"Visual Studio Code now ships with a new default theme '{0}'. Do you want to give it a try?"
]);