/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'nonempty',
	'requirestring',
	'optstring',
	'optstring',
	'optstring',
	'optstring',
	'optstring',
	'vscode.extension.contributes.keybindings.command',
	'vscode.extension.contributes.keybindings.args',
	'vscode.extension.contributes.keybindings.key',
	'vscode.extension.contributes.keybindings.mac',
	'vscode.extension.contributes.keybindings.linux',
	'vscode.extension.contributes.keybindings.win',
	'vscode.extension.contributes.keybindings.when',
	'vscode.extension.contributes.keybindings',
	'invalid.keybindings',
	'unboundCommands',
	'keybindings.json.title',
	'keybindings.json.command',
	'keybindings.json.removalCommand',
	'keybindings.json.key',
	'keybindings.commandsIsArray',
	'keybindings.json.when',
	'keybindings.json.args'
]);