/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'welcomeAriaLabel',
	'pickWalkthroughs',
	'welcome',
	'checkboxTitle',
	'welcomePage.showOnStartup',
	{ key: 'gettingStarted.editingEvolved', comment: ['Shown as subtitle on the Welcome page.'] },
	'welcomePage.openFolderWithPath',
	'recent',
	'noRecents',
	'openFolder',
	'toStart',
	'show more recents',
	'showAll',
	'start',
	'new',
	{ key: 'newItems', comment: ['Shown when a list of items has changed based on an update from a remote source'] },
	'close',
	'closeAriaLabel',
	'walkthroughs',
	'showAll',
	'close',
	'closeAriaLabel',
	'gettingStarted.allStepsComplete',
	'gettingStarted.someStepsComplete',
	'gettingStarted.keyboardTip',
	'imageShowing',
	'allDone',
	'nextOne',
	'privacy statement',
	'optOut',
	{ key: 'footer', comment: ['fist substitution is "vs code", second is "privacy statement", third is "opt out".'] }
]);