/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'markersViewIcon',
	{ key: 'miMarker', comment: ['&& denotes a mnemonic'] },
	'viewAsTree',
	'viewAsTable',
	'toggle errors',
	'problems',
	'errors',
	'toggle warnings',
	'problems',
	'warnings',
	'toggle infos',
	'problems',
	'Infos',
	'toggle active file',
	'problems',
	'Active File',
	'toggle Excluded Files',
	'problems',
	'Excluded Files',
	'copyMarker',
	'copyMessage',
	'copyMessage',
	'focusProblemsList',
	'focusProblemsFilter',
	'show multiline',
	'problems',
	'show singleline',
	'problems',
	'clearFiltersText',
	'problems',
	'collapseAll',
	'status.problems',
	'totalErrors',
	'totalWarnings',
	'totalInfos',
	'noProblems',
	'manyProblems',
	'totalProblems'
]);