/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'View icon of the markers view.',
	"&&Problems",
	"View as Tree",
	"View as Table",
	"Toggle Errors",
	"Problems",
	"Show Errors",
	"Toggle Warnings",
	"Problems",
	"Show Warnings",
	"Toggle Infos",
	"Problems",
	"Show Infos",
	"Toggle Active File",
	"Problems",
	"Show Active File Only",
	"Toggle Excluded Files",
	"Problems",
	"Hide Excluded Files",
	"Copy",
	"Copy Message",
	"Copy Message",
	"Focus problems view",
	"Focus problems filter",
	"Show message in multiple lines",
	"Problems",
	"Show message in single line",
	"Problems",
	"Clear filters text",
	"Problems",
	"Collapse All",
	"Problems",
	"Errors: {0}",
	"Warnings: {0}",
	"Infos: {0}",
	"No Problems",
	"10K+",
	'Total {0} Problems'
]);