/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Configure Task",
	"Tasks",
	'Select the build task (there is no default build task defined)',
	"Filters the tasks shown in the quickpick",
	"The task's label or a term to filter by",
	"The contributed task type",
	"The task's label or a term to filter by",
	'There are task errors. See the output for details.',
	"Show output",
	'The folder {0} is ignored since it uses task version 0.1.0',
	'Warning: {0} tasks are unavailable in the current environment.\n',
	'No test task defined. Mark a task with \'isTestCommand\' in the tasks.json file.',
	'No test task defined. Mark a task with as a \'test\' group in the tasks.json file.',
	'No build task defined. Mark a task with \'isBuildCommand\' in the tasks.json file.',
	'No build task defined. Mark a task with as a \'build\' group in the tasks.json file.',
	'Task to execute is undefined',
	'associate',
	'Continue without scanning the task output',
	'Never scan the task output for this task',
	'Never scan the task output for {0} tasks',
	'Learn more about scanning the task output',
	'Select for which kind of errors and warnings to scan the task output',
	'The current task configuration has errors. Please fix the errors first before customizing a task.',
	'\t// See https://go.microsoft.com/fwlink/?LinkId=733558 \n\t// for the documentation about the tasks.json format',
	'There are many build tasks defined in the tasks.json. Executing the first one.\n',
	"Save all editors?",
	"Do you want to save all editors before running the task?",
	'&&Save',
	'Don\'t save',
	'The task \'{0}\' is already active.',
	"Terminate Task",
	"Restart Task",
	'There is already a task running. Terminate it first before executing another task.',
	'Failed to terminate and restart task {0}',
	"The task provider for \"{0}\" tasks unexpectedly provided a task of type \"{1}\".\n",
	'Warning: {0} tasks are unavailable in the current environment.\n',
	'Error: The {0} task detection didn\'t contribute a task for the following configuration:\n{1}\nThe task will be ignored.\n',
	'Error: the provided task configuration has validation errors and can\'t not be used. Please correct the errors first.',
	'Error: The content of the tasks json in {0} has syntax errors. Please correct them before executing a task.\n',
	'workspace file',
	'Only tasks version 2.0.0 permitted in workspace configuration files.',
	'user settings',
	'Only tasks version 2.0.0 permitted in user settings.',
	'Workspace folder was undefined',
	'Error: the provided task configuration has validation errors and can\'t not be used. Please correct the errors first.',
	'Ignoring task configurations for workspace folder {0}. Multi folder workspace task support requires that all folders use task version 2.0.0\n',
	'Error: The content of the tasks.json file has syntax errors. Please correct them before executing a task.\n',
	"Terminate Task",
	'An error has occurred while running a task. See task log for details.',
	"Configure Task",
	'recently used tasks',
	'configured tasks',
	'detected tasks',
	'The following workspace folders are ignored since they use task version 0.1.0: {0}',
	"Don't Show Again",
	"Listing and running tasks requires that some of the files in this workspace be executed as code.",
	'Select the task to run',
	'Configure a Task',
	'Configure a Task',
	'Fetching build tasks...',
	'Select the build task to run',
	'No build task to run found. Configure Build Task...',
	'Fetching test tasks...',
	'Select the test task to run',
	'No test task to run found. Configure Tasks...',
	'Select a task to terminate',
	'No task is currently running',
	'All Running Tasks',
	'The launched process doesn\'t exist anymore. If the task spawned background tasks exiting VS Code might result in orphaned processes.',
	'Failed to terminate running task',
	'Select the task to restart',
	'No task to restart',
	'Select a Task Template',
	'User',
	'Create tasks.json file from template',
	'Open tasks.json file',
	'Select a task to configure',
	'{0} is already marked as the default build task',
	'Select a task to configure',
	'Select the task to be used as the default build task',
	'{0} is already marked as the default test task.',
	'Select the task to be used as the default test task',
	'Select the task to show its output',
	'No task is running',
	"The deprecated tasks version 0.1.0 has been removed. Your tasks have been upgraded to version 2.0.0. Open the diff to review the upgrade.",
	"The deprecated tasks version 0.1.0 has been removed. Your tasks have been upgraded to version 2.0.0. Open the diffs to review the upgrade.",
	"Open diff",
	"Open diffs"
]);