/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'building',
	'status.runningTasks',
	'numberOfRunningTasks',
	'runningTasks',
	{ key: 'miRunTask', comment: ['&& denotes a mnemonic'] },
	{ key: 'miBuildTask', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRunningTask', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRestartTask', comment: ['&& denotes a mnemonic'] },
	{ key: 'miTerminateTask', comment: ['&& denotes a mnemonic'] },
	{ key: 'miConfigureTask', comment: ['&& denotes a mnemonic'] },
	{ key: 'miConfigureBuildTask', comment: ['&& denotes a mnemonic'] },
	'workbench.action.tasks.openWorkspaceFileTasks',
	'ShowLogAction.label',
	'RunTaskAction.label',
	'ReRunTaskAction.label',
	'RestartTaskAction.label',
	'ShowTasksAction.label',
	'TerminateAction.label',
	'BuildAction.label',
	'TestAction.label',
	'ConfigureDefaultBuildTask.label',
	'ConfigureDefaultTestTask.label',
	'workbench.action.tasks.openUserTasks',
	'userTasks',
	'tasksQuickAccessPlaceholder',
	'tasksQuickAccessHelp',
	'tasksConfigurationTitle',
	'task.problemMatchers.neverPrompt',
	'task.problemMatchers.neverPrompt.boolean',
	'task.problemMatchers.neverPrompt.array',
	'task.autoDetect',
	'task.slowProviderWarning',
	'task.slowProviderWarning.boolean',
	'task.slowProviderWarning.array',
	'task.quickOpen.history',
	'task.quickOpen.detail',
	'task.quickOpen.skip',
	'task.quickOpen.showAll',
	'task.allowAutomaticTasks.on',
	'task.allowAutomaticTasks.off',
	'task.allowAutomaticTasks',
	'task.reconnection',
	'task.saveBeforeRun',
	'task.saveBeforeRun.always',
	'task.saveBeforeRun.never',
	'task.SaveBeforeRun.prompt'
]);