/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Building...',
	"Running Tasks",
	"{0} running tasks",
	"Show Running Tasks",
	"&&Run Task...",
	"Run &&Build Task...",
	"Show Runnin&&g Tasks...",
	"R&&estart Running Task...",
	"&&Terminate Task...",
	"&&Configure Tasks...",
	"Configure De&&fault Build Task...",
	"Open Workspace Tasks",
	"Show Task Log",
	"Run Task",
	"Rerun Last Task",
	"Restart Running Task",
	"Show Running Tasks",
	"Terminate Task",
	"Run Build Task",
	"Run Test Task",
	"Configure Default Build Task",
	"Configure Default Test Task",
	"Open User Tasks",
	"User Tasks",
	"Type the name of a task to run.",
	"Run Task",
	"Tasks",
	"Configures whether to show the problem matcher prompt when running a task. Set to `true` to never prompt, or use a dictionary of task types to turn off prompting only for specific task types.",
	'Sets problem matcher prompting behavior for all tasks.',
	'An object containing task type-boolean pairs to never prompt for problem matchers on.',
	"Controls enablement of `provideTasks` for all task provider extension. If the Tasks: Run Task command is slow, disabling auto detect for task providers may help. Individual extensions may also provide settings that disable auto detection.",
	"Configures whether a warning is shown when a provider is slow",
	'Sets the slow provider warning for all tasks.',
	'An array of task types to never show the slow provider warning.',
	"Controls the number of recent items tracked in task quick open dialog.",
	"Controls whether to show the task detail for tasks that have a detail in task quick picks, such as Run Task.",
	"Controls whether the task quick pick is skipped when there is only one task to pick from.",
	"Causes the Tasks: Run Task command to use the slower \"show all\" behavior instead of the faster two level picker where tasks are grouped by provider.",
	"Always",
	"Never",
	"Enable automatic tasks - note that tasks won't run in an untrusted workspace.",
	"On window reload, reconnect to tasks that have problem matchers.",
	'Save all dirty editors before running a task.',
	'Always saves all editors before running.',
	'Never saves editors before running.',
	'Prompts whether to save editors before running.'
]);