/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'warningIcon',
	'unicodeHighlighting.thisDocumentHasManyNonBasicAsciiUnicodeCharacters',
	'unicodeHighlighting.thisDocumentHasManyAmbiguousUnicodeCharacters',
	'unicodeHighlighting.thisDocumentHasManyInvisibleUnicodeCharacters',
	'unicodeHighlight.characterIsAmbiguousASCII',
	'unicodeHighlight.characterIsAmbiguous',
	'unicodeHighlight.characterIsInvisible',
	'unicodeHighlight.characterIsNonBasicAscii',
	'unicodeHighlight.adjustSettings',
	'unicodeHighlight.disableHighlightingInComments.shortLabel',
	'action.unicodeHighlight.disableHighlightingInComments',
	'unicodeHighlight.disableHighlightingInStrings.shortLabel',
	'action.unicodeHighlight.disableHighlightingInStrings',
	'unicodeHighlight.disableHighlightingOfAmbiguousCharacters.shortLabel',
	'action.unicodeHighlight.disableHighlightingOfAmbiguousCharacters',
	'unicodeHighlight.disableHighlightingOfInvisibleCharacters.shortLabel',
	'action.unicodeHighlight.disableHighlightingOfInvisibleCharacters',
	'unicodeHighlight.disableHighlightingOfNonBasicAsciiCharacters.shortLabel',
	'action.unicodeHighlight.disableHighlightingOfNonBasicAsciiCharacters',
	'action.unicodeHighlight.showExcludeOptions',
	'unicodeHighlight.excludeInvisibleCharFromBeingHighlighted',
	'unicodeHighlight.excludeCharFromBeingHighlighted',
	"unicodeHighlight.allowCommonCharactersInLanguage",
	'unicodeHighlight.configureUnicodeHighlightOptions'
]);