/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Contributes debug adapters.',
	"Unique identifier for this debug adapter.",
	"Display name for this debug adapter.",
	"Path to the debug adapter program. Path is either absolute or relative to the extension folder.",
	"Optional arguments to pass to the adapter.",
	"Optional runtime in case the program attribute is not an executable but requires a runtime.",
	"Optional runtime arguments.",
	"Mapping from interactive variables (e.g. ${action.pickProcess}) in `launch.json` to a command.",
	"Configurations for generating the initial \'launch.json\'.",
	"List of languages for which the debug extension could be considered the \"default debugger\".",
	"Snippets for adding new configurations in \'launch.json\'.",
	"JSON schema configurations for validating \'launch.json\'.",
	"Condition which must be true to enable this type of debugger. Consider using 'shellExecutionSupported', 'virtualWorkspace', 'resourceScheme' or an extension-defined context key as appropriate for this.",
	"When this condition is true, this debugger type is hidden from the debugger list, but is still enabled.",
	"Optional message to mark this debug type as being deprecated.",
	"Windows specific settings.",
	"Runtime used for Windows.",
	"macOS specific settings.",
	"Runtime used for macOS.",
	"Linux specific settings.",
	"Runtime used for Linux.",
	"UI strings contributed by this debug adapter.",
	"When there are unverified breakpoints in a language supported by this debug adapter, this message will appear on the breakpoint hover and in the breakpoints view. Markdown and command links are supported.",
	'Contributes breakpoints.',
	"Allow breakpoints for this language.",
	"Condition which must be true to enable breakpoints in this language. Consider matching this to the debugger when clause as appropriate.",
	"Presentation options on how to show this configuration in the debug configuration dropdown and the command palette.",
	"Controls if this configuration should be shown in the configuration dropdown and the command palette.",
	"Group that this configuration belongs to. Used for grouping and sorting in the configuration dropdown and the command palette.",
	"Order of this configuration within a group. Used for grouping and sorting in the configuration dropdown and the command palette.",
	"Launch",
	"Version of this file format.",
	"List of configurations. Add new configurations or edit existing ones by using IntelliSense.",
	"List of compounds. Each compound references multiple configurations which will get launched together.",
	"Name of compound. Appears in the launch configuration drop down menu.",
	"Please use unique configuration names.",
	"Name of compound. Appears in the launch configuration drop down menu.",
	"Name of folder in which the compound is located.",
	"Names of configurations that will be started as part of this compound.",
	"Controls whether manually terminating one session will stop all of the compound sessions.",
	"Task to run before any of the compound configurations start."
]);