/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'run',
	'unstash',
	'cat',
	'accept',
	'rerun',
	'rerunShort',
	'stop',
	'arrowUp',
	'arrowDown',
	'focus',
	'previousFromHistory',
	'nextFromHistory',
	'discardMenu',
	'discard',
	'undo.clipboard',
	'undo.newfile',
	'feedback.helpful',
	'feedback.unhelpful',
	'showDiff',
	{ key: 'miShowDiff', comment: ['&& denotes a mnemonic'] },
	'showDiff2',
	{ key: 'miShowDiff2', comment: ['&& denotes a mnemonic'] },
	'apply1',
	'apply2',
	'cancel',
	'copyRecordings',
	'label',
	'viewInChat',
	'expandMessage',
	'contractMessage'
]);