/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Start Code Chat',
	'Resume Last Dismissed Code Chat',
	'Inline Chat',
	'Make Request',
	'Regenerate Response',
	'Regenerate',
	'Stop Request',
	'Cursor Up',
	'Cursor Down',
	'Focus Input',
	'Previous From History',
	'Next From History',
	"Discard...",
	'Discard',
	'Discard to Clipboard',
	'Discard to New File',
	'Helpful',
	'Unhelpful',
	'Show Diff',
	"&&Show Diff",
	"Show Diff",
	"&&Show Diff",
	'Accept Changes',
	'Accept',
	'Cancel',
	'(Developer) Write Exchange to Clipboard',
	"'{0}' and {1} follow ups ({2})",
	'View in Chat',
	'Show More',
	'Show Less'
]);