/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Peek",
	'Definitions',
	"No definition found for '{0}'",
	"No definition found",
	"Go to Definition",
	"Go to &&Definition",
	"Open Definition to the Side",
	"Peek Definition",
	'Declarations',
	"No declaration found for '{0}'",
	"No declaration found",
	"Go to Declaration",
	"Go to &&Declaration",
	"No declaration found for '{0}'",
	"No declaration found",
	"Peek Declaration",
	'Type Definitions',
	"No type definition found for '{0}'",
	"No type definition found",
	"Go to Type Definition",
	"Go to &&Type Definition",
	"Peek Type Definition",
	'Implementations',
	"No implementation found for '{0}'",
	"No implementation found",
	"Go to Implementations",
	"Go to &&Implementations",
	"Peek Implementations",
	"No references found for '{0}'",
	"No references found",
	"Go to References",
	"Go to &&References",
	'References',
	"Peek References",
	'References',
	"Go to Any Symbol",
	'Locations',
	"No results for '{0}'",
	'References'
]);