/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'peek.submenu',
	'def.title',
	'noResultWord',
	'generic.noResults',
	'actions.goToDecl.label',
	{ key: 'miGotoDefinition', comment: ['&& denotes a mnemonic'] },
	'actions.goToDeclToSide.label',
	'actions.previewDecl.label',
	'decl.title',
	'decl.noResultWord',
	'decl.generic.noResults',
	'actions.goToDeclaration.label',
	{ key: 'miGotoDeclaration', comment: ['&& denotes a mnemonic'] },
	'decl.noResultWord',
	'decl.generic.noResults',
	'actions.peekDecl.label',
	'typedef.title',
	'goToTypeDefinition.noResultWord',
	'goToTypeDefinition.generic.noResults',
	'actions.goToTypeDefinition.label',
	{ key: 'miGotoTypeDefinition', comment: ['&& denotes a mnemonic'] },
	'actions.peekTypeDefinition.label',
	'impl.title',
	'goToImplementation.noResultWord',
	'goToImplementation.generic.noResults',
	'actions.goToImplementation.label',
	{ key: 'miGotoImplementation', comment: ['&& denotes a mnemonic'] },
	'actions.peekImplementation.label',
	'references.no',
	'references.noGeneric',
	'goToReferences.label',
	{ key: 'miGotoReference', comment: ['&& denotes a mnemonic'] },
	'ref.title',
	'references.action.label',
	'ref.title',
	'label.generic',
	'generic.title',
	'generic.noResult',
	'ref.title'
]);