/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"the terminal's current working directory",
	"the terminal's current working directory, displayed for multi-root workspaces or in a single root workspace when the value differs from the initial working directory. On Windows, this will only be displayed when shell integration is enabled.",
	"the workspace in which the terminal was launched",
	"indicates a local terminal in a remote workspace",
	"the name of the terminal process",
	"a conditional separator {0} that only shows when surrounded by variables with values or static text.",
	"the name provided to the terminal by the process",
	"indicates this terminal is associated with a task",
	"Controls the terminal title. Variables are substituted based on the context:",
	"Controls the terminal description, which appears to the right of the title. Variables are substituted based on the context:",
	"Integrated Terminal",
	"Dispatches most keybindings to the terminal instead of the workbench, overriding {0}, which can be used alternatively for fine tuning.",
	"A theme color ID to associate with terminal icons by default.",
	"A codicon ID to associate with terminal icons by default.",
	'Controls whether terminal tabs display as a list to the side of the terminal. When this is disabled a dropdown will display instead.',
	'Controls whether terminal tab statuses support animation (eg. in progress tasks).',
	'Controls whether the terminal tabs view will hide under certain conditions.',
	"Never hide the terminal tabs view",
	"Hide the terminal tabs view when there is only a single terminal opened",
	"Hide the terminal tabs view when there is only a single terminal group opened",
	'Shows the active terminal information in the view. This is particularly useful when the title within the tabs aren\'t visible.',
	"Always show the active terminal",
	"Show the active terminal when it is the only terminal opened",
	"Show the active terminal when it is the only terminal opened or when the tabs view is in its narrow textless state",
	"Never show the active terminal",
	'Controls whether terminal split and kill buttons are displays next to the new terminal button.',
	"Always show the actions",
	"Show the actions when it is the only terminal opened",
	"Show the actions when it is the only terminal opened or when the tabs view is in its narrow textless state",
	"Never show the actions",
	"Show the terminal tabs view to the left of the terminal",
	"Show the terminal tabs view to the right of the terminal",
	"Controls the location of the terminal tabs, either to the left or right of the actual terminal(s).",
	"Create terminals in the editor",
	"Create terminals in the terminal view",
	"Controls where newly created terminals will appear.",
	"Focus the terminal when clicking a terminal tab",
	"Focus the terminal when double-clicking a terminal tab",
	"Controls whether focusing the terminal of a tab happens on double or single click.",
	"Controls whether to treat the option key as the meta key in the terminal on macOS.",
	"Controls whether to force selection when using Option+click on macOS. This will force a regular (line) selection and disallow the use of column selection mode. This enables copying and pasting using the regular terminal selection, for example, when mouse mode is enabled in tmux.",
	"If enabled, alt/option + click will reposition the prompt cursor to underneath the mouse when {0} is set to {1} (the default value). This may not work reliably depending on your shell.",
	"Controls whether text selected in the terminal will be copied to the clipboard.",
	"Show a warning dialog when pasting multiple lines into the terminal. The dialog does not show when:\n\n- Bracketed paste mode is enabled (the shell supports multi-line paste natively)\n- The paste is handled by the shell's readline (in the case of pwsh)",
	"Controls whether bold text in the terminal will always use the \"bright\" ANSI color variant.",
	"Controls the font family of the terminal. Defaults to {0}'s value.",
	"Controls the font size in pixels of the terminal.",
	"Controls the letter spacing of the terminal. This is an integer value which represents the number of additional pixels to add between characters.",
	"Controls the line height of the terminal. This number is multiplied by the terminal font size to get the actual line-height in pixels.",
	"When set, the foreground color of each cell will change to try meet the contrast ratio specified. Note that this will not apply to `powerline` characters per #146406. Example values:\n\n- 1: Do nothing and use the standard theme colors.\n- 4.5: [WCAG AA compliance (minimum)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) (default).\n- 7: [WCAG AAA compliance (enhanced)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast7.html).\n- 21: White on black or black on white.",
	"The number of cells in a tab stop.",
	"Scrolling speed multiplier when pressing `Alt`.",
	"A multiplier to be used on the `deltaY` of mouse wheel scroll events.",
	"The number of milliseconds to show the bell within a terminal tab when triggered.",
	"Only \"normal\" and \"bold\" keywords or numbers between 1 and 1000 are allowed.",
	"The font weight to use within the terminal for non-bold text. Accepts \"normal\" and \"bold\" keywords or numbers between 1 and 1000.",
	"Only \"normal\" and \"bold\" keywords or numbers between 1 and 1000 are allowed.",
	"The font weight to use within the terminal for bold text. Accepts \"normal\" and \"bold\" keywords or numbers between 1 and 1000.",
	"Controls whether the terminal cursor blinks.",
	"Controls the style of terminal cursor when the terminal is focused.",
	"Controls the style of terminal cursor when the terminal is not focused.",
	"Controls the width of the cursor when {0} is set to {1}.",
	"Controls the maximum number of lines the terminal keeps in its buffer. We pre-allocate memory based on this value in order to ensure a smooth experience. As such, as the value increases, so will the amount of memory.",
	"Controls whether to detect and set the `$LANG` environment variable to a UTF-8 compliant option since VS Code's terminal only supports UTF-8 encoded data coming from the shell.",
	"Set the `$LANG` environment variable if the existing variable does not exist or it does not end in `'.UTF-8'`.",
	"Do not set the `$LANG` environment variable.",
	"Always set the `$LANG` environment variable.",
	"Let VS Code detect which renderer will give the best experience.",
	"Enable GPU acceleration within the terminal.",
	"Disable GPU acceleration within the terminal. The terminal will render much slower when GPU acceleration is off but it should reliably work on all systems.",
	"Use the terminal's fallback canvas renderer which uses a 2d context instead of webgl which may perform better on some systems. Note that some features are limited in the canvas renderer like opaque selection.",
	"Controls whether the terminal will leverage the GPU to do its rendering.",
	"Separator used by {0} and {1}.",
	"Show the context menu.",
	"Copy when there is a selection, otherwise paste.",
	"Paste on right click.",
	"Select the word under the cursor and show the context menu.",
	"Do nothing and pass event to terminal.",
	"Controls how terminal reacts to right click.",
	"An explicit start path where the terminal will be launched, this is used as the current working directory (cwd) for the shell process. This may be particularly useful in workspace settings if the root directory is not a convenient cwd.",
	"Controls whether to confirm when the window closes if there are active terminal sessions.",
	"Never confirm.",
	"Always confirm if there are terminals.",
	"Confirm if there are any terminals that have child processes.",
	"Controls whether to confirm killing terminals when they have child processes. When set to editor, terminals in the editor area will be marked as changed when they have child processes. Note that child process detection may not work well for shells like Git Bash which don't run their processes as child processes of the shell.",
	"Never confirm.",
	"Confirm if the terminal is in the editor.",
	"Confirm if the terminal is in the panel.",
	"Confirm if the terminal is either in the editor or panel.",
	"Controls whether the terminal bell is enabled. This shows up as a visual bell next to the terminal's name.",
	"A set of command IDs whose keybindings will not be sent to the shell but instead always be handled by VS Code. This allows keybindings that would normally be consumed by the shell to act instead the same as when the terminal is not focused, for example `Ctrl+P` to launch Quick Open.\n\n&nbsp;\n\nMany commands are skipped by default. To override a default and pass that command's keybinding to the shell instead, add the command prefixed with the `-` character. For example add `-workbench.action.quickOpen` to allow `Ctrl+P` to reach the shell.\n\n&nbsp;\n\nThe following list of default skipped commands is truncated when viewed in Settings Editor. To see the full list, {1} and search for the first command from the list below.\n\n&nbsp;\n\nDefault Skipped Commands:\n\n{0}",
	"open the default settings JSON",
	"Open Default Settings (JSON)",
	"Whether or not to allow chord keybindings in the terminal. Note that when this is true and the keystroke results in a chord it will bypass {0}, setting this to false is particularly useful when you want ctrl+k to go to your shell (not VS Code).",
	"Whether to allow menubar mnemonics (for example Alt+F) to trigger the open of the menubar. Note that this will cause all alt keystrokes to skip the shell when true. This does nothing on macOS.",
	"Object with environment variables that will be added to the VS Code process to be used by the terminal on macOS. Set to `null` to delete the environment variable.",
	"Object with environment variables that will be added to the VS Code process to be used by the terminal on Linux. Set to `null` to delete the environment variable.",
	"Object with environment variables that will be added to the VS Code process to be used by the terminal on Windows. Set to `null` to delete the environment variable.",
	"Whether to display the environment changes indicator on each terminal which explains whether extensions have made, or want to make changes to the terminal's environment.",
	"Disable the indicator.",
	"Enable the indicator.",
	"Only show the warning indicator when a terminal's environment is 'stale', not the information indicator that shows a terminal has had its environment modified by an extension.",
	"Whether to relaunch terminals automatically if extensions want to contribute to their environment and have not been interacted with yet.",
	"Controls whether to show the alert \"The terminal process terminated with exit code\" when exit code is non-zero.",
	"Controls the working directory a split terminal starts with.",
	"A new split terminal will use the workspace root as the working directory. In a multi-root workspace a choice for which root folder to use is offered.",
	"A new split terminal will use the working directory that the parent terminal started with.",
	"On macOS and Linux, a new split terminal will use the working directory of the parent terminal. On Windows, this behaves the same as initial.",
	"Whether to use ConPTY for Windows terminal process communication (requires Windows 10 build number 18309+). Winpty will be used if this is false.",
	"A string containing all characters to be considered word separators when double-clicking to select word and in the fallback 'word' link detection. Since this is used for link detection, including characters such as `:` that are used when detecting links will cause the line and column part of links like `file:10:5` to be ignored.",
	"Whether to enable file links in terminals. Links can be slow when working on a network drive in particular because each file link is verified against the file system. Changing this will take effect only in new terminals.",
	"Always off.",
	"Always on.",
	"Enable only when not in a remote workspace.",
	"Version 6 of Unicode. This is an older version which should work better on older systems.",
	"Version 11 of Unicode. This version provides better support on modern systems that use modern versions of Unicode.",
	"Controls what version of Unicode to use when evaluating the width of characters in the terminal. If you experience emoji or other wide characters not taking up the right amount of space or backspace either deleting too much or too little then you may want to try tweaking this setting.",
	"Length of network delay, in milliseconds, where local edits will be echoed on the terminal without waiting for server acknowledgement. If '0', local echo will always be on, and if '-1' it will be disabled.",
	"When local echo should be enabled. This will override {0}",
	"Always enabled",
	"Always disabled",
	"Enabled only for remote workspaces",
	"Local echo will be disabled when any of these program names are found in the terminal title.",
	"Terminal style of locally echoed text; either a font style or an RGB color.",
	"Persist terminal sessions/history for the workspace across window reloads.",
	"When the terminal process must be shut down (for example on window or application close), this determines when the previous terminal session contents/history should be restored and processes be recreated when the workspace is next opened.\n\nCaveats:\n\n- Restoring of the process current working directory depends on whether it is supported by the shell.\n- Time to persist the session during shutdown is limited, so it may be aborted when using high-latency remote connections.",
	"Revive the processes after the last window is closed on Windows/Linux or when the `workbench.action.quit` command is triggered (command palette, keybinding, menu).",
	"Revive the processes after the last window is closed on Windows/Linux or when the `workbench.action.quit` command is triggered (command palette, keybinding, menu), or when the window is closed.",
	"Never restore the terminal buffers or recreate the process.",
	"Whether to hide the terminal view on startup, avoiding creating a terminal when there are no persistent sessions.",
	"Never hide the terminal view on startup.",
	"Only hide the terminal when there are no persistent sessions restored.",
	"Always hide the terminal, even when there are persistent sessions restored.",
	"Whether to draw custom glyphs for block element and box drawing characters instead of using the font, which typically yields better rendering with continuous lines. Note that this doesn't work when {0} is disabled.",
	"A set of messages that, when encountered in the terminal, will be automatically responded to. Provided the message is specific enough, this can help automate away common responses.\n\nRemarks:\n\n- Use {0} to automatically respond to the terminate batch job prompt on Windows.\n- The message includes escape sequences so the reply might not happen with styled text.\n- Each reply can only happen once every second.\n- Use {1} in the reply to mean the enter key.\n- To unset a default key, set the value to null.\n- Restart VS Code if new don't apply.",
	"The reply to send to the process.",
	"Determines whether or not shell integration is auto-injected to support features like enhanced command tracking and current working directory detection. \n\nShell integration works by injecting the shell with a startup script. The script gives VS Code insight into what is happening within the terminal.\n\nSupported shells:\n\n- Linux/macOS: bash, fish, pwsh, zsh\n - Windows: pwsh\n\nThis setting applies only when terminals are created, so you will need to restart your terminals for it to take effect.\n\n Note that the script injection may not work if you have custom arguments defined in the terminal profile, have enabled {1}, have a [complex bash `PROMPT_COMMAND`](https://code.visualstudio.com/docs/editor/integrated-terminal#_complex-bash-promptcommand), or other unsupported setup. To disable decorations, see {0}",
	"When shell integration is enabled, adds a decoration for each command.",
	"Show decorations in the gutter (left) and overview ruler (right)",
	"Show gutter decorations to the left of the terminal",
	"Show overview ruler decorations to the right of the terminal",
	"Do not show decorations",
	"Controls the number of recently used commands to keep in the terminal command history. Set to 0 to disable terminal command history.",
	"Enables experimental terminal Intellisense suggestions for supported shells when {0} is set to {1}. If shell integration is installed manually, {2} needs to be set to {3} before calling the script.",
	"Controls whether the terminal will scroll using an animation.",
	"Controls whether the terminal will ignore bracketed paste mode even if the terminal was put into the mode, omitting the {0} and {1} sequences when pasting. This is useful when the shell is not respecting the mode which can happen in sub-shells for example.",
	"Enables image support in the terminal, this will only work when {0} is enabled. Both sixel and iTerm's inline image protocol are supported on Linux and macOS, Windows support will light up automatically when ConPTY passes through the sequences. Images will currently not be restored between window reloads/reconnects.",
	"Controls whether the terminal, accessible buffer, or neither will be focused after `Terminal: Run Selected Text In Active Terminal` has been run.",
	"Always focus the terminal.",
	"Always focus the accessible buffer.",
	"Do nothing."
]);