/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Icon for workspace trust ion the banner.',
	'Icon for the checkmark in the workspace trust editor.',
	'Icon for the cross in the workspace trust editor.',
	'Icon for the pick folder icon in the workspace trust editor.',
	'Icon for the edit folder icon in the workspace trust editor.',
	'Icon for the remove folder icon in the workspace trust editor.',
	"Host",
	"Path",
	"{0}, trusted",
	"{0} on {1}, trusted",
	"Trusted Folders & Workspaces",
	"Add Folder",
	"Add Folder",
	"Trust Folder",
	"Select Folder To Trust",
	"You trust the following folders, their subfolders, and workspace files.",
	"You haven't trusted any folders or workspace files yet.",
	"You will trust all repositories on {0}.",
	"You will trust all repositories and forks under '{0}' on {1}.",
	"You cannot trust individual folders within a repository.",
	"Trust Folder",
	"Select Folder To Trust",
	"Edit Path",
	"Open File Picker",
	"Delete Path",
	"Local",
	"This window is trusted",
	"You trust this window",
	"You trust this folder",
	"You trust this workspace",
	"You are in Restricted Mode",
	"In a Trusted Window",
	"In Restricted Mode",
	"You trust the authors of the files in the current window. All features are enabled:",
	"You do not trust the authors of the files in the current window. The following features are disabled:",
	"In a Trusted Folder",
	"In Restricted Mode",
	"You trust the authors of the files in the current folder. All features are enabled:",
	"You do not trust the authors of the files in the current folder. The following features are disabled:",
	"In a Trusted Workspace",
	"In Restricted Mode",
	"You trust the authors of the files in the current workspace. All features are enabled:",
	"You do not trust the authors of the files in the current workspace. The following features are disabled:",
	"All features are enabled because trust has been granted to the workspace.",
	"{0} is in a restricted mode intended for safe code browsing.",
	"[Configure your settings]({0}) or [learn more](https://aka.ms/vscode-workspace-trust).",
	"Manage Workspace Trust",
	"Trusted Folders & Workspaces",
	"Tasks are allowed to run",
	"Debugging is enabled",
	"All enabled extensions are activated",
	"Tasks are allowed to run",
	"Debugging is enabled",
	"All workspace settings are applied",
	"All enabled extensions are activated",
	"Tasks are not allowed to run",
	"Debugging is disabled",
	"[{0} extensions]({1}) are disabled or have limited functionality",
	"Tasks are not allowed to run",
	"Debugging is disabled",
	"[{0} workspace settings]({1}) are not applied",
	"Workspace settings requiring trust are not applied",
	"[{0} extensions]({1}) are disabled or have limited functionality",
	"Keyboard Shortcut: {0}",
	"Trust",
	"Trust the authors of all files in the current folder or its parent '{0}'.",
	"Trust Parent",
	"Don't Trust",
	"This workspace is trusted via the bolded entries in the trusted folders below.",
	"This folder is trusted via the bolded entries in the the trusted folders below.",
	"This window is trusted by nature of the workspace that is opened."
]);