/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'shieldIcon',
	'checkListIcon',
	'xListIcon',
	'folderPickerIcon',
	'editIcon',
	'removeIcon',
	'hostColumnLabel',
	'pathColumnLabel',
	'trustedFolderAriaLabel',
	'trustedFolderWithHostAriaLabel',
	'trustedFoldersAndWorkspaces',
	'addButton',
	'addButton',
	'trustUri',
	'selectTrustedUri',
	'trustedFoldersDescription',
	'noTrustedFoldersDescriptions',
	{ key: 'trustAll', comment: ['The {0} will be a host name where repositories are hosted.'] },
	{ key: 'trustOrg', comment: ['The {0} will be an organization or user name.', 'The {1} will be a host name where repositories are hosted.'] },
	'invalidTrust',
	'trustUri',
	'selectTrustedUri',
	'editTrustedUri',
	'pickerTrustedUri',
	'deleteTrustedUri',
	'localAuthority',
	'trustedUnsettableWindow',
	'trustedHeaderWindow',
	'trustedHeaderFolder',
	'trustedHeaderWorkspace',
	'untrustedHeader',
	'trustedWindow',
	'untrustedWorkspace',
	'trustedWindowSubtitle',
	'untrustedWindowSubtitle',
	'trustedFolder',
	'untrustedWorkspace',
	'trustedFolderSubtitle',
	'untrustedFolderSubtitle',
	'trustedWorkspace',
	'untrustedWorkspace',
	'trustedWorkspaceSubtitle',
	'untrustedWorkspaceSubtitle',
	'trustedDescription',
	'untrustedDescription',
	{ key: 'workspaceTrustEditorHeaderActions', comment: ['Please ensure the markdown link syntax is not broken up with whitespace [text block](link block)'] },
	'root element label',
	'trustedFoldersAndWorkspaces',
	'trustedTasks',
	'trustedDebugging',
	'trustedExtensions',
	'trustedTasks',
	'trustedDebugging',
	'trustedSettings',
	'trustedExtensions',
	'untrustedTasks',
	'untrustedDebugging',
	{ key: 'untrustedExtensions', comment: ['Please ensure the markdown link syntax is not broken up with whitespace [text block](link block)'] },
	'untrustedTasks',
	'untrustedDebugging',
	{ key: 'untrustedSettings', comment: ['Please ensure the markdown link syntax is not broken up with whitespace [text block](link block)'] },
	'no untrustedSettings',
	{ key: 'untrustedExtensions', comment: ['Please ensure the markdown link syntax is not broken up with whitespace [text block](link block)'] },
	'keyboardShortcut',
	'trustButton',
	'trustMessage',
	'trustParentButton',
	'dontTrustButton',
	'untrustedWorkspaceReason',
	'untrustedFolderReason',
	'trustedForcedReason'
]);