/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'openLooseFileWorkspaceDetails',
	'openLooseFileWindowDetails',
	'openLooseFileLearnMore',
	'openLooseFileWorkspaceMesssage',
	'openLooseFileWindowMesssage',
	{ key: 'open', comment: ['&& denotes a mnemonic'] },
	{ key: 'newWindow', comment: ['&& denotes a mnemonic'] },
	'openLooseFileWorkspaceCheckbox',
	'workspaceTrust',
	'folderTrust',
	'immediateTrustRequestMessage',
	{ key: 'grantWorkspaceTrustButton', comment: ['&& denotes a mnemonic'] },
	{ key: 'grantFolderTrustButton', comment: ['&& denotes a mnemonic'] },
	{ key: 'manageWorkspaceTrustButton', comment: ['&& denotes a mnemonic'] },
	'cancelWorkspaceTrustButton',
	'immediateTrustRequestLearnMore',
	'addWorkspaceFolderMessage',
	'addWorkspaceFolderDetail',
	'no',
	'workspaceTrust',
	'folderTrust',
	'checkboxString',
	{ key: 'trustOption', comment: ['&& denotes a mnemonic'] },
	'trustFolderOptionDescription',
	'trustWorkspaceOptionDescription',
	{ key: 'dontTrustOption', comment: ['&& denotes a mnemonic'] },
	'dontTrustFolderOptionDescription',
	'dontTrustWorkspaceOptionDescription',
	'workspaceStartupTrustDetails',
	'folderStartupTrustDetails',
	'startupTrustRequestLearnMore',
	'restrictedModeBannerManage',
	'restrictedModeBannerLearnMore',
	'restrictedModeBannerAriaLabelWindow',
	'restrictedModeBannerAriaLabelFolder',
	'restrictedModeBannerAriaLabelWorkspace',
	'restrictedModeBannerMessageWindow',
	'restrictedModeBannerMessageFolder',
	'restrictedModeBannerMessageWorkspace',
	'status.ariaTrustedWindow',
	'status.ariaUntrustedWindow',
	{ key: 'status.tooltipUntrustedWindow2', comment: ['[abc]({n}) are links.  Only translate `features are disabled` and `window is not trusted`. Do not change brackets and parentheses or {n}'] },
	'status.ariaTrustedFolder',
	'status.ariaUntrustedFolder',
	{ key: 'status.tooltipUntrustedFolder2', comment: ['[abc]({n}) are links.  Only translate `features are disabled` and `folder is not trusted`. Do not change brackets and parentheses or {n}'] },
	'status.ariaTrustedWorkspace',
	'status.ariaUntrustedWorkspace',
	{ key: 'status.tooltipUntrustedWorkspace2', comment: ['[abc]({n}) are links. Only translate `features are disabled` and `workspace is not trusted`. Do not change brackets and parentheses or {n}'] },
	'status.WorkspaceTrust',
	'workspaceTrustEditor',
	'workspacesCategory',
	'configureWorkspaceTrustSettings',
	'manageWorkspaceTrust',
	'workspace.trust.description',
	'workspace.trust.startupPrompt.description',
	'workspace.trust.startupPrompt.always',
	'workspace.trust.startupPrompt.once',
	'workspace.trust.startupPrompt.never',
	'workspace.trust.banner.description',
	'workspace.trust.banner.always',
	'workspace.trust.banner.untilDismissed',
	'workspace.trust.banner.never',
	'workspace.trust.untrustedFiles.description',
	'workspace.trust.untrustedFiles.prompt',
	'workspace.trust.untrustedFiles.open',
	'workspace.trust.untrustedFiles.newWindow',
	'workspace.trust.emptyWindow.description'
]);