/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'A title for the current category of settings. This label will be rendered in the Settings editor as a subheading. If the title is the same as the extension display name, then the category will be grouped under the main extension heading.',
	'When specified, gives the order of this category of settings relative to other categories.',
	'Description of the configuration properties.',
	'Property should not be empty.',
	'Schema of the configuration property.',
	"Configuration that can be configured only in the user settings.",
	"Configuration that can be configured only in the user settings or only in the remote settings.",
	"Configuration that can be configured in the user, remote or workspace settings.",
	"Configuration that can be configured in the user, remote, workspace or folder settings.",
	"Resource configuration that can be configured in language specific settings.",
	"Machine configuration that can be configured also in workspace or folder settings.",
	"Scope in which the configuration is applicable. Available scopes are `application`, `machine`, `window`, `resource`, and `machine-overridable`.",
	'Descriptions for enum values',
	'Descriptions for enum values in the markdown format.',
	'Labels for enum values to be displayed in the Settings editor. When specified, the {0} values still show after the labels, but less prominently.',
	'The description in the markdown format.',
	'If set, the property is marked as deprecated and the given message is shown as an explanation.',
	'If set, the property is marked as deprecated and the given message is shown as an explanation in the markdown format.',
	'The value will be shown in an inputbox.',
	'The value will be shown in a textarea.',
	'When specified, controls the presentation format of the string setting.',
	'When specified, gives the order of this setting relative to other settings within the same category. Settings with an order property will be placed before settings without this property set.',
	'When enabled, Settings Sync will not sync the user value of this configuration by default.',
	"Cannot register configuration defaults for '{0}'. Only defaults for machine-overridable, window, resource and language overridable scoped settings are supported.",
	'Contributes configuration settings.',
	"'configuration.title' must be a string",
	"'configuration.properties' must be an object",
	"Cannot register '{0}'. This property is already registered.",
	"configuration.properties property '{0}' must be an object",
	"'configuration.allOf' is deprecated and should no longer be used. Instead, pass multiple configuration sections as an array to the 'configuration' contribution point.",
	"List of folders to be loaded in the workspace.",
	"A file path. e.g. `/root/folderA` or `./folderA` for a relative path that will be resolved against the location of the workspace file.",
	"An optional name for the folder. ",
	"URI of the folder",
	"An optional name for the folder. ",
	"Workspace settings",
	"Workspace launch configurations",
	"Workspace task configurations",
	"Workspace extensions",
	"The remote server where the workspace is located.",
	"A transient workspace will disappear when restarting or reloading.",
	"Unknown workspace configuration property"
]);