/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Overall foreground color. This color is only used if not overridden by a component.",
	"Overall foreground for disabled elements. This color is only used if not overridden by a component.",
	"Overall foreground color for error messages. This color is only used if not overridden by a component.",
	"Foreground color for description text providing additional information, for example for a label.",
	"The default color for icons in the workbench.",
	"Overall border color for focused elements. This color is only used if not overridden by a component.",
	"An extra border around elements to separate them from others for greater contrast.",
	"An extra border around active elements to separate them from others for greater contrast.",
	"The background color of text selections in the workbench (e.g. for input fields or text areas). Note that this does not apply to selections within the editor.",
	"Color for text separators.",
	"Foreground color for links in text.",
	"Foreground color for links in text when clicked on and on mouse hover.",
	"Foreground color for preformatted text segments.",
	"Background color for block quotes in text.",
	"Border color for block quotes in text.",
	"Background color for code blocks in text.",
	'Shadow color of widgets such as find/replace inside the editor.',
	'Border color of widgets such as find/replace inside the editor.',
	"Input box background.",
	"Input box foreground.",
	"Input box border.",
	"Border color of activated options in input fields.",
	"Background color of activated options in input fields.",
	"Background hover color of options in input fields.",
	"Foreground color of activated options in input fields.",
	"Input box foreground color for placeholder text.",
	"Input validation background color for information severity.",
	"Input validation foreground color for information severity.",
	"Input validation border color for information severity.",
	"Input validation background color for warning severity.",
	"Input validation foreground color for warning severity.",
	"Input validation border color for warning severity.",
	"Input validation background color for error severity.",
	"Input validation foreground color for error severity.",
	"Input validation border color for error severity.",
	"Dropdown background.",
	"Dropdown list background.",
	"Dropdown foreground.",
	"Dropdown border.",
	"Button foreground color.",
	"Button separator color.",
	"Button background color.",
	"Button background color when hovering.",
	"Button border color.",
	"Secondary button foreground color.",
	"Secondary button background color.",
	"Secondary button background color when hovering.",
	"Badge background color. Badges are small information labels, e.g. for search results count.",
	"Badge foreground color. Badges are small information labels, e.g. for search results count.",
	"Scrollbar shadow to indicate that the view is scrolled.",
	"Scrollbar slider background color.",
	"Scrollbar slider background color when hovering.",
	"Scrollbar slider background color when clicked on.",
	"Background color of the progress bar that can show for long running operations.",
	'Background color of error text in the editor. The color must not be opaque so as not to hide underlying decorations.',
	'Foreground color of error squigglies in the editor.',
	'If set, color of double underlines for errors in the editor.',
	'Background color of warning text in the editor. The color must not be opaque so as not to hide underlying decorations.',
	'Foreground color of warning squigglies in the editor.',
	'If set, color of double underlines for warnings in the editor.',
	'Background color of info text in the editor. The color must not be opaque so as not to hide underlying decorations.',
	'Foreground color of info squigglies in the editor.',
	'If set, color of double underlines for infos in the editor.',
	'Foreground color of hint squigglies in the editor.',
	'If set, color of double underlines for hints in the editor.',
	"Border color of active sashes.",
	"Editor background color.",
	"Editor default foreground color.",
	"Sticky scroll background color for the editor",
	"Sticky scroll on hover background color for the editor",
	'Background color of editor widgets, such as find/replace.',
	'Foreground color of editor widgets, such as find/replace.',
	'Border color of editor widgets. The color is only used if the widget chooses to have a border and if the color is not overridden by a widget.',
	"Border color of the resize bar of editor widgets. The color is only used if the widget chooses to have a resize border and if the color is not overridden by a widget.",
	"Quick picker background color. The quick picker widget is the container for pickers like the command palette.",
	"Quick picker foreground color. The quick picker widget is the container for pickers like the command palette.",
	"Quick picker title background color. The quick picker widget is the container for pickers like the command palette.",
	"Quick picker color for grouping labels.",
	"Quick picker color for grouping borders.",
	"Keybinding label background color. The keybinding label is used to represent a keyboard shortcut.",
	"Keybinding label foreground color. The keybinding label is used to represent a keyboard shortcut.",
	"Keybinding label border color. The keybinding label is used to represent a keyboard shortcut.",
	"Keybinding label border bottom color. The keybinding label is used to represent a keyboard shortcut.",
	"Color of the editor selection.",
	"Color of the selected text for high contrast.",
	"Color of the selection in an inactive editor. The color must not be opaque so as not to hide underlying decorations.",
	'Color for regions with the same content as the selection. The color must not be opaque so as not to hide underlying decorations.',
	"Border color for regions with the same content as the selection.",
	"Color of the current search match.",
	"Color of the other search matches. The color must not be opaque so as not to hide underlying decorations.",
	"Color of the range limiting the search. The color must not be opaque so as not to hide underlying decorations.",
	"Border color of the current search match.",
	"Border color of the other search matches.",
	"Border color of the range limiting the search. The color must not be opaque so as not to hide underlying decorations.",
	"Color of the Search Editor query matches.",
	"Border color of the Search Editor query matches.",
	"Color of the text in the search viewlet's completion message.",
	'Highlight below the word for which a hover is shown. The color must not be opaque so as not to hide underlying decorations.',
	'Background color of the editor hover.',
	'Foreground color of the editor hover.',
	'Border color of the editor hover.',
	"Background color of the editor hover status bar.",
	'Color of active links.',
	'Foreground color of inline hints',
	'Background color of inline hints',
	'Foreground color of inline hints for types',
	'Background color of inline hints for types',
	'Foreground color of inline hints for parameters',
	'Background color of inline hints for parameters',
	"The color used for the lightbulb actions icon.",
	"The color used for the lightbulb auto fix actions icon.",
	'Background color for text that got inserted. The color must not be opaque so as not to hide underlying decorations.',
	'Background color for text that got removed. The color must not be opaque so as not to hide underlying decorations.',
	'Background color for lines that got inserted. The color must not be opaque so as not to hide underlying decorations.',
	'Background color for lines that got removed. The color must not be opaque so as not to hide underlying decorations.',
	'Background color for the margin where lines got inserted.',
	'Background color for the margin where lines got removed.',
	'Diff overview ruler foreground for inserted content.',
	'Diff overview ruler foreground for removed content.',
	'Outline color for the text that got inserted.',
	'Outline color for text that got removed.',
	'Border color between the two text editors.',
	"Color of the diff editor's diagonal fill. The diagonal fill is used in side-by-side diff views.",
	"The background color of unchanged blocks in the diff editor.",
	"The foreground color of unchanged blocks in the diff editor.",
	"The background color of unchanged code in the diff editor.",
	"List/Tree background color for the focused item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree foreground color for the focused item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree outline color for the focused item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree outline color for the focused item when the list/tree is active and selected. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree background color for the selected item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree foreground color for the selected item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree icon foreground color for the selected item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree background color for the selected item when the list/tree is inactive. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree foreground color for the selected item when the list/tree is inactive. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree icon foreground color for the selected item when the list/tree is inactive. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree background color for the focused item when the list/tree is inactive. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree outline color for the focused item when the list/tree is inactive. An active list/tree has keyboard focus, an inactive does not.",
	"List/Tree background when hovering over items using the mouse.",
	"List/Tree foreground when hovering over items using the mouse.",
	"List/Tree drag and drop background when moving items around using the mouse.",
	'List/Tree foreground color of the match highlights when searching inside the list/tree.',
	'List/Tree foreground color of the match highlights on actively focused items when searching inside the list/tree.',
	'List/Tree foreground color for invalid items, for example an unresolved root in explorer.',
	'Foreground color of list items containing errors.',
	'Foreground color of list items containing warnings.',
	'Background color of the type filter widget in lists and trees.',
	'Outline color of the type filter widget in lists and trees.',
	'Outline color of the type filter widget in lists and trees, when there are no matches.',
	'Shadow color of the type filter widget in lists and trees.',
	'Background color of the filtered match.',
	'Border color of the filtered match.',
	"Tree stroke color for the indentation guides.",
	"Tree stroke color for the indentation guides that are not active.",
	"Table border color between columns.",
	"Background color for odd table rows.",
	"List/Tree foreground color for items that are deemphasized. ",
	"Background color of checkbox widget.",
	"Background color of checkbox widget when the element it's in is selected.",
	"Foreground color of checkbox widget.",
	"Border color of checkbox widget.",
	"Border color of checkbox widget when the element it's in is selected.",
	"Please use quickInputList.focusBackground instead",
	"Quick picker foreground color for the focused item.",
	"Quick picker icon foreground color for the focused item.",
	"Quick picker background color for the focused item.",
	"Border color of menus.",
	"Foreground color of menu items.",
	"Background color of menu items.",
	"Foreground color of the selected menu item in menus.",
	"Background color of the selected menu item in menus.",
	"Border color of the selected menu item in menus.",
	"Color of a separator menu item in menus.",
	"Toolbar background when hovering over actions using the mouse",
	"Toolbar outline when hovering over actions using the mouse",
	"Toolbar background when holding the mouse over actions",
	"Highlight background color of a snippet tabstop.",
	"Highlight border color of a snippet tabstop.",
	"Highlight background color of the final tabstop of a snippet.",
	"Highlight border color of the final tabstop of a snippet.",
	"Color of focused breadcrumb items.",
	"Background color of breadcrumb items.",
	"Color of focused breadcrumb items.",
	"Color of selected breadcrumb items.",
	"Background color of breadcrumb item picker.",
	'Current header background in inline merge-conflicts. The color must not be opaque so as not to hide underlying decorations.',
	'Current content background in inline merge-conflicts. The color must not be opaque so as not to hide underlying decorations.',
	'Incoming header background in inline merge-conflicts. The color must not be opaque so as not to hide underlying decorations.',
	'Incoming content background in inline merge-conflicts. The color must not be opaque so as not to hide underlying decorations.',
	'Common ancestor header background in inline merge-conflicts. The color must not be opaque so as not to hide underlying decorations.',
	'Common ancestor content background in inline merge-conflicts. The color must not be opaque so as not to hide underlying decorations.',
	'Border color on headers and the splitter in inline merge-conflicts.',
	'Current overview ruler foreground for inline merge-conflicts.',
	'Incoming overview ruler foreground for inline merge-conflicts.',
	'Common ancestor overview ruler foreground for inline merge-conflicts.',
	'Overview ruler marker color for find matches. The color must not be opaque so as not to hide underlying decorations.',
	'Overview ruler marker color for selection highlights. The color must not be opaque so as not to hide underlying decorations.',
	'Minimap marker color for find matches.',
	'Minimap marker color for repeating editor selections.',
	'Minimap marker color for the editor selection.',
	'Minimap marker color for infos.',
	'Minimap marker color for warnings.',
	'Minimap marker color for errors.',
	"Minimap background color.",
	'Opacity of foreground elements rendered in the minimap. For example, "#000000c0" will render the elements with 75% opacity.',
	"Minimap slider background color.",
	"Minimap slider background color when hovering.",
	"Minimap slider background color when clicked on.",
	"The color used for the problems error icon.",
	"The color used for the problems warning icon.",
	"The color used for the problems info icon.",
	"The foreground color used in charts.",
	"The color used for horizontal lines in charts.",
	"The red color used in chart visualizations.",
	"The blue color used in chart visualizations.",
	"The yellow color used in chart visualizations.",
	"The orange color used in chart visualizations.",
	"The green color used in chart visualizations.",
	"The purple color used in chart visualizations."
]);