/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Colors and styles for the token.',
	'Foreground color for the token.',
	'Token background colors are currently not supported.',
	'Sets the all font styles of the rule: \'italic\', \'bold\', \'underline\' or \'strikethrough\' or a combination. All styles that are not listed are unset. The empty string unsets all styles.',
	'Font style must be \'italic\', \'bold\', \'underline\' or \'strikethrough\' or a combination. The empty string unsets all styles.',
	'None (clear inherited style)',
	'Sets or unsets the font style to bold. Note, the presence of \'fontStyle\' overrides this setting.',
	'Sets or unsets the font style to italic. Note, the presence of \'fontStyle\' overrides this setting.',
	'Sets or unsets the font style to underline. Note, the presence of \'fontStyle\' overrides this setting.',
	'Sets or unsets the font style to strikethrough. Note, the presence of \'fontStyle\' overrides this setting.',
	"Style for comments.",
	"Style for strings.",
	"Style for keywords.",
	"Style for numbers.",
	"Style for expressions.",
	"Style for operators.",
	"Style for namespaces.",
	"Style for types.",
	"Style for structs.",
	"Style for classes.",
	"Style for interfaces.",
	"Style for enums.",
	"Style for type parameters.",
	"Style for functions",
	"Style for member functions",
	"Style for method (member functions)",
	"Style for macros.",
	"Style for variables.",
	"Style for parameters.",
	"Style for properties.",
	"Style for enum members.",
	"Style for events.",
	"Style for decorators & annotations.",
	"Style for labels. ",
	"Style for all symbol declarations.",
	"Style to use for references in documentation.",
	"Style to use for symbols that are static.",
	"Style to use for symbols that are abstract.",
	"Style to use for symbols that are deprecated.",
	"Style to use for write accesses.",
	"Style to use for symbols that are async.",
	"Style to use for symbols that are read-only."
]);