/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	{ key: 'miNewWindow', comment: ['&& denotes a mnemonic'] },
	{ key: 'mFile', comment: ['&& denotes a mnemonic'] },
	{ key: 'mEdit', comment: ['&& denotes a mnemonic'] },
	{ key: 'mSelection', comment: ['&& denotes a mnemonic'] },
	{ key: 'mView', comment: ['&& denotes a mnemonic'] },
	{ key: 'mGoto', comment: ['&& denotes a mnemonic'] },
	{ key: 'mRun', comment: ['&& denotes a mnemonic'] },
	{ key: 'mTerminal', comment: ['&& denotes a mnemonic'] },
	'mWindow',
	{ key: 'mHelp', comment: ['&& denotes a mnemonic'] },
	'mAbout',
	{ key: 'miPreferences', comment: ['&& denotes a mnemonic'] },
	'mServices',
	'mHide',
	'mHideOthers',
	'mShowAll',
	'miQuit',
	{ key: 'quit', comment: ['&& denotes a mnemonic'] },
	'cancel',
	'quitMessage',
	'mMinimize',
	'mZoom',
	'mBringToFront',
	{ key: 'miSwitchWindow', comment: ['&& denotes a mnemonic'] },
	'mNewTab',
	'mShowPreviousTab',
	'mShowNextTab',
	'mMoveTabToNewWindow',
	'mMergeAllWindows',
	'miCheckForUpdates',
	'miCheckingForUpdates',
	'miDownloadUpdate',
	'miDownloadingUpdate',
	'miInstallUpdate',
	'miInstallingUpdate',
	'miRestartToUpdate'
]);