/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"New &&Window",
	"&&File",
	"&&Edit",
	"&&Selection",
	"&&View",
	"&&Go",
	"&&Run",
	"&&Terminal",
	"Window",
	"&&Help",
	"About {0}",
	"&&Preferences",
	"Services",
	"Hide {0}",
	"Hide Others",
	"Show All",
	"Quit {0}",
	"&&Quit",
	"Cancel",
	"Are you sure you want to quit?",
	"Minimize",
	"Zoom",
	"Bring All to Front",
	"Switch &&Window...",
	"New Tab",
	"Show Previous Tab",
	"Show Next Tab",
	"Move Tab to New Window",
	"Merge All Windows",
	"Check for &&Updates...",
	"Checking for Updates...",
	"D&&ownload Available Update",
	"Downloading Update...",
	"Install &&Update...",
	"Installing Update...",
	"Restart to &&Update"
]);