/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'profile import error',
	'resolving uri',
	'preview profile',
	'import profile',
	'create profile',
	'save profile',
	'create new profle',
	'settings',
	'keybindings',
	'snippets',
	'tasks',
	'extensions',
	'name placeholder',
	'save',
	'create',
	'customise the profile',
	'profileExists',
	'invalid configurations',
	'use default profile',
	'name required',
	'create from',
	'empty profile',
	'from templates',
	'from existing profiles',
	'create profile',
	'export',
	'close',
	'create from profile',
	'progress extensions',
	'switching profile',
	'troubleshoot issue',
	'troubleshoot profile progress',
	'progress extensions',
	'switching profile',
	'profiles.exporting',
	'export success',
	{ key: 'copy', comment: ['&& denotes a mnemonic'] },
	{ key: 'open', comment: ['&& denotes a mnemonic'] },
	{ key: 'open in', comment: ['&& denotes a mnemonic'] },
	'close',
	'preview profile',
	'import in desktop',
	'close',
	'preview profile message',
	'learn more',
	'install extensions title',
	'create profile',
	'cancel',
	'import',
	'switching profile',
	'progress settings',
	'progress keybindings',
	'progress tasks',
	'progress snippets',
	'progress global state',
	'progress extensions',
	'select profile content handler',
	'profile already exists',
	{ key: 'overwrite', comment: ['&& denotes a mnemonic'] },
	{ key: 'create new', comment: ['&& denotes a mnemonic'] },
	'name',
	'create new title',
	'profileExists',
	'profiles.applying',
	'applied profile',
	'local',
	'file',
	'export profile dialog',
	'select profile',
	'select',
	'select',
	'from default',
	'export profile name',
	'export profile title',
	'profile name required'
]);