/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Error while importing profile: {0}",
	"{0}: Resolving profile content...",
	"Preview Profile",
	"Create Profile",
	"Create Profile",
	"Edit {0} Profile...",
	"Create New Profile...",
	"Settings",
	"Keyboard Shortcuts",
	"User Snippets",
	"User Tasks",
	"Extensions",
	"Profile name",
	"Save",
	"Create",
	"Choose what to configure in your Profile:",
	"Profile with name {0} already exists.",
	"The profile should contain at least one configuration.",
	"Using Default Profile",
	"Profile name is required and must be a non-empty value.",
	"Copy from:",
	"None",
	"Profile Templates",
	"Existing Profiles",
	"Create Profile",
	"Export",
	"Close",
	"Create Profile: {0}",
	"Applying Extensions...",
	"Switching Profile...",
	"Troubleshoot Issue",
	"Setting up Troubleshoot Profile: {0}",
	"Applying Extensions...",
	"Switching Profile...",
	"{0}: Exporting...",
	"Profile '{0}' was exported successfully.",
	"&&Copy Link",
	"&&Open Link",
	"&&Open in {0}",
	"Close",
	"Preview Profile",
	"Create Profile in {0}",
	"Close",
	"By default, extensions aren't installed when previewing a profile on the web. You can still install them manually before importing the profile. ",
	"Learn more",
	"Install Extensions",
	"Create Profile",
	"Cancel",
	"Create Profile",
	"Switching Profile...",
	"Applying Settings...",
	"Applying Keyboard Shortcuts...",
	"Applying Tasks...",
	"Applying Snippets...",
	"Applying State...",
	"Applying Extensions...",
	"Export '{0}' profile as...",
	"Profile with name '{0}' already exists. Do you want to overwrite it?",
	"&&Overwrite",
	"&&Create New Profile",
	"Profile name",
	"Create New Profile",
	"Profile with name {0} already exists.",
	"{0}: Applying...",
	"{0}: Applied successfully.",
	"Local",
	"file",
	"Save Profile",
	"Select Profile",
	"Select {0}",
	"Select {0}",
	"From Default Profile",
	"Name the profile",
	"Export Profile",
	"Profile name must be provided."
]);