/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'maximizeIcon',
	'restoreIcon',
	'closeIcon',
	'togglePanelOffIcon',
	'togglePanelOnIcon',
	'togglePanelVisibility',
	'toggle panel',
	{ key: 'toggle panel mnemonic', comment: ['&& denotes a mnemonic'] },
	'focusPanel',
	'focusPanel',
	'positionPanelLeft',
	'positionPanelLeftShort',
	'positionPanelRight',
	'positionPanelRightShort',
	'positionPanelBottom',
	'positionPanelBottomShort',
	'alignPanelLeft',
	'alignPanelLeftShort',
	'alignPanelRight',
	'alignPanelRightShort',
	'alignPanelCenter',
	'alignPanelCenterShort',
	'alignPanelJustify',
	'alignPanelJustifyShort',
	'positionPanel',
	'alignPanel',
	'previousPanelView',
	'nextPanelView',
	'toggleMaximizedPanel',
	'maximizePanel',
	'minimizePanel',
	'panelMaxNotSupported',
	'closePanel',
	'closeSecondarySideBar',
	'togglePanel',
	'hidePanel',
	'movePanelToSecondarySideBar',
	'movePanelToSecondarySideBar',
	'moveSidePanelToPanel',
	'moveSidePanelToPanel'
]);