/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Icon to maximize a panel.',
	'Icon to restore a panel.',
	'Icon to close a panel.',
	'Icon to toggle the panel off when it is on.',
	'Icon to toggle the panel on when it is off.',
	"Toggle Panel Visibility",
	"Panel",
	"&&Panel",
	"Focus into Panel",
	"Focus into Panel",
	'Move Panel Left',
	"Left",
	'Move Panel Right',
	"Right",
	'Move Panel To Bottom',
	"Bottom",
	'Set Panel Alignment to Left',
	"Left",
	'Set Panel Alignment to Right',
	"Right",
	'Set Panel Alignment to Center',
	"Center",
	'Set Panel Alignment to Justify',
	"Justify",
	"Panel Position",
	"Align Panel",
	'Previous Panel View',
	'Next Panel View',
	"Toggle Maximized Panel",
	"Maximize Panel Size",
	"Restore Panel Size",
	"Maximizing the panel is only supported when it is center aligned.",
	"Close Panel",
	"Close Secondary Side Bar",
	"Toggle Panel",
	"Hide Panel",
	"Move Panel Views To Secondary Side Bar",
	"Move Panel Views To Secondary Side Bar",
	"Move Secondary Side Bar Views To Panel",
	"Move Secondary Side Bar Views To Panel"
]);