/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Remote Tunnels',
	'Turn on Remote Tunnel Access...',
	'Turn off Remote Tunnel Access...',
	'Show Remote Tunnel Service Log',
	'Configure Tunnel Name...',
	'Copy Browser URI to Clipboard',
	'Get Started with Tunnels',
	"Tunnel '{0}' is avaiable for remote access. The {1} extension can be used to connect to it.",
	"Show Extension",
	"Do not show again",
	"[Looking for remote tunnel](command:{0})",
	"[Starting remote tunnel](command:{0})",
	"Installation as a service failed, and we fell back to running the tunnel for this session. See the [error log](command:{0}) for details.",
	"Sign in to an account to enable remote access",
	"Signed In",
	"Others",
	"Sign in with {0}",
	'Remote Tunnels is currently in preview. Please report any problems using the "Help: Report Issue" command.',
	'&&Enable',
	'Select how you want to enable access',
	'Turn on for this session',
	'Run whenever {0} is open',
	'Install as a service',
	'Run whenever you\'re logged in',
	"You can now access this machine anywhere via the secure tunnel [{0}](command:{4}). To connect via a different machine, use the generated [{1}]({2}) link or use the [{6}]({7}) extension in the desktop or web. You can [configure](command:{3}) or [turn off](command:{5}) this access via the VS Code Accounts menu.",
	"Copy Browser Link to Clipboard",
	"Show Extension",
	"Unable to turn on the remote tunnel access. Check the Remote Tunnel Service log for details.",
	'Remote Tunnel Access is On',
	'Remote Tunnel Access is Connecting',
	'Do you want to turn off Remote Tunnel Access? This will also stop the service that was started externally.',
	'Do you want to turn off Remote Tunnel Access?',
	'Select a command to invoke',
	'Remote Tunnel Access enabled for {0} (launched externally)',
	'Remote Tunnel Access enabled for {0}',
	'Remote Tunnel Access not enabled',
	'Show Log',
	'Change Tunnel Name',
	"The name under which the remote tunnel access is registered. If not set, the host name is used.",
	"The name must only consist of letters, numbers, underscore and dash. It must not start with a dash.",
	"Prevent the computer from sleeping when remote tunnel access is turned on."
]);