/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Additional command options',
	'The current working directory of the executed program or script. If omitted Code\'s current workspace root is used.',
	'The environment of the executed program or shell. If omitted the parent process\' environment is used.',
	'Unrecognized problem matcher. Is the extension that contributes this problem matcher installed?',
	'Unrecognized problem matcher. Is the extension that contributes this problem matcher installed?',
	'Configures the shell to be used.',
	'The shell to be used.',
	'The shell arguments.',
	'The command to be executed. Can be an external program or a shell command.',
	'Arguments passed to the command when this task is invoked.',
	"The task's name",
	'The command to be executed. Can be an external program or a shell command.',
	'Arguments passed to the command when this task is invoked.',
	'Windows specific command configuration',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'Mac specific command configuration',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'Linux specific command configuration',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'Controls whether the task name is added as an argument to the command. If omitted the globally defined value is used.',
	'Controls whether the output of the running task is shown or not. If omitted the globally defined value is used.',
	'Controls whether the executed command is echoed to the output. Default is false.',
	'Deprecated. Use isBackground instead.',
	'Whether the executed task is kept alive and is watching the file system.',
	'Whether the executed task is kept alive and is running in the background.',
	'Whether the user is prompted when VS Code closes with a running task.',
	'Maps this task to Code\'s default build command.',
	'Maps this task to Code\'s default test command.',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'The command to be executed. Can be an external program or a shell command.',
	'Additional arguments passed to the command.',
	'Controls whether the output of the running task is shown or not. If omitted \'always\' is used.',
	'Deprecated. Use isBackground instead.',
	'Whether the executed task is kept alive and is watching the file system.',
	'Whether the executed task is kept alive and is running in the background.',
	'Whether the user is prompted when VS Code closes with a running background task.',
	'Controls whether the executed command is echoed to the output. Default is false.',
	'Controls whether the task name is added as an argument to the command. Default is false.',
	'Prefix to indicate that an argument is task.',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'The task configurations. Usually these are enrichments of task already defined in the external task runner.'
]);