/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Specifies whether the command is a shell command or an external program. Defaults to false if omitted.',
	'The property isShellCommand is deprecated. Use the type property of the task and the shell property in the options instead. See also the 1.14 release notes.',
	'Hide this task from the run task quick pick',
	'The task identifier.',
	'Another task this task depends on.',
	'The other tasks this task depends on.',
	'Either a string representing another task or an array of other tasks that this task depends on.',
	'Run all dependsOn tasks in parallel.',
	'Run all dependsOn tasks in sequence.',
	'Determines the order of the dependsOn tasks for this task. Note that this property is not recursive.',
	'An optional description of a task that shows in the Run Task quick pick as a detail.',
	'An optional icon for the task',
	'An optional codicon ID to use',
	'An optional color of the icon',
	'Configures the panel that is used to present the task\'s output and reads its input.',
	'Controls whether the executed command is echoed to the panel. Default is true.',
	'Controls whether the panel takes focus. Default is false. If set to true the panel is revealed as well.',
	'Always reveals the problems panel when this task is executed.',
	'Only reveals the problems panel if a problem is found.',
	'Never reveals the problems panel when this task is executed.',
	'Controls whether the problems panel is revealed when running this task or not. Takes precedence over option \"reveal\". Default is \"never\".',
	'Always reveals the terminal when this task is executed.',
	'Only reveals the terminal if the task exits with an error or the problem matcher finds an error.',
	'Never reveals the terminal when this task is executed.',
	'Controls whether the terminal running the task is revealed or not. May be overridden by option \"revealProblems\". Default is \"always\".',
	'Controls if the panel is shared between tasks, dedicated to this task or a new one is created on every run.',
	'Controls whether to show the `Terminal will be reused by tasks, press any key to close it` message.',
	'Controls whether the terminal is cleared before executing the task.',
	'Controls whether the task is executed in a specific terminal group using split panes.',
	'Controls whether the terminal the task runs in is closed when the task exits.',
	'The terminal property is deprecated. Use presentation instead',
	'Marks the task as a build task accessible through the \'Run Build Task\' command.',
	'Marks the task as a test task accessible through the \'Run Test Task\' command.',
	'Assigns the task to no group',
	'The task\'s execution group.',
	'Defines if this task is the default task in the group, or a glob to match the file which should trigger this task.',
	'Marks the task as the default build task.',
	'Marks the task as the default test task.',
	'Defines to which execution group this task belongs to. It supports "build" to add it to the build group and "test" to add it to the test group.',
	'Defines whether the task is run as a process or as a command inside a shell.',
	'The shell command to be executed. Array items will be joined using a space character',
	'The shell command to be executed. Array items will be joined using a space character',
	'The actual command value',
	'Escapes characters using the shell\'s escape character (e.g. ` under PowerShell and \\ under bash).',
	'Quotes the argument using the shell\'s strong quote character (e.g. \' under PowerShell and bash).',
	'Quotes the argument using the shell\'s weak quote character (e.g. " under PowerShell and bash).',
	'How the command value should be quoted.',
	'The command to be executed. Can be an external program or a shell command.',
	'The actual argument value',
	'Escapes characters using the shell\'s escape character (e.g. ` under PowerShell and \\ under bash).',
	'Quotes the argument using the shell\'s strong quote character (e.g. \' under PowerShell and bash).',
	'Quotes the argument using the shell\'s weak quote character (e.g. " under PowerShell and bash).',
	'How the argument value should be quoted.',
	'Arguments passed to the command when this task is invoked.',
	"The task's user interface label",
	'The config\'s version number.',
	'A user defined identifier to reference the task in launch.json or a dependsOn clause.',
	'User defined identifiers are deprecated. For custom task use the name as a reference and for tasks provided by extensions use their defined task identifier.',
	'Whether to reevaluate task variables on rerun.',
	'Configures when the task should be run. If set to folderOpen, then the task will be run automatically when the folder is opened.',
	'The number of instances of the task that are allowed to run simultaneously.',
	'The task\'s run related options',
	"The task's label",
	'The task\'s name',
	'The task\'s name property is deprecated. Use the label property instead.',
	'Whether the executed task is kept alive and is running in the background.',
	'Whether the user is prompted when VS Code closes with a running task.',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'The task type to customize',
	'The customize property is deprecated. See the 1.14 release notes on how to migrate to the new task customization approach',
	'The task\'s name property is deprecated. Use the label property instead.',
	'The property showOutput is deprecated. Use the reveal property inside the presentation property instead. See also the 1.14 release notes.',
	'The property echoCommand is deprecated. Use the echo property inside the presentation property instead. See also the 1.14 release notes.',
	'The property suppressTaskName is deprecated. Inline the command with its arguments into the task instead. See also the 1.14 release notes.',
	'The property isBuildCommand is deprecated. Use the group property instead. See also the 1.14 release notes.',
	'The property isTestCommand is deprecated. Use the group property instead. See also the 1.14 release notes.',
	'Defines whether the task is run as a process or as a command inside a shell.',
	'The property suppressTaskName is deprecated. Inline the command with its arguments into the task instead. See also the 1.14 release notes.',
	'The property taskSelector is deprecated. Inline the command with its arguments into the task instead. See also the 1.14 release notes.',
	'Windows specific command configuration',
	'Mac specific command configuration',
	'Linux specific command configuration'
]);