/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'The problem pattern is missing a regular expression.',
	'The loop property is only supported on the last line matcher.',
	'The problem pattern is invalid. The kind property must be provided only in the first element',
	'The problem pattern is invalid. It must have at least have a file and a message.',
	'The problem pattern is invalid. It must either have kind: "file" or have a line or location match group.',
	'Error: The string {0} is not a valid regular expression.\n',
	'The regular expression to find an error, warning or info in the output.',
	'whether the pattern matches a location (file and line) or only a file.',
	'The match group index of the filename. If omitted 1 is used.',
	'The match group index of the problem\'s location. Valid location patterns are: (line), (line,column) and (startLine,startColumn,endLine,endColumn). If omitted (line,column) is assumed.',
	'The match group index of the problem\'s line. Defaults to 2',
	'The match group index of the problem\'s line character. Defaults to 3',
	'The match group index of the problem\'s end line. Defaults to undefined',
	'The match group index of the problem\'s end line character. Defaults to undefined',
	'The match group index of the problem\'s severity. Defaults to undefined',
	'The match group index of the problem\'s code. Defaults to undefined',
	'The match group index of the message. If omitted it defaults to 4 if location is specified. Otherwise it defaults to 5.',
	'In a multi line matcher loop indicated whether this pattern is executed in a loop as long as it matches. Can only specified on a last pattern in a multi line pattern.',
	'The name of the problem pattern.',
	'The name of the problem multi line problem pattern.',
	'The actual patterns.',
	'Contributes problem patterns',
	'Invalid problem pattern. The pattern will be ignored.',
	'Invalid problem pattern. The pattern will be ignored.',
	'Error: the description can\'t be converted into a problem matcher:\n{0}\n',
	'Error: the description doesn\'t define a valid problem pattern:\n{0}\n',
	'Error: the description doesn\'t define an owner:\n{0}\n',
	'Error: the description doesn\'t define a file location:\n{0}\n',
	'Info: unknown severity {0}. Valid values are error, warning and info.\n',
	'Error: the pattern with the identifier {0} doesn\'t exist.',
	'Error: the pattern property refers to an empty identifier.',
	'Error: the pattern property {0} is not a valid pattern variable name.',
	'A problem matcher must define both a begin pattern and an end pattern for watching.',
	'Error: The string {0} is not a valid regular expression.\n',
	'The regular expression to detect the begin or end of a background task.',
	'The match group index of the filename. Can be omitted.',
	'The name of a contributed or predefined pattern',
	'A problem pattern or the name of a contributed or predefined problem pattern. Can be omitted if base is specified.',
	'The name of a base problem matcher to use.',
	'The owner of the problem inside Code. Can be omitted if base is specified. Defaults to \'external\' if omitted and base is not specified.',
	'A human-readable string describing the source of this diagnostic, e.g. \'typescript\' or \'super lint\'.',
	'The default severity for captures problems. Is used if the pattern doesn\'t define a match group for severity.',
	'Controls if a problem reported on a text document is applied only to open, closed or all documents.',
	'Defines how file names reported in a problem pattern should be interpreted. A relative fileLocation may be an array, where the second element of the array is the path of the relative file location. The search fileLocation mode, performs a deep (and, possibly, heavy) file system search within the directories specified by the include/exclude properties of the second element (or the current workspace directory if not specified).',
	'Patterns to track the begin and end of a matcher active on a background task.',
	'If set to true the background monitor is in active mode when the task starts. This is equals of issuing a line that matches the beginsPattern',
	'If matched in the output the start of a background task is signaled.',
	'If matched in the output the end of a background task is signaled.',
	'The watching property is deprecated. Use background instead.',
	'Patterns to track the begin and end of a watching matcher.',
	'If set to true the watcher is in active mode when the task starts. This is equals of issuing a line that matches the beginPattern',
	'If matched in the output the start of a watching task is signaled.',
	'If matched in the output the end of a watching task is signaled.',
	'This property is deprecated. Use the watching property instead.',
	'A regular expression signaling that a watched tasks begins executing triggered through file watching.',
	'This property is deprecated. Use the watching property instead.',
	'A regular expression signaling that a watched tasks ends executing.',
	'The name of the problem matcher used to refer to it.',
	'A human readable label of the problem matcher.',
	'Contributes problem matchers',
	'Microsoft compiler problems',
	'Less problems',
	'Gulp TSC Problems',
	'JSHint problems',
	'JSHint stylish problems',
	'ESLint compact problems',
	'ESLint stylish problems',
	'Go problems'
]);