/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'workbench.editor.titleScrollbarSizing.default',
	'workbench.editor.titleScrollbarSizing.large',
	'tabScrollbarHeight',
	'showEditorTabs',
	'wrapTabs',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'scrollToSwitchTabs' },
	'highlightModifiedTabs',
	'decorations.badges',
	'decorations.colors',
	'workbench.editor.labelFormat.default',
	'workbench.editor.labelFormat.short',
	'workbench.editor.labelFormat.medium',
	'workbench.editor.labelFormat.long',
	{
					comment: ['This is the description for a setting. Values surrounded by parenthesis are not to be translated.'],
					key: 'tabDescription'
				},
	'workbench.editor.untitled.labelFormat.content',
	'workbench.editor.untitled.labelFormat.name',
	{
					comment: ['This is the description for a setting. Values surrounded by parenthesis are not to be translated.'],
					key: 'untitledLabelFormat'
				},
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'emptyEditorHint' },
	'workbench.editor.languageDetection',
	'workbench.editor.historyBasedLanguageDetection',
	'workbench.editor.preferBasedLanguageDetection',
	'workbench.editor.showLanguageDetectionHints',
	'workbench.editor.showLanguageDetectionHints.editors',
	'workbench.editor.showLanguageDetectionHints.notebook',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'editorTabCloseButton' },
	'workbench.editor.tabSizing.fit',
	'workbench.editor.tabSizing.shrink',
	'workbench.editor.tabSizing.fixed',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'tabSizing' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.editor.tabSizingFixedMinWidth' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.editor.tabSizingFixedMaxWidth' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.editor.tabHeight' },
	'workbench.editor.pinnedTabSizing.normal',
	'workbench.editor.pinnedTabSizing.compact',
	'workbench.editor.pinnedTabSizing.shrink',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'pinnedTabSizing' },
	'workbench.editor.preventPinnedEditorClose.always',
	'workbench.editor.preventPinnedEditorClose.onlyKeyboard',
	'workbench.editor.preventPinnedEditorClose.onlyMouse',
	'workbench.editor.preventPinnedEditorClose.never',
	'workbench.editor.preventPinnedEditorClose',
	'workbench.editor.splitSizingAuto',
	'workbench.editor.splitSizingDistribute',
	'workbench.editor.splitSizingSplit',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'splitSizing' },
	'splitOnDragAndDrop',
	'focusRecentEditorAfterClose',
	'showIcons',
	'enablePreview',
	'enablePreviewFromQuickOpen',
	'enablePreviewFromCodeNavigation',
	'closeOnFileDelete',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'editorOpenPositioning' },
	'sideBySideDirection',
	'closeEmptyGroups',
	'revealIfOpen',
	'mouseBackForwardToNavigate',
	'navigationScope',
	'workbench.editor.navigationScopeDefault',
	'workbench.editor.navigationScopeEditorGroup',
	'workbench.editor.navigationScopeEditor',
	'restoreViewState',
	'sharedViewState',
	'splitInGroupLayout',
	'workbench.editor.splitInGroupLayoutVertical',
	'workbench.editor.splitInGroupLayoutHorizontal',
	'centeredLayoutAutoResize',
	'centeredLayoutDynamicWidth',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'doubleClickTabToToggleEditorGroupSizes' },
	'limitEditorsEnablement',
	'limitEditorsMaximum',
	'limitEditorsExcludeDirty',
	'perEditorGroup',
	'localHistoryEnabled',
	'localHistoryMaxFileSize',
	'localHistoryMaxFileEntries',
	'exclude',
	'mergeWindow',
	'commandHistory',
	'preserveInput',
	'suggestCommands',
	'askChatLocation',
	'askChatLocation.chatView',
	'askChatLocation.quickChat',
	'enableNaturalLanguageSearch',
	'closeOnFocusLost',
	'workbench.quickOpen.preserveInput',
	'openDefaultSettings',
	'useSplitJSON',
	'openDefaultKeybindings',
	'sideBarLocation',
	'panelDefaultLocation',
	'panelOpensMaximized',
	'workbench.panel.opensMaximized.always',
	'workbench.panel.opensMaximized.never',
	'workbench.panel.opensMaximized.preserve',
	'statusBarVisibility',
	'activityBarVisibility',
	'activityBarIconClickBehavior',
	'workbench.activityBar.iconClickBehavior.toggle',
	'workbench.activityBar.iconClickBehavior.focus',
	'viewVisibility',
	'fontAliasing',
	'workbench.fontAliasing.default',
	'workbench.fontAliasing.antialiased',
	'workbench.fontAliasing.none',
	'workbench.fontAliasing.auto',
	'settings.editor.ui',
	'settings.editor.json',
	'settings.editor.desc',
	'workbench.hover.delay',
	'workbench.reduceMotion',
	'workbench.reduceMotion.on',
	'workbench.reduceMotion.off',
	'workbench.reduceMotion.auto',
	'layoutControlEnabledWeb',
	{ key: 'layoutControlEnabled', comment: ['{0} is a placeholder for a setting identifier.'] },
	'layoutcontrol.type.menu',
	'layoutcontrol.type.toggles',
	'layoutcontrol.type.both',
	'layoutControlType',
	'tips.enabled',
	'windowTitle',
	'activeEditorShort',
	'activeEditorMedium',
	'activeEditorLong',
	'activeFolderShort',
	'activeFolderMedium',
	'activeFolderLong',
	'folderName',
	'folderPath',
	'rootName',
	'rootNameShort',
	'rootPath',
	'profileName',
	'appName',
	'remoteName',
	'dirty',
	'focusedView',
	'separator',
	'windowConfigurationTitle',
	"window.titleSeparator",
	'window.commandCenterWeb',
	{ key: 'window.commandCenter', comment: ['{0} is a placeholder for a setting identifier.'] },
	'window.menuBarVisibility.classic',
	'window.menuBarVisibility.visible',
	'window.menuBarVisibility.toggle.mac',
	'window.menuBarVisibility.toggle',
	'window.menuBarVisibility.hidden',
	'window.menuBarVisibility.compact.web',
	{ key: 'window.menuBarVisibility.compact', comment: ['{0} is a placeholder for a setting identifier.'] },
	'menuBarVisibility.mac',
	'menuBarVisibility',
	'enableMenuBarMnemonics',
	'customMenuBarAltFocus',
	'window.openFilesInNewWindow.on',
	'window.openFilesInNewWindow.off',
	'window.openFilesInNewWindow.defaultMac',
	'window.openFilesInNewWindow.default',
	'openFilesInNewWindowMac',
	'openFilesInNewWindow',
	'window.openFoldersInNewWindow.on',
	'window.openFoldersInNewWindow.off',
	'window.openFoldersInNewWindow.default',
	'openFoldersInNewWindow',
	'window.confirmBeforeClose.always.web',
	'window.confirmBeforeClose.always',
	'window.confirmBeforeClose.keyboardOnly.web',
	'window.confirmBeforeClose.keyboardOnly',
	'window.confirmBeforeClose.never.web',
	'window.confirmBeforeClose.never',
	'confirmBeforeCloseWeb',
	'confirmBeforeClose',
	'zenModeConfigurationTitle',
	'zenMode.fullScreen',
	'zenMode.centerLayout',
	'zenMode.hideTabs',
	'zenMode.hideStatusBar',
	'zenMode.hideActivityBar',
	'zenMode.hideLineNumbers',
	'zenMode.restore',
	'zenMode.silentNotifications'
]);