/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"hide",
	"show",
	"Create on GitHub",
	"Preview on GitHub",
	"Loading data...",
	"GitHub query limit exceeded. Please wait.",
	"Similar issues",
	"Open",
	"Closed",
	"Open",
	"Closed",
	"No similar issues found",
	"Bug Report",
	"Feature Request",
	"Performance Issue",
	"Select source",
	"Visual Studio Code",
	"An extension",
	"Extensions marketplace",
	"Don't know",
	"This extension handles issues outside of VS Code",
	"The '{0}' extension prefers to use an external issue reporter. To be taken to that issue reporting experience, click the button below.",
	"Open External Issue Reporter",
	"Steps to Reproduce",
	"Share the steps needed to reliably reproduce the problem. Please include actual and expected results. We support GitHub-flavored Markdown. You will be able to edit your issue and add screenshots when we preview it on GitHub.",
	"Steps to Reproduce",
	"When did this performance issue happen? Does it occur on startup or after a specific series of actions? We support GitHub-flavored Markdown. You will be able to edit your issue and add screenshots when we preview it on GitHub.",
	"Description",
	"Please describe the feature you would like to see. We support GitHub-flavored Markdown. You will be able to edit your issue and add screenshots when we preview it on GitHub.",
	"We have written the needed data into your clipboard because it was too large to send. Please paste.",
	"Select extension",
	"Extensions are disabled",
	"No current experiments."
]);