/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Inspect Context Keys",
	"Toggle Screencast Mode",
	"Log Storage Database Contents",
	"The storage database contents have been logged to the developer tools.",
	"Open developer tools from the menu and select the Console tab.",
	"Log Working Copies",
	"Remove Large Storage Database Entries...",
	"Scope: {0}, Target: {1}",
	"Global",
	"Profile",
	"Workspace",
	"Machine",
	"User",
	"Remove",
	"Select large entries to remove from storage",
	"There are no large storage entries to remove.",
	"Do you want to remove the selected storage entries from the database?",
	"{0}\n\nThis action is irreversible and may result in data loss!",
	"&&Remove",
	"Start Tracking Disposables",
	"Snapshot Tracked Disposables",
	"Stop Tracking Disposables",
	"Screencast Mode",
	"Controls the vertical offset of the screencast mode overlay from the bottom as a percentage of the workbench height.",
	"Controls the font size (in pixels) of the screencast mode keyboard.",
	"Options for customizing the keyboard overlay in screencast mode.",
	"Show raw keys.",
	"Show keyboard shortcuts.",
	"Show command names.",
	"Show command group names, when commands are also shown.",
	"Show single editor cursor move commands.",
	"Controls how long (in milliseconds) the keyboard overlay is shown in screencast mode.",
	"Controls the color in hex (#RGB, #RGBA, #RRGGBB or #RRGGBBAA) of the mouse indicator in screencast mode.",
	"Controls the size (in pixels) of the mouse indicator in screencast mode."
]);