/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'inspect context keys',
	'toggle screencast mode',
	{ key: 'logStorage', comment: ['A developer only action to log the contents of the storage for the current window.'] },
	'storageLogDialogMessage',
	'storageLogDialogDetails',
	{ key: 'logWorkingCopies', comment: ['A developer only action to log the working copies that exist.'] },
	'removeLargeStorageDatabaseEntries',
	'largeStorageItemDetail',
	'global',
	'profile',
	'workspace',
	'machine',
	'user',
	'removeLargeStorageEntriesPickerButton',
	'removeLargeStorageEntriesPickerPlaceholder',
	'removeLargeStorageEntriesPickerDescriptionNoEntries',
	'removeLargeStorageEntriesConfirmRemove',
	'removeLargeStorageEntriesConfirmRemoveDetail',
	{ key: 'removeLargeStorageEntriesButtonLabel', comment: ['&& denotes a mnemonic'] },
	'startTrackDisposables',
	'snapshotTrackedDisposables',
	'stopTrackDisposables',
	'screencastModeConfigurationTitle',
	'screencastMode.location.verticalPosition',
	'screencastMode.fontSize',
	'screencastMode.keyboardOptions.description',
	'screencastMode.keyboardOptions.showKeys',
	'screencastMode.keyboardOptions.showKeybindings',
	'screencastMode.keyboardOptions.showCommands',
	'screencastMode.keyboardOptions.showCommandGroups',
	'screencastMode.keyboardOptions.showSingleEditorCursorMoves',
	'screencastMode.keyboardOverlayTimeout',
	'screencastMode.mouseIndicatorColor',
	'screencastMode.mouseIndicatorSize'
]);