/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Represents the menu bar",
	"Represents the activity bar in the left position",
	"Represents the activity bar in the right position",
	"Represents a side bar in the left position",
	"Represents a side bar in the left position toggled off",
	"Represents side bar in the right position",
	"Represents side bar in the right position toggled off",
	"Represents the bottom panel",
	"Represents the status bar",
	"Represents the bottom panel alignment set to the left",
	"Represents the bottom panel alignment set to the right",
	"Represents the bottom panel alignment set to the center",
	"Represents the bottom panel alignment set to justified",
	"Represents full screen",
	"Represents centered layout mode",
	"Represents zen mode",
	"Close Primary Side Bar",
	"Toggle Activity Bar Visibility",
	"&&Activity Bar",
	"Toggle Centered Layout",
	"&&Centered Layout",
	"Move Primary Side Bar Right",
	"Move Primary Side Bar Left",
	"Toggle Primary Side Bar Position",
	"Move Primary Side Bar Right",
	"Move Primary Side Bar Left",
	"Toggle Primary Side Bar Position",
	'Icon represents workbench layout configuration.',
	"Configure Layout",
	"Move Primary Side Bar Right",
	"Move Primary Side Bar Right",
	"Move Primary Side Bar Left",
	"Move Primary Side Bar Left",
	"Move Secondary Side Bar Left",
	"Move Secondary Side Bar Right",
	"&&Move Primary Side Bar Right",
	"&&Move Primary Side Bar Left",
	"Toggle Editor Area Visibility",
	"Show &&Editor Area",
	"&&Appearance",
	"Toggle Primary Side Bar Visibility",
	"Primary Side Bar",
	"&&Primary Side Bar",
	"Hide Primary Side Bar",
	"Hide Primary Side Bar",
	"Toggle Primary Side Bar",
	"Toggle Primary Side Bar",
	"Toggle Status Bar Visibility",
	"S&&tatus Bar",
	"Toggle Tab Visibility",
	"Toggle Zen Mode",
	"Zen Mode",
	"Toggle Menu Bar",
	"Menu &&Bar",
	"Menu Bar",
	"Reset View Locations",
	"Move View",
	"Side Bar / {0}",
	"Panel / {0}",
	"Secondary Side Bar / {0}",
	"Select a View to Move",
	"Move Focused View",
	"There is no view currently focused.",
	"The currently focused view is not movable.",
	"Select a Destination for the View",
	"View: Move {0}",
	"New Panel Entry",
	"New Side Bar Entry",
	"New Secondary Side Bar Entry",
	"Side Bar",
	"Panel",
	"Secondary Side Bar",
	"Reset Focused View Location",
	"There is no view currently focused.",
	"Increase Current View Size",
	"Increase Editor Width",
	"Increase Editor Height",
	"Decrease Current View Size",
	"Decrease Editor Width",
	"Decrease Editor Height",
	"Select to Hide",
	"Select to Show",
	"Active",
	"Menu Bar",
	"Activity Bar",
	"Primary Side Bar",
	"Secondary Side Bar",
	"Panel",
	"Status Bar",
	"Left",
	"Right",
	"Left",
	"Right",
	"Center",
	"Justify",
	"Full Screen",
	"Zen Mode",
	"Centered Layout",
	"Customize Layout...",
	"Visibility",
	"Primary Side Bar Position",
	"Panel Alignment",
	"Modes",
	"Customize Layout",
	"Close",
	"Restore Defaults"
]);