/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'menuBarIcon',
	'activityBarLeft',
	'activityBarRight',
	'panelLeft',
	'panelLeftOff',
	'panelRight',
	'panelRightOff',
	'panelBottom',
	'statusBarIcon',
	'panelBottomLeft',
	'panelBottomRight',
	'panelBottomCenter',
	'panelBottomJustify',
	'fullScreenIcon',
	'centerLayoutIcon',
	'zenModeIcon',
	'closeSidebar',
	'toggleActivityBar',
	{ key: 'miActivityBar', comment: ['&& denotes a mnemonic'] },
	'toggleCenteredLayout',
	{ key: 'miToggleCenteredLayout', comment: ['&& denotes a mnemonic'] },
	'moveSidebarRight',
	'moveSidebarLeft',
	'toggleSidebarPosition',
	'moveSidebarRight',
	'moveSidebarLeft',
	'toggleSidebarPosition',
	'cofigureLayoutIcon',
	'configureLayout',
	'move side bar right',
	'move sidebar right',
	'move sidebar left',
	'move sidebar left',
	'move second sidebar left',
	'move second sidebar right',
	{ key: 'miMoveSidebarRight', comment: ['&& denotes a mnemonic'] },
	{ key: 'miMoveSidebarLeft', comment: ['&& denotes a mnemonic'] },
	'toggleEditor',
	{ key: 'miShowEditorArea', comment: ['&& denotes a mnemonic'] },
	{ key: 'miAppearance', comment: ['&& denotes a mnemonic'] },
	'toggleSidebar',
	'primary sidebar',
	{ key: 'primary sidebar mnemonic', comment: ['&& denotes a mnemonic'] },
	'compositePart.hideSideBarLabel',
	'compositePart.hideSideBarLabel',
	'toggleSideBar',
	'toggleSideBar',
	'toggleStatusbar',
	{ key: 'miStatusbar', comment: ['&& denotes a mnemonic'] },
	'toggleTabs',
	'toggleZenMode',
	{ key: 'miToggleZenMode', comment: ['&& denotes a mnemonic'] },
	'toggleMenuBar',
	{ key: 'miMenuBar', comment: ['&& denotes a mnemonic'] },
	'miMenuBarNoMnemonic',
	'resetViewLocations',
	'moveView',
	'sidebarContainer',
	'panelContainer',
	'secondarySideBarContainer',
	'moveFocusedView.selectView',
	'moveFocusedView',
	'moveFocusedView.error.noFocusedView',
	'moveFocusedView.error.nonMovableView',
	'moveFocusedView.selectDestination',
	{ key: 'moveFocusedView.title', comment: ['{0} indicates the title of the view the user has selected to move.'] },
	{ key: 'moveFocusedView.newContainerInPanel', comment: ['Creates a new top-level tab in the panel.'] },
	'moveFocusedView.newContainerInSidebar',
	'moveFocusedView.newContainerInSidePanel',
	'sidebar',
	'panel',
	'secondarySideBar',
	'resetFocusedViewLocation',
	'resetFocusedView.error.noFocusedView',
	'increaseViewSize',
	'increaseEditorWidth',
	'increaseEditorHeight',
	'decreaseViewSize',
	'decreaseEditorWidth',
	'decreaseEditorHeight',
	'selectToHide',
	'selectToShow',
	'active',
	'menuBar',
	'activityBar',
	'sideBar',
	'secondarySideBar',
	'panel',
	'statusBar',
	'leftSideBar',
	'rightSideBar',
	'leftPanel',
	'rightPanel',
	'centerPanel',
	'justifyPanel',
	'fullscreen',
	'zenMode',
	'centeredLayout',
	'customizeLayout',
	'toggleVisibility',
	'sideBarPosition',
	'panelAlignment',
	'layoutModes',
	'customizeLayoutQuickPickTitle',
	'close',
	'restore defaults'
]);