/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'View icon of the Source Control view.',
	"Source Control",
	"No source control providers registered.",
	"None of the registered source control providers work in Restricted Mode.",
	"Manage Workspace Trust",
	"Source Control",
	"Source &&Control",
	"Source Control Repositories",
	"Source Control Sync",
	"Source Control",
	"Show the diff decorations in all available locations.",
	"Show the diff decorations only in the editor gutter.",
	"Show the diff decorations only in the overview ruler.",
	"Show the diff decorations only in the minimap.",
	"Do not show the diff decorations.",
	"Controls diff decorations in the editor.",
	"Controls the width(px) of diff decorations in gutter (added & modified).",
	"Show the diff decorator in the gutter at all times.",
	"Show the diff decorator in the gutter only on hover.",
	"Controls the visibility of the Source Control diff decorator in the gutter.",
	"Show the inline diff Peek view on click.",
	"Do nothing.",
	"Controls the behavior of Source Control diff gutter decorations.",
	"Controls whether a pattern is used for the diff decorations in gutter.",
	"Use pattern for the diff decorations in gutter for added lines.",
	"Use pattern for the diff decorations in gutter for modified lines.",
	"Ignore leading and trailing whitespace.",
	"Do not ignore leading and trailing whitespace.",
	"Inherit from `diffEditor.ignoreTrimWhitespace`.",
	"Controls whether leading and trailing whitespace is ignored in Source Control diff gutter decorations.",
	"Controls whether inline actions are always visible in the Source Control view.",
	"Show the sum of all Source Control Provider count badges.",
	"Show the count badge of the focused Source Control Provider.",
	"Disable the Source Control count badge.",
	"Controls the count badge on the Source Control icon on the Activity Bar.",
	"Hide Source Control Provider count badges.",
	"Only show count badge for Source Control Provider when non-zero.",
	"Show Source Control Provider count badges.",
	"Controls the count badges on Source Control Provider headers. These headers only appear when there is more than one provider.",
	"Show the repository changes as a tree.",
	"Show the repository changes as a list.",
	"Controls the default Source Control repository view mode.",
	"Sort the repository changes by file name.",
	"Sort the repository changes by path.",
	"Sort the repository changes by Source Control status.",
	"Controls the default Source Control repository changes sort order when viewed as a list.",
	"Controls whether the Source Control view should automatically reveal and select files when opening them.",
	"Controls the font for the input message. Use `default` for the workbench user interface font family, `editor` for the `#editor.fontFamily#`'s value, or a custom font family.",
	"Controls the font size for the input message in pixels.",
	"Controls whether repositories should always be visible in the Source Control view.",
	"Repositories in the Source Control Repositories view are sorted by discovery time. Repositories in the Source Control view are sorted in the order that they were selected.",
	"Repositories in the Source Control Repositories and Source Control views are sorted by repository name.",
	"Repositories in the Source Control Repositories and Source Control views are sorted by repository path.",
	"Controls the sort order of the repositories in the source control repositories view.",
	"Controls how many repositories are visible in the Source Control Repositories section. Set to 0, to be able to manually resize the view.",
	"Controls whether an action button can be shown in the Source Control view.",
	"Controls whether the Source Control Sync view is shown.",
	"Source Control: Accept Input",
	"Source Control: View Next Commit",
	"Source Control: View Previous Commit",
	"Open in External Terminal",
	"Open in Integrated Terminal"
]);