/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'sourceControlViewIcon',
	'source control',
	'no open repo',
	'no open repo in an untrusted workspace',
	'manageWorkspaceTrustAction',
	'source control',
	{ key: 'miViewSCM', comment: ['&& denotes a mnemonic'] },
	'source control repositories',
	'source control sync',
	'scmConfigurationTitle',
	'scm.diffDecorations.all',
	'scm.diffDecorations.gutter',
	'scm.diffDecorations.overviewRuler',
	'scm.diffDecorations.minimap',
	'scm.diffDecorations.none',
	'diffDecorations',
	'diffGutterWidth',
	'scm.diffDecorationsGutterVisibility.always',
	'scm.diffDecorationsGutterVisibility.hover',
	'scm.diffDecorationsGutterVisibility',
	'scm.diffDecorationsGutterAction.diff',
	'scm.diffDecorationsGutterAction.none',
	'scm.diffDecorationsGutterAction',
	'diffGutterPattern',
	'diffGutterPatternAdded',
	'diffGutterPatternModifed',
	'scm.diffDecorationsIgnoreTrimWhitespace.true',
	'scm.diffDecorationsIgnoreTrimWhitespace.false',
	'scm.diffDecorationsIgnoreTrimWhitespace.inherit',
	'diffDecorationsIgnoreTrimWhitespace',
	'alwaysShowActions',
	'scm.countBadge.all',
	'scm.countBadge.focused',
	'scm.countBadge.off',
	'scm.countBadge',
	'scm.providerCountBadge.hidden',
	'scm.providerCountBadge.auto',
	'scm.providerCountBadge.visible',
	'scm.providerCountBadge',
	'scm.defaultViewMode.tree',
	'scm.defaultViewMode.list',
	'scm.defaultViewMode',
	'scm.defaultViewSortKey.name',
	'scm.defaultViewSortKey.path',
	'scm.defaultViewSortKey.status',
	'scm.defaultViewSortKey',
	'autoReveal',
	'inputFontFamily',
	'inputFontSize',
	'alwaysShowRepository',
	'scm.repositoriesSortOrder.discoveryTime',
	'scm.repositoriesSortOrder.name',
	'scm.repositoriesSortOrder.path',
	'repositoriesSortOrder',
	'providersVisible',
	'showActionButton',
	'showSyncView',
	'scm accept',
	'scm view next commit',
	'scm view previous commit',
	'open in external terminal',
	'open in integrated terminal'
]);