/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	{ key: 'remote', comment: ['Remote as in remote machine'] },
	'installed',
	'select and install local extensions',
	'install remote in local',
	'popularExtensions',
	'recommendedExtensions',
	'enabledExtensions',
	'disabledExtensions',
	'marketPlace',
	'installed',
	'recently updated',
	'enabled',
	'disabled',
	'availableUpdates',
	'builtin',
	'workspaceUnsupported',
	'workspaceRecommendedExtensions',
	'otherRecommendedExtensions',
	'builtinFeatureExtensions',
	'builtInThemesExtensions',
	'builtinProgrammingLanguageExtensions',
	'untrustedUnsupportedExtensions',
	'untrustedPartiallySupportedExtensions',
	'virtualUnsupportedExtensions',
	'virtualPartiallySupportedExtensions',
	'deprecated',
	'searchExtensions',
	'extensionFoundInSection',
	'extensionFound',
	'extensionsFoundInSection',
	'extensionsFound',
	'suggestProxyError',
	'open user settings',
	'extensionToUpdate',
	'extensionsToUpdate',
	'extensionToReload',
	'extensionsToReload',
	'malicious warning',
	'reloadNow'
]);