/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'extensionsViewIcon',
	'manageExtensionIcon',
	'clearSearchResultsIcon',
	'refreshIcon',
	'filterIcon',
	'installLocalInRemoteIcon',
	'installWorkspaceRecommendedIcon',
	'configureRecommendedIcon',
	'syncEnabledIcon',
	'syncIgnoredIcon',
	'remoteIcon',
	'installCountIcon',
	'ratingIcon',
	'verifiedPublisher',
	'preReleaseIcon',
	'sponsorIcon',
	'starFullIcon',
	'starHalfIcon',
	'starEmptyIcon',
	'errorIcon',
	'warningIcon',
	'infoIcon',
	'trustIcon',
	'activationtimeIcon'
]);