/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'VS Code for Web',
	'cannot be installed',
	{ key: 'more information', comment: ['&& denotes a mnemonic'] },
	'close',
	'signature verification failed',
	'install anyway',
	'cancel',
	'update operation',
	'install operation',
	'check logs',
	'download',
	'install vsix',
	'installVSIX',
	'install',
	'deprecated message',
	'install anyway',
	'deprecated with alternate extension message',
	{ key: 'Show alternate extension', comment: ['&& denotes a mnemonic'] },
	'deprecated with alternate settings message',
	{ key: 'configure in settings', comment: ['&& denotes a mnemonic'] },
	'install confirmation',
	'installExtensionStart',
	'installExtensionComplete',
	'install pre-release',
	'install pre-release version',
	'install',
	'install release version',
	'install',
	'installing',
	'install',
	'installing',
	'installExtensionStart',
	{ key: 'install in remote', comment: ['This is the name of the action to install an extension in remote server. Placeholder is for the name of remote server.'] },
	'install locally',
	'install browser',
	'uninstallAction',
	'Uninstalling',
	'uninstallExtensionStart',
	'uninstallExtensionComplete',
	'update',
	'update to',
	'update',
	'updateExtensionStart',
	'updateExtensionComplete',
	'ignoreUpdates',
	'ignoreExtensionUpdate',
	'migrateExtension',
	'migrate to',
	'migrate',
	'manage',
	'manage',
	'switch to pre-release version',
	'switch to pre-release version tooltip',
	'switch to release version',
	'switch to release version tooltip',
	'install another version',
	'no versions',
	'pre-release',
	'current',
	'selectVersion',
	'enableForWorkspaceAction',
	'enableForWorkspaceActionToolTip',
	'enableGloballyAction',
	'enableGloballyActionToolTip',
	'disableForWorkspaceAction',
	'disableForWorkspaceActionToolTip',
	'disableGloballyAction',
	'disableGloballyActionToolTip',
	'enableAction',
	'disableAction',
	'reloadAction',
	'reload required',
	'current',
	'workbench.extensions.action.setColorTheme',
	'select color theme',
	'workbench.extensions.action.setFileIconTheme',
	'select file icon theme',
	'workbench.extensions.action.setProductIconTheme',
	'select product icon theme',
	'workbench.extensions.action.setDisplayLanguage',
	'workbench.extensions.action.clearLanguage',
	'showRecommendedExtension',
	'installRecommendedExtension',
	'ignoreExtensionRecommendation',
	'undo',
	'search recommendations',
	'OpenExtensionsFile.failed',
	'configureWorkspaceRecommendedExtensions',
	'configureWorkspaceFolderRecommendedExtensions',
	'updated',
	'installed',
	'uninstalled',
	'enabled',
	'disabled',
	'ignored',
	'synced',
	'sync',
	'do not sync',
	'malicious tooltip',
	'deprecated with alternate extension tooltip',
	'settings',
	'deprecated with alternate settings tooltip',
	'deprecated tooltip',
	'incompatible platform',
	'learn more',
	'VS Code for Web',
	'not web tooltip',
	'learn why',
	'disabled by environment',
	'enabled by environment',
	'disabled because of virtual workspace',
	'extension limited because of virtual workspace',
	'extension disabled because of trust requirement',
	'extension limited because of trust requirement',
	'Install in remote server to enable',
	'learn more',
	'Install in local server to enable',
	'learn more',
	'Defined to run in desktop',
	'learn more',
	'Cannot be enabled',
	'learn more',
	'Install language pack also in remote server',
	'Install language pack also locally',
	'enabled remotely',
	'learn more',
	'enabled locally',
	'learn more',
	'enabled in web worker',
	'learn more',
	'extension disabled because of dependency',
	'extension enabled on remote',
	'globally enabled',
	'workspace enabled',
	'globally disabled',
	'workspace disabled',
	'reinstall',
	'selectExtensionToReinstall',
	'ReinstallAction.successReload',
	'ReinstallAction.success',
	'InstallVSIXAction.reloadNow',
	'install previous version',
	'selectExtension',
	'select extensions to install',
	'no local extensions',
	'installing extensions',
	'finished installing',
	'select and install local extensions',
	'install local extensions title',
	'select and install remote extensions',
	'install remote extensions',
	'extensionButtonBackground',
	'extensionButtonForeground',
	'extensionButtonHoverBackground',
	'extensionButtonSeparator',
	'extensionButtonProminentBackground',
	'extensionButtonProminentForeground',
	'extensionButtonProminentHoverBackground'
]);