/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'manageExtensionsQuickAccessPlaceholder',
	'manageExtensionsHelp',
	'extension',
	'extensions',
	{ key: 'miViewExtensions', comment: ['&& denotes a mnemonic'] },
	'extensionsConfigurationTitle',
	'all',
	'enabled',
	'none',
	'extensions.autoUpdate.true',
	'extensions.autoUpdate.enabled',
	'extensions.autoUpdate.false',
	'extensions.autoUpdate',
	'extensionsCheckUpdates',
	'extensionsIgnoreRecommendations',
	'extensionsShowRecommendationsOnlyOnDemand_Deprecated',
	'extensionsCloseExtensionDetailsOnViewChange',
	'handleUriConfirmedExtensions',
	'extensionsWebWorker.true',
	'extensionsWebWorker.false',
	'extensionsWebWorker.auto',
	'extensionsWebWorker',
	'extensions.supportVirtualWorkspaces',
	'extensions.affinity',
	'extensions.supportUntrustedWorkspaces',
	'extensions.supportUntrustedWorkspaces.true',
	'extensions.supportUntrustedWorkspaces.false',
	'extensions.supportUntrustedWorkspaces.limited',
	'extensions.supportUntrustedWorkspaces.supported',
	'extensions.supportUntrustedWorkspaces.version',
	'extensionsDeferredStartupFinishedActivation',
	'notFound',
	'workbench.extensions.installExtension.description',
	'workbench.extensions.installExtension.arg.decription',
	'workbench.extensions.installExtension.option.installOnlyNewlyAddedFromExtensionPackVSIX',
	'workbench.extensions.installExtension.option.installPreReleaseVersion',
	'workbench.extensions.installExtension.option.donotSync',
	'workbench.extensions.installExtension.option.context',
	'notFound',
	'workbench.extensions.uninstallExtension.description',
	'workbench.extensions.uninstallExtension.arg.name',
	'id required',
	'notInstalled',
	'builtin',
	'workbench.extensions.search.description',
	'workbench.extensions.search.arg.name',
	'installExtensionQuickAccessPlaceholder',
	'installExtensionQuickAccessHelp',
	{ key: 'miPreferencesExtensions', comment: ['&& denotes a mnemonic'] },
	'showExtensions',
	'focusExtensions',
	'installExtensions',
	'showRecommendedKeymapExtensionsShort',
	'importKeyboardShortcutsFroms',
	'showLanguageExtensionsShort',
	'checkForUpdates',
	'noUpdatesAvailable',
	'configure auto updating extensions',
	'configureExtensionsAutoUpdate.all',
	'configureExtensionsAutoUpdate.enabled',
	'configureExtensionsAutoUpdate.none',
	'updateAll',
	'disableAutoUpdate',
	'enableAutoUpdate',
	'enableAll',
	'enableAllWorkspace',
	'disableAll',
	'disableAllWorkspace',
	'InstallFromVSIX',
	'installFromVSIX',
	{ key: 'installButton', comment: ['&& denotes a mnemonic'] },
	'installVSIX',
	'InstallVSIXAction.successReload',
	'InstallVSIXAction.success',
	'InstallVSIXAction.reloadNow',
	'installExtensionFromLocation',
	'installFromLocation',
	'install button',
	'installFromLocationPlaceHolder',
	'installFromLocation',
	'filterExtensions',
	'showFeaturedExtensions',
	'featured filter',
	'showPopularExtensions',
	'most popular filter',
	'showRecommendedExtensions',
	'most popular recommended',
	'recentlyPublishedExtensions',
	'recently published filter',
	'filter by category',
	'showBuiltInExtensions',
	'builtin filter',
	'extensionUpdates',
	'extension updates filter',
	'showWorkspaceUnsupportedExtensions',
	'workspace unsupported filter',
	'showEnabledExtensions',
	'enabled filter',
	'showDisabledExtensions',
	'disabled filter',
	'sorty by',
	'sort by installs',
	'sort by rating',
	'sort by name',
	'sort by published date',
	'sort by update date',
	'clearExtensionsSearchResults',
	'refreshExtension',
	'installWorkspaceRecommendedExtensions',
	'show pre-release version',
	'show released version',
	'workbench.extensions.action.copyExtension',
	'extensionInfoName',
	'extensionInfoId',
	'extensionInfoDescription',
	'extensionInfoVersion',
	'extensionInfoPublisher',
	'extensionInfoVSMarketplaceLink',
	'workbench.extensions.action.copyExtensionId',
	'workbench.extensions.action.configure',
	'workbench.extensions.action.configureKeybindings',
	'workbench.extensions.action.toggleApplyToAllProfiles',
	'workbench.extensions.action.toggleIgnoreExtension',
	'workbench.extensions.action.ignoreRecommendation',
	'workbench.extensions.action.undoIgnoredRecommendation',
	'workbench.extensions.action.addExtensionToWorkspaceRecommendations',
	'workbench.extensions.action.removeExtensionFromWorkspaceRecommendations',
	'workbench.extensions.action.addToWorkspaceRecommendations',
	'extensions',
	'workbench.extensions.action.addToWorkspaceFolderRecommendations',
	'extensions',
	'workbench.extensions.action.addToWorkspaceIgnoredRecommendations',
	'extensions',
	'workbench.extensions.action.addToWorkspaceFolderIgnoredRecommendations',
	'extensions',
	'extensions'
]);