/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"{0} for the Web",
	"The '{0}' extension is not available in {1}. Click 'More Information' to learn more.",
	"&&More Information",
	"Close",
	"{0} cannot verify the '{1}' extension. Are you sure you want to install it?",
	"Install Anyway",
	"Cancel",
	"Error while updating '{0}' extension.",
	"Error while installing '{0}' extension.",
	"Please check the [log]({0}) for more details.",
	"Try Downloading Manually...",
	'Once downloaded, please manually install the downloaded VSIX of \'{0}\'.',
	"Install from VSIX...",
	"Install",
	"This extension is deprecated as it is no longer being maintained.",
	"Install Anyway",
	"This extension is deprecated. Use the {0} extension instead.",
	"&&Open {0}",
	"This extension is deprecated as this functionality is now built-in to VS Code.",
	"&&Configure Settings",
	"Are you sure you want to install '{0}'?",
	"Installing extension {0} started. An editor is now open with more details on this extension",
	"Installing extension {0} is completed.",
	"Install Pre-Release",
	"Install Pre-Release Version",
	"Install",
	"Install Release Version",
	"Install",
	"Installing",
	"Install",
	"Installing",
	"Installing extension {0} started. An editor is now open with more details on this extension",
	"Install in {0}",
	"Install Locally",
	"Install in Browser",
	"Uninstall",
	"Uninstalling",
	"Uninstalling extension {0} started.",
	"Please reload Visual Studio Code to complete the uninstallation of the extension {0}.",
	"Update",
	"Update to v{0}",
	"Update",
	"Updating extension {0} to version {1} started.",
	"Updating extension {0} to version {1} completed.",
	"Ignore Updates",
	"Ignoring {0} updates",
	"Migrate",
	"Migrate to {0}",
	"Migrate",
	"Manage",
	"Manage",
	"Switch to Pre-Release Version",
	"Switch to Pre-Release version of this extension",
	"Switch to Release Version",
	"Switch to Release version of this extension",
	"Install Another Version...",
	"This extension has no other versions.",
	"pre-release",
	"current",
	"Select Version to Install",
	"Enable (Workspace)",
	"Enable this extension only in this workspace",
	"Enable",
	"Enable this extension",
	"Disable (Workspace)",
	"Disable this extension only in this workspace",
	"Disable",
	"Disable this extension",
	"Enable",
	"Disable",
	"Reload",
	'Reload Required',
	"current",
	"Set Color Theme",
	"Select Color Theme",
	"Set File Icon Theme",
	"Select File Icon Theme",
	"Set Product Icon Theme",
	"Select Product Icon Theme",
	"Set Display Language",
	"Clear Display Language",
	"Show Recommended Extension",
	"Install Recommended Extension",
	"Do not recommend this extension again",
	"Undo",
	"Search Extensions",
	"Unable to create 'extensions.json' file inside the '.vscode' folder ({0}).",
	"Configure Recommended Extensions (Workspace)",
	"Configure Recommended Extensions (Workspace Folder)",
	"Updated",
	"Installed",
	"Uninstalled",
	"Enabled",
	"Disabled",
	"This extension is ignored during sync",
	"This extension is synced",
	"Sync this extension",
	"Do not sync this extension",
	"This extension was reported to be problematic.",
	"This extension is deprecated. Use the {0} extension instead.",
	"settings",
	"This extension is deprecated as this functionality is now built-in to VS Code. Configure these {0} to use this functionality.",
	"This extension is deprecated as it is no longer being maintained.",
	"The '{0}' extension is not available in {1} for {2}.",
	"Learn More",
	"{0} for the Web",
	"The '{0}' extension is not available in {1}.",
	"Learn Why",
	"This extension is disabled by the environment.",
	"This extension is enabled because it is required in the current environment.",
	"This extension has been disabled because it does not support virtual workspaces.",
	"This extension has limited features because the current workspace is virtual.",
	"This extension has been disabled because the current workspace is not trusted.",
	"This extension has limited features because the current workspace is not trusted.",
	"This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in '{0}' to enable.",
	"Learn More",
	"This extension is disabled in this workspace because it is defined to run in the Local Extension Host. Please install the extension locally to enable.",
	"Learn More",
	"This extension is disabled because it is defined to run only in {0} for the Desktop.",
	"Learn More",
	"This extension is disabled because it is not supported in {0} for the Web.",
	"Learn More",
	"Install the language pack extension on '{0}' to enable it there also.",
	"Install the language pack extension locally to enable it there also.",
	"This extension is enabled in the Remote Extension Host because it prefers to run there.",
	"Learn More",
	"This extension is enabled in the Local Extension Host because it prefers to run there.",
	"Learn More",
	"This extension is enabled in the Web Worker Extension Host because it prefers to run there.",
	"Learn More",
	"This extension has been disabled because it depends on an extension that is disabled.",
	"Extension is enabled on '{0}'",
	"This extension is enabled globally.",
	"This extension is enabled for this workspace by the user.",
	"This extension is disabled globally by the user.",
	"This extension is disabled for this workspace by the user.",
	"Reinstall Extension...",
	"Select Extension to Reinstall",
	"Please reload Visual Studio Code to complete reinstalling the extension {0}.",
	"Reinstalling the extension {0} is completed.",
	"Reload Now",
	"Install Specific Version of Extension...",
	"Select Extension",
	"Select extensions to install",
	"There are no extensions to install.",
	"Installing Extensions...",
	"Successfully installed extensions.",
	"Install Local Extensions in '{0}'...",
	"Install Local Extensions in '{0}'",
	"Install Remote Extensions Locally...",
	"Install Remote Extensions Locally",
	"Button background color for extension actions.",
	"Button foreground color for extension actions.",
	"Button background hover color for extension actions.",
	"Button separator color for extension actions",
	"Button background color for extension actions that stand out (e.g. install button).",
	"Button foreground color for extension actions that stand out (e.g. install button).",
	"Button background hover color for extension actions that stand out (e.g. install button)."
]);