/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Extension Version",
	"Pre-Release",
	"Extension name",
	"Preview",
	"Preview",
	"Built-in",
	"Publisher",
	"Install count",
	"Rating",
	"Details",
	"Extension details, rendered from the extension's 'README.md' file",
	"Feature Contributions",
	"Lists contributions to VS Code by this extension",
	"Changelog",
	"Extension update history, rendered from the extension's 'CHANGELOG.md' file",
	"Dependencies",
	"Lists extensions this extension depends on",
	"Extension Pack",
	"Lists extensions those will be installed together with this extension",
	"Runtime Status",
	"Extension runtime status",
	"No README available.",
	"Readme",
	"Extension Pack ({0})",
	"No README available.",
	"Readme",
	"Categories",
	"Marketplace",
	"Repository",
	"License",
	"Extension Resources",
	"More Info",
	"Published",
	"Last released",
	"Last updated",
	"Identifier",
	"No Changelog available.",
	"Changelog",
	"No Contributions",
	"No Contributions",
	"No Dependencies",
	"Activation Event:",
	"Startup",
	"Activation Time:",
	"Activated By:",
	"Not yet activated.",
	"Uncaught Errors ({0})",
	"Messages ({0})",
	"No status available.",
	"Settings ({0})",
	"ID",
	"Description",
	"Default",
	"Debuggers ({0})",
	"Name",
	"Type",
	"View Containers ({0})",
	"ID",
	"Title",
	"Where",
	"Views ({0})",
	"ID",
	"Name",
	"Where",
	"Localizations ({0})",
	"Language ID",
	"Language Name",
	"Language Name (Localized)",
	"Custom Editors ({0})",
	"View Type",
	"Priority",
	"Filename Pattern",
	"Code Actions ({0})",
	"Title",
	"Kind",
	"Description",
	"Languages",
	"Authentication ({0})",
	"Label",
	"ID",
	"Color Themes ({0})",
	"File Icon Themes ({0})",
	"Product Icon Themes ({0})",
	"Colors ({0})",
	"ID",
	"Description",
	"Dark Default",
	"Light Default",
	"High Contrast Default",
	"JSON Validation ({0})",
	"File Match",
	"Schema",
	"Commands ({0})",
	"ID",
	"Title",
	"Keyboard Shortcuts",
	"Menu Contexts",
	"Languages ({0})",
	"ID",
	"Name",
	"File Extensions",
	"Grammar",
	"Snippets",
	"Activation Events ({0})",
	"Notebooks ({0})",
	"ID",
	"Name",
	"Notebook Renderers ({0})",
	"Name",
	"Mimetypes",
	"Find",
	"Find Next",
	"Find Previous"
]);