/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'extension version',
	'preRelease',
	'name',
	'preview',
	'preview',
	'builtin',
	'publisher',
	'install count',
	'rating',
	'details',
	'detailstooltip',
	'contributions',
	'contributionstooltip',
	'changelog',
	'changelogtooltip',
	'dependencies',
	'dependenciestooltip',
	'extensionpack',
	'extensionpacktooltip',
	'runtimeStatus',
	'runtimeStatus description',
	'noReadme',
	'Readme title',
	'extension pack',
	'noReadme',
	'Readme title',
	'categories',
	'Marketplace',
	'repository',
	'license',
	'resources',
	'Marketplace Info',
	'published',
	'last released',
	'last updated',
	'id',
	'noChangelog',
	'Changelog title',
	'noContributions',
	'noContributions',
	'noDependencies',
	'activation reason',
	'startup',
	'activation time',
	'activatedBy',
	'not yet activated',
	'uncaught errors',
	'messages',
	'noStatus',
	'settings',
	'setting name',
	'description',
	'default',
	'debuggers',
	'debugger name',
	'debugger type',
	'viewContainers',
	'view container id',
	'view container title',
	'view container location',
	'views',
	'view id',
	'view name',
	'view location',
	'localizations',
	'localizations language id',
	'localizations language name',
	'localizations localized language name',
	'customEditors',
	'customEditors view type',
	'customEditors priority',
	'customEditors filenamePattern',
	'codeActions',
	'codeActions.title',
	'codeActions.kind',
	'codeActions.description',
	'codeActions.languages',
	'authentication',
	'authentication.label',
	'authentication.id',
	'colorThemes',
	'iconThemes',
	'productThemes',
	'colors',
	'colorId',
	'description',
	'defaultDark',
	'defaultLight',
	'defaultHC',
	'JSON Validation',
	'fileMatch',
	'schema',
	'commands',
	'command name',
	'command title',
	'keyboard shortcuts',
	'menuContexts',
	'languages',
	'language id',
	'language name',
	'file extensions',
	'grammar',
	'snippets',
	'activation events',
	'Notebooks',
	'Notebook id',
	'Notebook name',
	'NotebookRenderers',
	'Notebook renderer name',
	'Notebook mimetypes',
	'find',
	'find next',
	'find previous'
]);