/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Remote",
	"Installed",
	"Install Local Extensions in '{0}'...",
	"Install Remote Extensions Locally...",
	"Popular",
	"Recommended",
	"Enabled",
	"Disabled",
	"Marketplace",
	"Installed",
	"Recently Updated",
	"Enabled",
	"Disabled",
	"Available Updates",
	"Builtin",
	"Workspace Unsupported",
	"Workspace Recommendations",
	"Other Recommendations",
	"Features",
	"Themes",
	"Programming Languages",
	"Disabled in Restricted Mode",
	"Limited in Restricted Mode",
	"Disabled in Virtual Workspaces",
	"Limited in Virtual Workspaces",
	"Deprecated",
	"Search Extensions in Marketplace",
	"1 extension found in the {0} section.",
	"1 extension found.",
	"{0} extensions found in the {1} section.",
	"{0} extensions found.",
	"Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.",
	"Open User Settings",
	'{0} requires update',
	'{0} require update',
	'{0} requires reload',
	'{0} require reload',
	"We have uninstalled '{0}' which was reported to be problematic.",
	"Reload Now"
]);