/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'testConfigurationTitle',
	'testing.autoRun.delay',
	'testing.automaticallyOpenPeekView',
	'testing.automaticallyOpenPeekView.failureAnywhere',
	'testing.automaticallyOpenPeekView.failureInVisibleDocument',
	'testing.automaticallyOpenPeekView.never',
	'testing.showAllMessages',
	'testing.automaticallyOpenPeekViewDuringContinuousRun',
	'testing.countBadge',
	'testing.countBadge.failed',
	'testing.countBadge.off',
	'testing.countBadge.passed',
	'testing.countBadge.skipped',
	'testing.followRunningTest',
	'testing.defaultGutterClickAction',
	'testing.defaultGutterClickAction.run',
	'testing.defaultGutterClickAction.debug',
	'testing.defaultGutterClickAction.contextMenu',
	'testing.gutterEnabled',
	'testing.saveBeforeTest',
	'testing.openTesting.neverOpen',
	'testing.openTesting.openOnTestStart',
	'testing.openTesting.openOnTestFailure',
	'testing.openTesting.openExplorerOnTestStart',
	'testing.openTesting',
	'testing.alwaysRevealTestOnStateChange'
]);