/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Errors parsing {0}: {1}",
	"{0}: Invalid format, JSON object expected.",
	'The opening bracket character or string sequence.',
	'The closing bracket character or string sequence.',
	'Defines the comment symbols',
	'Defines how block comments are marked.',
	'The character sequence that starts a block comment.',
	'The character sequence that ends a block comment.',
	'The character sequence that starts a line comment.',
	'Defines the bracket symbols that increase or decrease the indentation. When bracket pair colorization is enabled and {0} is not defined, this also defines the bracket pairs that are colorized by their nesting level.',
	'Defines the bracket pairs that are colorized by their nesting level if bracket pair colorization is enabled. Any brackets included here that are not included in {0} will be automatically included in {0}.',
	'Defines the bracket pairs. When a opening bracket is entered, the closing bracket is inserted automatically.',
	'Defines a list of scopes where the auto pairs are disabled.',
	'Defines what characters must be after the cursor in order for bracket or quote autoclosing to occur when using the \'languageDefined\' autoclosing setting. This is typically the set of characters which can not start an expression.',
	'Defines the bracket pairs that can be used to surround a selected string.',
	'Defines what is considered to be a word in the programming language.',
	'The RegExp pattern used to match words.',
	'The RegExp flags used to match words.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'The language\'s indentation settings.',
	'If a line matches this pattern, then all the lines after it should be indented once (until another rule matches).',
	'The RegExp pattern for increaseIndentPattern.',
	'The RegExp flags for increaseIndentPattern.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'If a line matches this pattern, then all the lines after it should be unindented once (until another rule matches).',
	'The RegExp pattern for decreaseIndentPattern.',
	'The RegExp flags for decreaseIndentPattern.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'If a line matches this pattern, then **only the next line** after it should be indented once.',
	'The RegExp pattern for indentNextLinePattern.',
	'The RegExp flags for indentNextLinePattern.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'If a line matches this pattern, then its indentation should not be changed and it should not be evaluated against the other rules.',
	'The RegExp pattern for unIndentedLinePattern.',
	'The RegExp flags for unIndentedLinePattern.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'The language\'s folding settings.',
	'A language adheres to the off-side rule if blocks in that language are expressed by their indentation. If set, empty lines belong to the subsequent block.',
	'Language specific folding markers such as \'#region\' and \'#endregion\'. The start and end regexes will be tested against the contents of all lines and must be designed efficiently',
	'The RegExp pattern for the start marker. The regexp must start with \'^\'.',
	'The RegExp pattern for the end marker. The regexp must start with \'^\'.',
	'The language\'s rules to be evaluated when pressing Enter.',
	'The language\'s rules to be evaluated when pressing Enter.',
	'This rule will only execute if the text before the cursor matches this regular expression.',
	'The RegExp pattern for beforeText.',
	'The RegExp flags for beforeText.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'This rule will only execute if the text after the cursor matches this regular expression.',
	'The RegExp pattern for afterText.',
	'The RegExp flags for afterText.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'This rule will only execute if the text above the line matches this regular expression.',
	'The RegExp pattern for previousLineText.',
	'The RegExp flags for previousLineText.',
	'Must match the pattern `/^([gimuy]+)$/`.',
	'The action to execute.',
	"Describe what to do with the indentation",
	"Insert new line and copy the previous line's indentation.",
	"Insert new line and indent once (relative to the previous line's indentation).",
	"Insert two new lines:\n - the first one indented which will hold the cursor\n - the second one at the same indentation level",
	"Insert new line and outdent once (relative to the previous line's indentation).",
	'Describes text to be appended after the new line and after the indentation.',
	'Describes the number of characters to remove from the new line\'s indentation.'
]);