/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Copy Path",
	"Copy Relative Path",
	"Reveal in Explorer View",
	"Use your changes and overwrite file contents",
	"Discard your changes and revert to file contents",
	"Copy Path of Active File",
	"Copy Relative Path of Active File",
	"Save All in Group",
	"Save All Files",
	"Revert File",
	"Compare Active File with Saved",
	"Open to the Side",
	"Reopen Editor With...",
	"Revert File",
	"Save All",
	"Compare with Saved",
	"Compare with Selected",
	"Select for Compare",
	"Compare Selected",
	"Close",
	"Close Others",
	"Close Saved",
	"Close All",
	"Open With...",
	"Cut",
	"Delete Permanently",
	"Delete Permanently",
	"New Text File",
	"Open File...",
	"&&New Text File",
	"&&Save",
	"Save &&As...",
	"Save A&&ll",
	"A&&uto Save",
	"Re&&vert File",
	"&&Close Editor",
	"Go to &&File..."
]);