/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Uploading",
	"Overwrite {0}",
	"Overwriting {0}",
	"{0} of {1} files ({2}/s)",
	"{0} ({1} of {2}, {3}/s)",
	"Copying...",
	"&&Copy Folders",
	"&&Copy Folder",
	"&&Add Folders to Workspace",
	"&&Add Folder to Workspace",
	"Do you want to copy the folders or add the folders to the workspace?",
	"Do you want to copy '{0}' or add '{0}' as a folder to the workspace?",
	"Are you sure to want to copy folders?",
	"Are you sure to want to copy '{0}'?",
	"Some or all of the dropped files could not be accessed for import.",
	"The dropped file could not be accessed for import.",
	"Import {0}",
	"Import {0} resources",
	"Copying {0}",
	"Copying {0} resources",
	"Downloading",
	"{0} of {1} files ({2}/s)",
	"{0} ({1} of {2}, {3}/s)",
	"Download",
	"Choose Where to Download",
	"Download {0}",
	"Downloading {0}",
	"A file or folder with the name '{0}' already exists in the destination folder. Do you want to replace it?",
	"This action is irreversible!",
	"&&Replace",
	"The following {0} files and/or folders already exist in the destination folder. Do you want to replace them?",
	"This action is irreversible!",
	"&&Replace"
]);