/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Text File Editor",
	"Binary File Editor",
	'Disable hot exit. A prompt will show when attempting to close a window with editors that have unsaved changes.',
	'Hot exit will be triggered when the last window is closed on Windows/Linux or when the `workbench.action.quit` command is triggered (command palette, keybinding, menu). All windows without folders opened will be restored upon next launch. A list of previously opened windows with unsaved files can be accessed via `File > Open Recent > More...`',
	'Hot exit will be triggered when the last window is closed on Windows/Linux or when the `workbench.action.quit` command is triggered (command palette, keybinding, menu), and also for any window with a folder opened regardless of whether it\'s the last window. All windows without folders opened will be restored upon next launch. A list of previously opened windows with unsaved files can be accessed via `File > Open Recent > More...`',
	"[Hot Exit](https://aka.ms/vscode-hot-exit) controls whether unsaved files are remembered between sessions, allowing the save prompt when exiting the editor to be skipped.",
	'Disable hot exit. A prompt will show when attempting to close a window with editors that have unsaved changes.',
	'Hot exit will be triggered when the browser quits or the window or tab is closed.',
	"[Hot Exit](https://aka.ms/vscode-hot-exit) controls whether unsaved files are remembered between sessions, allowing the save prompt when exiting the editor to be skipped.",
	"Files",
	"Configure [glob patterns](https://aka.ms/vscode-glob-patterns) for excluding files and folders. For example, the File Explorer decides which files and folders to show or hide based on this setting. Refer to the `#search.exclude#` setting to define search-specific excludes. Refer to the `#explorer.excludeGitIgnore#` setting for ignoring files based on your `.gitignore`.",
	"Enable the pattern.",
	"Disable the pattern.",
	"The glob pattern to match file paths against. Set to true or false to enable or disable the pattern.",
	"Additional check on the siblings of a matching file. Use \\$(basename) as variable for the matching file name.",
	"Configure [glob patterns](https://aka.ms/vscode-glob-patterns) of file associations to languages (for example `\"*.extension\": \"html\"`). Patterns will match on the absolute path of a file if they contain a path separator and will match on the name of the file otherwise. These have precedence over the default associations of the languages installed.",
	"The default character set encoding to use when reading and writing files. This setting can also be configured per language.",
	"When enabled, the editor will attempt to guess the character set encoding when opening files. This setting can also be configured per language. Note, this setting is not respected by text search. Only {0} is respected.",
	"LF",
	"CRLF",
	"Uses operating system specific end of line character.",
	"The default end of line character.",
	"Moves files/folders to the OS trash (recycle bin on Windows) when deleting. Disabling this will delete files/folders permanently.",
	"When enabled, will trim trailing whitespace when saving a file.",
	"When enabled, insert a final new line at the end of the file when saving it.",
	"When enabled, will trim all new lines after the final new line at the end of the file when saving it.",
	"An editor with changes is never automatically saved.",
	"An editor with changes is automatically saved after the configured `#files.autoSaveDelay#`.",
	"An editor with changes is automatically saved when the editor loses focus.",
	"An editor with changes is automatically saved when the window loses focus.",
	"Controls [auto save](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) of editors that have unsaved changes.",
	"Controls the delay in milliseconds after which an editor with unsaved changes is saved automatically. Only applies when `#files.autoSave#` is set to `{0}`.",
	"Configure paths or [glob patterns](https://aka.ms/vscode-glob-patterns) to exclude from file watching. Paths can either be relative to the watched folder or absolute. Glob patterns are matched relative from the watched folder. When you experience the file watcher process consuming a lot of CPU, make sure to exclude large folders that are of less interest (such as build output folders).",
	"Configure extra paths to watch for changes inside the workspace. By default, all workspace folders will be watched recursively, except for folders that are symbolic links. You can explicitly add absolute or relative paths to support watching folders that are symbolic links. Relative paths will be resolved to an absolute path using the currently opened workspace.",
	"The default language identifier that is assigned to new files. If configured to `${activeEditorLanguage}`, will use the language identifier of the currently active text editor if any.",
	"Configure paths or [glob patterns](https://aka.ms/vscode-glob-patterns) to mark as read-only. Glob patterns are always evaluated relative to the path of the workspace folder unless they are absolute paths. You can exclude matching paths via the `#files.readonlyExclude#` setting. Files from readonly file system providers will always be read-only independent of this setting.",
	"Configure paths or [glob patterns](https://aka.ms/vscode-glob-patterns) to exclude from being marked as read-only if they match as a result of the `#files.readonlyInclude#` setting. Glob patterns are always evaluated relative to the path of the workspace folder unless they are absolute paths. Files from readonly file system providers will always be read-only independent of this setting.",
	"Marks files as read-only when their file permissions indicate as such. This can be overridden via `#files.readonlyInclude#` and `#files.readonlyExclude#` settings.",
	"Restore the undo stack when a file is reopened.",
	"Will refuse to save and ask for resolving the save conflict manually.",
	"Will resolve the save conflict by overwriting the file on disk with the changes in the editor.",
	"A save conflict can occur when a file is saved to disk that was changed by another program in the meantime. To prevent data loss, the user is asked to compare the changes in the editor with the version on disk. This setting should only be changed if you frequently encounter save conflict errors and may result in data loss if used without caution.",
	"Default path for file dialogs must be an absolute path (e.g. C:\\\\myFolder or /myFolder).",
	"Default path for file dialogs, overriding user's home path. Only used in the absence of a context-specific path, such as most recently opened file or folder.",
	"Enables the simple file dialog for opening and saving files and folders. The simple file dialog replaces the system file dialog when enabled.",
	"Timeout in milliseconds after which file participants for create, rename, and delete are cancelled. Use `0` to disable participants.",
	"Format a file on save. A formatter must be available, the file must not be saved after delay, and the editor must not be shutting down.",
	"Format the whole file.",
	"Format modifications (requires source control).",
	"Will attempt to format modifications only (requires source control). If source control can't be used, then the whole file will be formatted.",
	"Controls if format on save formats the whole file or only modifications. Only applies when `#editor.formatOnSave#` is enabled.",
	"File Explorer",
	"The initial maximum number of editors shown in the Open Editors pane. Exceeding this limit will show a scroll bar and allow resizing the pane to display more items.",
	"The minimum number of editor slots pre-allocated in the Open Editors pane. If set to 0 the Open Editors pane will dynamically resize based on the number of editors.",
	"Controls the sorting order of editors in the Open Editors pane.",
	'Editors are ordered in the same order editor tabs are shown.',
	'Editors are ordered alphabetically by tab name inside each editor group.',
	'Editors are ordered alphabetically by full path inside each editor group.',
	'Files will be revealed and selected.',
	'Files will not be revealed and selected.',
	'Files will not be scrolled into view, but will still be focused.',
	"Controls whether the Explorer should automatically reveal and select files when opening them.",
	"Configure paths or [glob patterns](https://aka.ms/vscode-glob-patterns) for excluding files and folders from being revealed and selected in the Explorer when they are opened. Glob patterns are always evaluated relative to the path of the workspace folder unless they are absolute paths.",
	"The glob pattern to match file paths against. Set to true or false to enable or disable the pattern.",
	'Additional check on the siblings of a matching file. Use $(basename) as variable for the matching file name.',
	"Controls whether the Explorer should allow to move files and folders via drag and drop. This setting only effects drag and drop from inside the Explorer.",
	"Controls whether the Explorer should ask for confirmation to move files and folders via drag and drop.",
	"Controls whether the Explorer should ask for confirmation when deleting a file via the trash.",
	"Controls whether the Explorer should support undoing file and folder operations.",
	"Controls whether the Explorer should ask for confirmation when undoing.",
	'Explorer will prompt before all undo operations.',
	'Explorer will prompt before destructive undo operations.',
	'Explorer will not prompt before undo operations when focused.',
	"Controls whether the Explorer should expand multi-root workspaces containing only one folder during initialization",
	'Files and folders are sorted by their names. Folders are displayed before files.',
	'Files and folders are sorted by their names. Files are interwoven with folders.',
	'Files and folders are sorted by their names. Files are displayed before folders.',
	'Files and folders are grouped by extension type then sorted by their names. Folders are displayed before files.',
	'Files and folders are sorted by last modified date in descending order. Folders are displayed before files.',
	'Files and folders are sorted by their names. Folders are displayed before files. Files with nested children are displayed before other files.',
	"Controls the property-based sorting of files and folders in the Explorer. When `#explorer.fileNesting.enabled#` is enabled, also controls sorting of nested files.",
	'Uppercase and lowercase names are mixed together.',
	'Uppercase names are grouped together before lowercase names.',
	'Lowercase names are grouped together before uppercase names.',
	'Names are sorted in Unicode order.',
	"Controls the lexicographic sorting of file and folder names in the Explorer.",
	"Controls whether file decorations should use colors.",
	"Controls whether file decorations should use badges.",
	"Appends the word \"copy\" at the end of the duplicated name potentially followed by a number.",
	"Adds a number at the end of the duplicated name. If some number is already part of the name, tries to increase that number.",
	"Disables incremental naming. If two files with the same name exist you will be prompted to overwrite the existing file.",
	"Controls what naming strategy to use when a giving a new name to a duplicated Explorer item on paste.",
	"Controls whether the Explorer should render folders in a compact form. In such a form, single child folders will be compressed in a combined tree element. Useful for Java package structures, for example.",
	"Use slash as path separation character.",
	"Use backslash as path separation character.",
	"Uses operating system specific path separation character.",
	"The path separation character used when copying relative file paths.",
	"Controls whether entries in .gitignore should be parsed and excluded from the Explorer. Similar to {0}.",
	"Controls whether file nesting is enabled in the Explorer. File nesting allows for related files in a directory to be visually grouped together under a single parent file.",
	"Controls whether file nests are automatically expanded. {0} must be set for this to take effect.",
	"Controls nesting of files in the Explorer. {0} must be set for this to take effect. Each __Item__ represents a parent pattern and may contain a single `*` character that matches any string. Each __Value__ represents a comma separated list of the child patterns that should be shown nested under a given parent. Child patterns may contain several special tokens:\n- `${capture}`: Matches the resolved value of the `*` from the parent pattern\n- `${basename}`: Matches the parent file's basename, the `file` in `file.ts`\n- `${extname}`: Matches the parent file's extension, the `ts` in `file.ts`\n- `${dirname}`: Matches the parent file's directory name, the `src` in `src/file.ts`\n- `*`:  Matches any string, may only be used once per child pattern",
	"Each key pattern may contain a single `*` character which will match any string."
]);