/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'textFileEditor',
	'binaryFileEditor',
	'hotExit.off',
	'hotExit.onExit',
	'hotExit.onExitAndWindowClose',
	'hotExit',
	'hotExit.off',
	'hotExit.onExitAndWindowCloseBrowser',
	'hotExit',
	'filesConfigurationTitle',
	'exclude',
	'trueDescription',
	'falseDescription',
	'files.exclude.boolean',
	{ key: 'files.exclude.when', comment: ['\\$(basename) should not be translated'] },
	'associations',
	'encoding',
	'autoGuessEncoding',
	'eol.LF',
	'eol.CRLF',
	'eol.auto',
	'eol',
	'useTrash',
	'trimTrailingWhitespace',
	'insertFinalNewline',
	'trimFinalNewlines',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.off' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.afterDelay' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.onFocusChange' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.onWindowChange' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'autoSave' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'autoSaveDelay' },
	'watcherExclude',
	'watcherInclude',
	'defaultLanguage',
	'filesReadonlyInclude',
	'filesReadonlyExclude',
	'filesReadonlyFromPermissions',
	'files.restoreUndoStack',
	'askUser',
	'overwriteFileOnDisk',
	'files.saveConflictResolution',
	'defaultPathErrorMessage',
	'fileDialogDefaultPath',
	'files.simpleDialog.enable',
	'files.participants.timeout',
	'formatOnSave',
	{ key: 'everything', comment: ['This is the description of an option'] },
	{ key: 'modification', comment: ['This is the description of an option'] },
	{ key: 'modificationIfAvailable', comment: ['This is the description of an option'] },
	'formatOnSaveMode',
	'explorerConfigurationTitle',
	{ key: 'openEditorsVisible', comment: ['Open is an adjective'] },
	{ key: 'openEditorsVisibleMin', comment: ['Open is an adjective'] },
	{ key: 'openEditorsSortOrder', comment: ['Open is an adjective'] },
	'sortOrder.editorOrder',
	'sortOrder.alphabetical',
	'sortOrder.fullPath',
	'autoReveal.on',
	'autoReveal.off',
	'autoReveal.focusNoScroll',
	'autoReveal',
	'autoRevealExclude',
	'explorer.autoRevealExclude.boolean',
	'explorer.autoRevealExclude.when',
	'enableDragAndDrop',
	'confirmDragAndDrop',
	'confirmDelete',
	'enableUndo',
	'confirmUndo',
	'enableUndo.verbose',
	'enableUndo.default',
	'enableUndo.light',
	'expandSingleFolderWorkspaces',
	'sortOrder.default',
	'sortOrder.mixed',
	'sortOrder.filesFirst',
	'sortOrder.type',
	'sortOrder.modified',
	'sortOrder.foldersNestsFiles',
	'sortOrder',
	'sortOrderLexicographicOptions.default',
	'sortOrderLexicographicOptions.upper',
	'sortOrderLexicographicOptions.lower',
	'sortOrderLexicographicOptions.unicode',
	'sortOrderLexicographicOptions',
	'explorer.decorations.colors',
	'explorer.decorations.badges',
	'simple',
	'smart',
	'disabled',
	'explorer.incrementalNaming',
	'compressSingleChildFolders',
	'copyRelativePathSeparator.slash',
	'copyRelativePathSeparator.backslash',
	'copyRelativePathSeparator.auto',
	'copyRelativePathSeparator',
	'excludeGitignore',
	'fileNestingEnabled',
	'fileNestingExpand',
	'fileNestingPatterns',
	'fileNesting.description'
]);