/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'newFile',
	'newFolder',
	'rename',
	'delete',
	'copyFile',
	'pasteFile',
	'download',
	'upload',
	'deleteButtonLabelRecycleBin',
	{ key: 'deleteButtonLabelTrash', comment: ['&& denotes a mnemonic'] },
	{ key: 'deleteButtonLabel', comment: ['&& denotes a mnemonic'] },
	'dirtyMessageFilesDelete',
	'dirtyMessageFolderOneDelete',
	'dirtyMessageFolderDelete',
	'dirtyMessageFileDelete',
	'dirtyWarning',
	'irreversible',
	'restorePlural',
	'restore',
	'undoBinFiles',
	'undoBin',
	'undoTrashFiles',
	'undoTrash',
	'doNotAskAgain',
	{ key: 'deleteBulkEdit', comment: ['Placeholder will be replaced by the number of files deleted'] },
	{ key: 'deleteFileBulkEdit', comment: ['Placeholder will be replaced by the name of the file deleted'] },
	{ key: 'deletingBulkEdit', comment: ['Placeholder will be replaced by the number of files deleted'] },
	{ key: 'deletingFileBulkEdit', comment: ['Placeholder will be replaced by the name of the file deleted'] },
	'binFailed',
	'trashFailed',
	{ key: 'deletePermanentlyButtonLabel', comment: ['&& denotes a mnemonic'] },
	{ key: 'retryButtonLabel', comment: ['&& denotes a mnemonic'] },
	'confirmMoveTrashMessageFilesAndDirectories',
	'confirmMoveTrashMessageMultipleDirectories',
	'confirmMoveTrashMessageMultiple',
	'confirmMoveTrashMessageFolder',
	'confirmMoveTrashMessageFile',
	'confirmDeleteMessageFilesAndDirectories',
	'confirmDeleteMessageMultipleDirectories',
	'confirmDeleteMessageMultiple',
	'confirmDeleteMessageFolder',
	'confirmDeleteMessageFile',
	'confirmOverwrite',
	'replaceButtonLabel',
	'globalCompareFile',
	'toggleAutoSave',
	'saveAllInGroup',
	'closeGroup',
	'focusFilesExplorer',
	'showInExplorer',
	'openFileInNewWindow',
	'openFileToShowInNewWindow.unsupportedschema',
	'emptyFileNameError',
	'fileNameStartsWithSlashError',
	'fileNameExistsError',
	'invalidFileNameError',
	'fileNameWhitespaceWarning',
	'compareNewUntitledTextFiles',
	'compareWithClipboard',
	'clipboardComparisonLabel',
	'retry',
	'createBulkEdit',
	'creatingBulkEdit',
	'renameBulkEdit',
	'renamingBulkEdit',
	'fileIsAncestor',
	{ key: 'movingBulkEdit', comment: ['Placeholder will be replaced by the number of files being moved'] },
	{ key: 'movingFileBulkEdit', comment: ['Placeholder will be replaced by the name of the file moved.'] },
	{ key: 'moveBulkEdit', comment: ['Placeholder will be replaced by the number of files being moved'] },
	{ key: 'moveFileBulkEdit', comment: ['Placeholder will be replaced by the name of the file moved.'] },
	{ key: 'copyingBulkEdit', comment: ['Placeholder will be replaced by the number of files being copied'] },
	{ key: 'copyingFileBulkEdit', comment: ['Placeholder will be replaced by the name of the file copied.'] },
	{ key: 'copyBulkEdit', comment: ['Placeholder will be replaced by the number of files being copied'] },
	{ key: 'copyFileBulkEdit', comment: ['Placeholder will be replaced by the name of the file copied.'] },
	'fileDeleted',
	'setActiveEditorReadonlyInSession',
	'setActiveEditorWriteableInSession',
	'toggleActiveEditorReadonlyInSession',
	'resetActiveEditorReadonlyInSession'
]);