/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'The foreground color for array symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for boolean symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for class symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for color symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for constant symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for constructor symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for enumerator symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for enumerator member symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for event symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for field symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for file symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for folder symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for function symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for interface symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for key symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for keyword symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for method symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for module symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for namespace symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for null symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for number symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for object symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for operator symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for package symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for property symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for reference symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for snippet symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for string symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for struct symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for text symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for type parameter symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for unit symbols. These symbols appear in the outline, breadcrumb, and suggest widget.',
	'The foreground color for variable symbols. These symbols appear in the outline, breadcrumb, and suggest widget.'
]);