/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Background color for the highlight of line at the cursor position.',
	'Background color for the border around the line at the cursor position.',
	'Background color of highlighted ranges, like by quick open and find features. The color must not be opaque so as not to hide underlying decorations.',
	'Background color of the border around highlighted ranges.',
	'Background color of highlighted symbol, like for go to definition or go next/previous symbol. The color must not be opaque so as not to hide underlying decorations.',
	'Background color of the border around highlighted symbols.',
	'Color of the editor cursor.',
	'The background color of the editor cursor. Allows customizing the color of a character overlapped by a block cursor.',
	'Color of whitespace characters in the editor.',
	'Color of editor line numbers.',
	'Color of the editor indentation guides.',
	'\'editorIndentGuide.background\' is deprecated. Use \'editorIndentGuide.background1\' instead.',
	'Color of the active editor indentation guides.',
	'\'editorIndentGuide.activeBackground\' is deprecated. Use \'editorIndentGuide.activeBackground1\' instead.',
	'Color of the editor indentation guides (1).',
	'Color of the editor indentation guides (2).',
	'Color of the editor indentation guides (3).',
	'Color of the editor indentation guides (4).',
	'Color of the editor indentation guides (5).',
	'Color of the editor indentation guides (6).',
	'Color of the active editor indentation guides (1).',
	'Color of the active editor indentation guides (2).',
	'Color of the active editor indentation guides (3).',
	'Color of the active editor indentation guides (4).',
	'Color of the active editor indentation guides (5).',
	'Color of the active editor indentation guides (6).',
	'Color of editor active line number',
	'Id is deprecated. Use \'editorLineNumber.activeForeground\' instead.',
	'Color of editor active line number',
	'Color of the final editor line when editor.renderFinalNewline is set to dimmed.',
	'Color of the editor rulers.',
	'Foreground color of editor CodeLens',
	'Background color behind matching brackets',
	'Color for matching brackets boxes',
	'Color of the overview ruler border.',
	'Background color of the editor overview ruler.',
	'Background color of the editor gutter. The gutter contains the glyph margins and the line numbers.',
	'Border color of unnecessary (unused) source code in the editor.',
	'Opacity of unnecessary (unused) source code in the editor. For example, "#000000c0" will render the code with 75% opacity. For high contrast themes, use the  \'editorUnnecessaryCode.border\' theme color to underline unnecessary code instead of fading it out.',
	'Border color of ghost text in the editor.',
	'Foreground color of the ghost text in the editor.',
	'Background color of the ghost text in the editor.',
	'Overview ruler marker color for range highlights. The color must not be opaque so as not to hide underlying decorations.',
	'Overview ruler marker color for errors.',
	'Overview ruler marker color for warnings.',
	'Overview ruler marker color for infos.',
	'Foreground color of brackets (1). Requires enabling bracket pair colorization.',
	'Foreground color of brackets (2). Requires enabling bracket pair colorization.',
	'Foreground color of brackets (3). Requires enabling bracket pair colorization.',
	'Foreground color of brackets (4). Requires enabling bracket pair colorization.',
	'Foreground color of brackets (5). Requires enabling bracket pair colorization.',
	'Foreground color of brackets (6). Requires enabling bracket pair colorization.',
	'Foreground color of unexpected brackets.',
	'Background color of inactive bracket pair guides (1). Requires enabling bracket pair guides.',
	'Background color of inactive bracket pair guides (2). Requires enabling bracket pair guides.',
	'Background color of inactive bracket pair guides (3). Requires enabling bracket pair guides.',
	'Background color of inactive bracket pair guides (4). Requires enabling bracket pair guides.',
	'Background color of inactive bracket pair guides (5). Requires enabling bracket pair guides.',
	'Background color of inactive bracket pair guides (6). Requires enabling bracket pair guides.',
	'Background color of active bracket pair guides (1). Requires enabling bracket pair guides.',
	'Background color of active bracket pair guides (2). Requires enabling bracket pair guides.',
	'Background color of active bracket pair guides (3). Requires enabling bracket pair guides.',
	'Background color of active bracket pair guides (4). Requires enabling bracket pair guides.',
	'Background color of active bracket pair guides (5). Requires enabling bracket pair guides.',
	'Background color of active bracket pair guides (6). Requires enabling bracket pair guides.',
	'Border color used to highlight unicode characters.',
	'Background color used to highlight unicode characters.'
]);