/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Icon used for the setup category of welcome page",
	"Icon used for the beginner category of welcome page",
	"Icon used for the intermediate category of welcome page",
	"New File...",
	"Open a new untitled text file, notebook, or custom editor.",
	"Open...",
	"Open a file or folder to start working",
	"Open File...",
	"Open a file to start working",
	"Open Folder...",
	"Open a folder to start working",
	"Open Folder...",
	"Open a folder to start working",
	"Clone Git Repository...",
	"Clone a remote repository to a local folder",
	"Open Repository...",
	"Connect to a remote repository or pull request to browse, search, edit, and commit",
	"Open a Walkthrough...",
	"View a walkthrough on the editor or an extension",
	"Connect to...",
	"Connect to remote development workspaces.",
	"Open Tunnel...",
	"Connect to a remote machine through a Tunnel",
	"Get Started with VS Code",
	"Discover the best customizations to make VS Code yours.",
	"Choose the look you want",
	"The right color palette helps you focus on your code, is easy on your eyes, and is simply more fun to use.\n{0}",
	"Browse Color Themes",
	"Sync to and from other devices",
	"Keep your essential VS Code customizations backed up and updated across all your devices.\n{0}",
	"Enable Settings Sync",
	"One shortcut to access everything",
	"Commands are the keyboard way to accomplish any task in VS Code. **Practice** by looking up your frequent ones to save time.\n{0}\n__Try searching for 'view toggle'.__",
	"Open Command Palette",
	"Limitless extensibility",
	"Extensions are VS Code's power-ups. A growing number are becoming available in the web.\n{0}",
	"Browse Popular Web Extensions",
	"Rich support for all your languages",
	"Code smarter with syntax highlighting, code completion, linting and debugging. While many languages are built-in, many more can be added as extensions.\n{0}",
	"Browse Language Extensions",
	"Open up your code",
	"You're all set to start coding. Open a project folder to get your files into VS Code.\n{0}",
	"Pick a Folder",
	"Open up your code",
	"You're all set to start coding. Open a project folder to get your files into VS Code.\n{0}",
	"Pick a Folder",
	"Quickly navigate between your files",
	"Navigate between files in an instant with one keystroke. Tip: Open multiple files by pressing the right arrow key.\n{0}",
	"Quick Open a File",
	"Get Started with VS Code for the Web",
	"Discover the best customizations to make VS Code for the Web yours.",
	"Choose the look you want",
	"The right color palette helps you focus on your code, is easy on your eyes, and is simply more fun to use.\n{0}",
	"Browse Color Themes",
	"Sync to and from other devices",
	"Keep your essential VS Code customizations backed up and updated across all your devices.\n{0}",
	"Enable Settings Sync",
	"One shortcut to access everything",
	"Commands are the keyboard way to accomplish any task in VS Code. **Practice** by looking up your frequent ones to save time.\n{0}\n__Try searching for 'view toggle'.__",
	"Open Command Palette",
	"Just the right amount of UI",
	"The full menu bar is available in the dropdown menu to make room for your code. Toggle its appearance for faster access. \n{0}",
	"Toggle Menu Bar",
	"Limitless extensibility",
	"Extensions are VS Code's power-ups. A growing number are becoming available in the web.\n{0}",
	"Browse Popular Web Extensions",
	"Rich support for all your languages",
	"Code smarter with syntax highlighting, code completion, linting and debugging. While many languages are built-in, many more can be added as extensions.\n{0}",
	"Browse Language Extensions",
	"Open up your code",
	"You're all set to start coding. You can open a local project or a remote repository to get your files into VS Code.\n{0}\n{1}",
	"Open Folder",
	"Open Repository",
	"Quickly navigate between your files",
	"Navigate between files in an instant with one keystroke. Tip: Open multiple files by pressing the right arrow key.\n{0}",
	"Quick Open a File",
	"Learn the Fundamentals",
	"Jump right into VS Code and get an overview of the must-have features.",
	"Redefine your editing skills",
	"Want to code faster and smarter? Practice powerful code editing features in the interactive playground.\n{0}",
	"Open Editor Playground",
	"Convenient built-in terminal",
	"Quickly run shell commands and monitor build output, right next to your code.\n{0}",
	"Show Terminal Panel",
	"Limitless extensibility",
	"Extensions are VS Code's power-ups. They range from handy productivity hacks, expanding out-of-the-box features, to adding completely new capabilities.\n{0}",
	"Browse Recommended Extensions",
	"Tune your settings",
	"Tweak every aspect of VS Code and your extensions to your liking. Commonly used settings are listed first to get you started.\n{0}",
	"Tweak my Settings",
	"Customize VS Code with Profiles",
	"Profiles let you create sets of VS Code customizations that include settings, extensions and UI state. Create your own profile from scratch or use the predefined set of profile templates for your specific workflow.\n{0}",
	"Try Profiles",
	"Safely browse and edit code",
	"{0} lets you decide whether your project folders should **allow or restrict** automatic code execution __(required for extensions, debugging, etc)__.\nOpening a file/folder will prompt to grant trust. You can always {1} later.",
	"Workspace Trust",
	"enable trust",
	"Lean back and learn",
	"Watch the first in a series of short & practical video tutorials for VS Code's key features.\n{0}",
	"Watch Tutorial",
	"Boost your Productivity",
	"Optimize your development workflow with these tips & tricks.",
	"Side by side editing",
	"Make the most of your screen estate by opening files side by side, vertically and horizontally.\n{0}",
	"Split Editor",
	"Watch your code in action",
	"Accelerate your edit, build, test, and debug loop by setting up a launch configuration.\n{0}",
	"Run your Project",
	"Track your code with Git",
	"Set up the built-in version control for your project to track your changes and collaborate with others.\n{0}",
	"Clone Repository",
	"Track your code with Git",
	"Set up the built-in version control for your project to track your changes and collaborate with others.\n{0}",
	"Initialize Git Repository",
	"Track your code with Git",
	"No more looking up Git commands! Git and GitHub workflows are seamlessly integrated.\n{0}",
	"Open Source Control",
	"Install Git",
	"Install Git to track changes in your projects.\n{0}\n{1}Reload window{2} after installation to complete Git setup.",
	"Install Git",
	"Automate your project tasks",
	"Create tasks for your common workflows and enjoy the integrated experience of running scripts and automatically checking results.\n{0}",
	"Run Auto-detected Tasks",
	"Customize your shortcuts",
	"Once you have discovered your favorite commands, create custom keyboard shortcuts for instant access.\n{0}",
	"Keyboard Shortcuts",
	"Customize Notebooks",
	"Select the layout for your notebooks",
	"Get notebooks to feel just the way you prefer"
]);