/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Hide Test',
	'Unhide Test',
	'Unhide All Tests',
	'Debug Test',
	'Execute Using Profile...',
	'Run Test',
	'Select Default Profile',
	'Turn on Continuous Run',
	'Turn off Continuous Run',
	'Start Continous Run Using...',
	'Configure Test Profiles',
	'Select a profile to update',
	"Stop Continuous Run",
	'No test continuous run-enabled profiles were found',
	'Select profiles to run when files change:',
	"Start Continuous Run",
	'Get Selected Profiles',
	'Get Explorer Selection',
	'Run Tests',
	'Debug Tests',
	'Discovering Tests',
	'Run All Tests',
	'No tests found in this workspace. You may need to install a test provider extension',
	'Debug All Tests',
	'No debuggable tests found in this workspace. You may need to install a test provider extension',
	"Cancel Test Run",
	"View as List",
	"View as Tree",
	"Sort by Status",
	"Sort by Location",
	"Sort by Duration",
	"Show Output",
	"Collapse All Tests",
	"Clear All Results",
	"Go to Test",
	"No tests found here",
	"Run Test at Cursor",
	"Debug Test at Cursor",
	"No tests found in this file",
	"Run Tests in Current File",
	"Debug Tests in Current File",
	"Rerun Failed Tests",
	"Debug Failed Tests",
	"Rerun Last Run",
	"Debug Last Run",
	"Search for Test Extension",
	"Peek Output",
	"Toggle Inline Test Output",
	"Refresh Tests",
	"Cancel Test Refresh"
]);