/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"New Window Tab",
	"Show Previous Window Tab",
	"Show Next Window Tab",
	"Move Window Tab to New Window",
	"Merge All Windows",
	"Toggle Window Tabs Bar",
	"E&&xit",
	"Controls the timeout in seconds before giving up resolving the shell environment when the application is not already launched from a terminal. See our [documentation](https://go.microsoft.com/fwlink/?linkid=2149667) for more information.",
	"Window",
	"Open a new empty window.",
	"Focus the last active running instance.",
	"Controls whether a new empty window should open when starting a second instance without arguments or if the last running instance should get focus.\nNote that there can still be cases where this setting is ignored (e.g. when using the `--new-window` or `--reuse-window` command line option).",
	"Always reopen all windows. If a folder or workspace is opened (e.g. from the command line) it opens as a new window unless it was opened before. If files are opened they will open in one of the restored windows.",
	"Reopen all windows unless a folder, workspace or file is opened (e.g. from the command line).",
	"Reopen all windows that had folders or workspaces opened unless a folder, workspace or file is opened (e.g. from the command line).",
	"Reopen the last active window unless a folder, workspace or file is opened (e.g. from the command line).",
	"Never reopen a window. Unless a folder or workspace is opened (e.g. from the command line), an empty window will appear.",
	"Controls how windows are being reopened after starting for the first time. This setting has no effect when the application is already running.",
	"Controls whether a window should restore to full screen mode if it was exited in full screen mode.",
	"Adjust the zoom level of the window. The original size is 0 and each increment above (e.g. 1) or below (e.g. -1) represents zooming 20% larger or smaller. You can also enter decimals to adjust the zoom level with a finer granularity.",
	"Open new windows in the center of the screen.",
	"Open new windows with same dimension as last active one.",
	"Open new windows with same dimension as last active one with an offset position.",
	"Open new windows maximized.",
	"Open new windows in full screen mode.",
	"Controls the dimensions of opening a new window when at least one window is already opened. Note that this setting does not have an impact on the first window that is opened. The first window will always restore the size and location as you left it before closing.",
	"Controls whether closing the last editor should also close the window. This setting only applies for windows that do not show folders.",
	"If enabled, this setting will close the window when the application icon in the title bar is double-clicked. The window will not be able to be dragged by the icon. This setting is effective only if `#window.titleBarStyle#` is set to `custom`.",
	"Adjust the appearance of the window title bar. On Linux and Windows, this setting also affects the application and context menu appearances. Changes require a full restart to apply.",
	"Adjust the appearance of dialog windows.",
	"Enables macOS Sierra window tabs. Note that changes require a full restart to apply and that native tabs will disable a custom title bar style if configured.",
	"Controls if native full-screen should be used on macOS. Disable this option to prevent macOS from creating a new space when going full-screen.",
	"If enabled, clicking on an inactive window will both activate the window and trigger the element under the mouse if it is clickable. If disabled, clicking anywhere on an inactive window will activate it only and a second click is required on the element.",
	"Telemetry",
	"Enable crash reports to be collected. This helps us improve stability. \nThis option requires restart to take effect.",
	"If this setting is false, no telemetry will be sent regardless of the new setting's value. Deprecated due to being combined into the {0} setting.",
	"Keyboard",
	"Enables the macOS touchbar buttons on the keyboard if available.",
	'A set of identifiers for entries in the touchbar that should not show up (for example `workbench.action.navigateBack`).',
	'The display Language to use. Picking a different language requires the associated language pack to be installed.',
	'Disables hardware acceleration. ONLY change this option if you encounter graphic issues.',
	'Allows to override the color profile to use. If you experience colors appear badly, try to set this to `srgb` and restart.',
	'Allows to disable crash reporting, should restart the app if the value is changed.',
	'Unique id used for correlating crash reports sent from this app instance.',
	"Enable proposed APIs for a list of extension ids (such as \`vscode.git\`). Proposed APIs are unstable and subject to breaking without warning at any time. This should only be set for extension development and testing purposes.",
	"Log level to use. Default is 'info'. Allowed values are 'error', 'warn', 'info', 'debug', 'trace', 'off'.",
	"Disables the Chromium sandbox. This is useful when running VS Code as elevated on Linux and running under Applocker on Windows.",
	'Forces the renderer to be accessible. ONLY change this if you are using a screen reader on Linux. On other platforms the renderer will automatically be accessible. This flag is automatically set if you have editor.accessibilitySupport: on.'
]);