/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Restart",
	"Configure",
	"Learn More",
	"Writing login information to the keychain failed with error '{0}'.",
	"Troubleshooting Guide",
	"You are running an emulated version of {0}. For better performance download the native arm64 version of {0} build for your machine.",
	"Download",
	"Proxy Authentication Required",
	"&&Log In",
	"Username",
	"Password",
	"The proxy {0} requires a username and password.",
	"Remember my credentials",
	"Are you sure you want to quit?",
	"Are you sure you want to exit?",
	"Are you sure you want to close the window?",
	"&&Quit",
	"&&Exit",
	"&&Close Window",
	"Do not ask me again",
	"Error: {0}",
	"The following operations are still running: \n{0}",
	"An unexpected error prevented the window to close",
	"An unexpected error prevented the application to quit",
	"An unexpected error prevented the window to reload",
	"An unexpected error prevented to change the workspace",
	"Closing the window is taking a bit longer...",
	"Quitting the application is taking a bit longer...",
	"Reloading the window is taking a bit longer...",
	"Changing the workspace is taking a bit longer...",
	"Close Anyway",
	"Quit Anyway",
	"Reload Anyway",
	"Change Anyway",
	"There is a dependency cycle in the AMD modules that needs to be resolved!",
	"It is not recommended to run {0} as root user.",
	"Files you store within the installation folder ('{0}') may be OVERWRITTEN or DELETED IRREVERSIBLY without warning at update time.",
	"You are running {0} 32-bit, which will soon stop receiving updates on Windows. Consider upgrading to the 64-bit build.",
	"Learn More",
	"{0}. Use navigation keys to access banner actions.",
	"Learn More",
	"{0} on {1} will soon stop receiving updates. Consider upgrading your macOS version.",
	"Learn More",
	"{0}. Use navigation keys to access banner actions.",
	"Learn More",
	"Resolving shell environment...",
	"Learn More"
]);