/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'restart',
	'configure',
	'learnMore',
	'keychainWriteError',
	'troubleshooting',
	"runningTranslated",
	'downloadArmBuild',
	'proxyAuthRequired',
	{ key: 'loginButton', comment: ['&& denotes a mnemonic'] },
	'username',
	'password',
	'proxyDetail',
	'rememberCredentials',
	'quitMessageMac',
	'quitMessage',
	'closeWindowMessage',
	{ key: 'quitButtonLabel', comment: ['&& denotes a mnemonic'] },
	{ key: 'exitButtonLabel', comment: ['&& denotes a mnemonic'] },
	{ key: 'closeWindowButtonLabel', comment: ['&& denotes a mnemonic'] },
	'doNotAskAgain',
	'shutdownErrorDetail',
	'willShutdownDetail',
	'shutdownErrorClose',
	'shutdownErrorQuit',
	'shutdownErrorReload',
	'shutdownErrorLoad',
	'shutdownTitleClose',
	'shutdownTitleQuit',
	'shutdownTitleReload',
	'shutdownTitleLoad',
	'shutdownForceClose',
	'shutdownForceQuit',
	'shutdownForceReload',
	'shutdownForceLoad',
	'loaderCycle',
	'runningAsRoot',
	'appRootWarning.banner',
	'windows32eolmessage',
	'windowseolBannerLearnMore',
	'windowseolarialabel',
	'learnMore',
	'macoseolmessage',
	'macoseolBannerLearnMore',
	'macoseolarialabel',
	'learnMore',
	'resolveShellEnvironment',
	'learnMore'
]);