/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"The kind of workspace opened in the window, either 'empty' (no workspace), 'folder' (single folder) or 'workspace' (multi-root workspace)",
	"The number of root folders in the workspace",
	"Whether there are any working copies with unsaved changes",
	"The name of the remote the window is connected to or an empty string if not connected to any remote",
	"The scheme of the current workspace is from a virtual file system or an empty string.",
	"The scheme of the current workspace is from a temporary file system.",
	"Whether the window is in fullscreen mode",
	'The identifier of the embedder according to the product service, if one is defined',
	"Whether the active editor has unsaved changes",
	"Whether the active editor is not in preview mode",
	"Whether the active editor is the first one in its group",
	"Whether the active editor is the last one in its group",
	"Whether the active editor is pinned",
	"Whether the active editor is read-only",
	"Whether the active editor can toggle between being read-only or writeable",
	"Whether the active editor can revert",
	"The identifier of the active editor",
	"The available editor identifiers that are usable for the active editor",
	"Whether a text compare editor is visible",
	"Whether a text compare editor is active",
	"Whether a side by side editor is active",
	"The number of opened editor groups",
	"Whether the active editor group is empty",
	"The index of the active editor group",
	"Whether the active editor group is the last group",
	"Whether the active editor group is locked",
	"Whether there are multiple editor groups opened",
	"Whether an editor is open",
	"Whether Zen mode is enabled",
	"Whether centered layout is enabled",
	"Whether editors split vertically",
	"Whether the editor area is visible",
	"Whether editor tabs are visible",
	"Whether the sidebar is visible",
	"Whether the sidebar has keyboard focus",
	"The identifier of the active viewlet",
	"Whether the status bar has keyboard focus",
	"Whether the banner has keyboard focus",
	"Whether a notification has keyboard focus",
	"Whether the notifications center is visible",
	"Whether a notification toast is visible",
	"The identifier of the active auxiliary panel",
	"Whether the auxiliary bar has keyboard focus",
	"Whether the auxiliary bar is visible",
	"The identifier of the active panel",
	"Whether the panel has keyboard focus",
	"The position of the panel, always 'bottom'",
	"The alignment of the panel, either 'center', 'left', 'right' or 'justify'",
	"Whether the panel is visible",
	"Whether the panel is maximized",
	"The identifier of the view that has keyboard focus",
	"The scheme of the resource",
	"The file name of the resource",
	"The folder name the resource is contained in",
	"The full path of the resource",
	"The language identifier of the resource",
	"The full value of the resource including scheme and path",
	"The extension name of the resource",
	"Whether a resource is present or not",
	"Whether the resource is backed by a file system provider"
]);