/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'View icon of the outline view.',
	"Outline",
	"Outline",
	"Render Outline elements with icons.",
	"Controls whether Outline items are collapsed or expanded.",
	"Collapse all items.",
	"Expand all items.",
	"Show errors and warnings on Outline elements.",
	"Use colors for errors and warnings on Outline elements.",
	"Use badges for errors and warnings on Outline elements.",
	"When enabled, Outline shows `file`-symbols.",
	"When enabled, Outline shows `module`-symbols.",
	"When enabled, Outline shows `namespace`-symbols.",
	"When enabled, Outline shows `package`-symbols.",
	"When enabled, Outline shows `class`-symbols.",
	"When enabled, Outline shows `method`-symbols.",
	"When enabled, Outline shows `property`-symbols.",
	"When enabled, Outline shows `field`-symbols.",
	"When enabled, Outline shows `constructor`-symbols.",
	"When enabled, Outline shows `enum`-symbols.",
	"When enabled, Outline shows `interface`-symbols.",
	"When enabled, Outline shows `function`-symbols.",
	"When enabled, Outline shows `variable`-symbols.",
	"When enabled, Outline shows `constant`-symbols.",
	"When enabled, Outline shows `string`-symbols.",
	"When enabled, Outline shows `number`-symbols.",
	"When enabled, Outline shows `boolean`-symbols.",
	"When enabled, Outline shows `array`-symbols.",
	"When enabled, Outline shows `object`-symbols.",
	"When enabled, Outline shows `key`-symbols.",
	"When enabled, Outline shows `null`-symbols.",
	"When enabled, Outline shows `enumMember`-symbols.",
	"When enabled, Outline shows `struct`-symbols.",
	"When enabled, Outline shows `event`-symbols.",
	"When enabled, Outline shows `operator`-symbols.",
	"When enabled, Outline shows `typeParameter`-symbols."
]);