/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"To go to a symbol, first open a text editor with symbol information.",
	"The active text editor does not provide symbol information.",
	"No matching editor symbols",
	"No editor symbols",
	"Open to the Side",
	"Open to the Bottom",
	"symbols ({0})",
	"properties ({0})",
	"methods ({0})",
	"functions ({0})",
	"constructors ({0})",
	"variables ({0})",
	"classes ({0})",
	"structs ({0})",
	"events ({0})",
	"operators ({0})",
	"interfaces ({0})",
	"namespaces ({0})",
	"packages ({0})",
	"type parameters ({0})",
	"modules ({0})",
	"properties ({0})",
	"enumerations ({0})",
	"enumeration members ({0})",
	"strings ({0})",
	"files ({0})",
	"arrays ({0})",
	"numbers ({0})",
	"booleans ({0})",
	"objects ({0})",
	"keys ({0})",
	"fields ({0})",
	"constants ({0})"
]);