/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'audioCues.enabled.auto',
	'audioCues.enabled.on',
	'audioCues.enabled.off',
	'audioCues.volume',
	'audioCues.debouncePositionChanges',
	'audioCues.lineHasBreakpoint',
	'audioCues.lineHasInlineSuggestion',
	'audioCues.lineHasError',
	'audioCues.lineHasFoldedArea',
	'audioCues.lineHasWarning',
	'audioCues.onDebugBreak',
	'audioCues.noInlayHints',
	'audioCues.taskCompleted',
	'audioCues.taskFailed',
	'audioCues.terminalCommandFailed',
	'audioCues.terminalQuickFix',
	'audioCues.diffLineInserted',
	'audioCues.diffLineDeleted',
	'audioCues.diffLineModified',
	'audioCues.notebookCellCompleted',
	'audioCues.notebookCellFailed',
	'audioCues.chatRequestSent',
	'audioCues.chatResponsePending',
	'audioCues.chatResponseReceived'
]);