/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'args.schema.kind',
	'args.schema.apply',
	'args.schema.apply.first',
	'args.schema.apply.ifSingle',
	'args.schema.apply.never',
	'args.schema.preferred',
	'quickfix.trigger.label',
	'editor.action.quickFix.noneMessage',
	'editor.action.codeAction.noneMessage.preferred.kind',
	'editor.action.codeAction.noneMessage.kind',
	'editor.action.codeAction.noneMessage.preferred',
	'editor.action.codeAction.noneMessage',
	'refactor.label',
	'editor.action.refactor.noneMessage.preferred.kind',
	'editor.action.refactor.noneMessage.kind',
	'editor.action.refactor.noneMessage.preferred',
	'editor.action.refactor.noneMessage',
	'source.label',
	'editor.action.source.noneMessage.preferred.kind',
	'editor.action.source.noneMessage.kind',
	'editor.action.source.noneMessage.preferred',
	'editor.action.source.noneMessage',
	'organizeImports.label',
	'editor.action.organize.noneMessage',
	'fixAll.label',
	'fixAll.noneMessage',
	'autoFix.label',
	'editor.action.autoFix.noneMessage'
]);