/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'notebookTreeAriaLabelHelp',
	'notebookTreeAriaLabelHelpNoKb',
	'notebookTreeAriaLabel',
	'notebook.cellBorderColor',
	'notebook.focusedEditorBorder',
	'notebookStatusSuccessIcon.foreground',
	'notebookEditorOverviewRuler.runningCellForeground',
	'notebookStatusErrorIcon.foreground',
	'notebookStatusRunningIcon.foreground',
	'notebook.outputContainerBorderColor',
	'notebook.outputContainerBackgroundColor',
	'notebook.cellToolbarSeparator',
	'focusedCellBackground',
	'selectedCellBackground',
	'notebook.cellHoverBackground',
	'notebook.selectedCellBorder',
	'notebook.inactiveSelectedCellBorder',
	'notebook.focusedCellBorder',
	'notebook.inactiveFocusedCellBorder',
	'notebook.cellStatusBarItemHoverBackground',
	'notebook.cellInsertionIndicator',
	'notebookScrollbarSliderBackground',
	'notebookScrollbarSliderHoverBackground',
	'notebookScrollbarSliderActiveBackground',
	'notebook.symbolHighlightBackground',
	'notebook.cellEditorBackground',
	'notebook.editorBackground'
]);