/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'logPoint',
	'breakpoint',
	'breakpointHasConditionDisabled',
	'message',
	'condition',
	'breakpointHasConditionEnabled',
	'message',
	'condition',
	{ key: 'removeLogPoint', comment: ['&& denotes a mnemonic'] },
	'disableLogPoint',
	{ key: 'disable', comment: ['&& denotes a mnemonic'] },
	{ key: 'enable', comment: ['&& denotes a mnemonic'] },
	'logPoint',
	'breakpoint',
	'removeBreakpoint',
	'editBreakpoint',
	'disableBreakpoint',
	'enableBreakpoint',
	'removeBreakpoints',
	'removeInlineBreakpointOnColumn',
	'removeLineBreakpoint',
	'editBreakpoints',
	'editInlineBreakpointOnColumn',
	'editLineBreakpoint',
	'enableDisableBreakpoints',
	'disableInlineColumnBreakpoint',
	'disableBreakpointOnLine',
	'enableBreakpoints',
	'enableBreakpointOnLine',
	'addBreakpoint',
	'addConditionalBreakpoint',
	'addLogPoint',
	'runToLine',
	'debugIcon.breakpointForeground',
	'debugIcon.breakpointDisabledForeground',
	'debugIcon.breakpointUnverifiedForeground',
	'debugIcon.breakpointCurrentStackframeForeground',
	'debugIcon.breakpointStackframeForeground'
]);