/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'unverifiedExceptionBreakpoint',
	'expressionCondition',
	'expressionAndHitCount',
	'functionBreakpointsNotSupported',
	'dataBreakpointsNotSupported',
	'read',
	'write',
	'access',
	'functionBreakpointPlaceholder',
	'functionBreakPointInputAriaLabel',
	'functionBreakpointExpressionPlaceholder',
	'functionBreakPointExpresionAriaLabel',
	'functionBreakpointHitCountPlaceholder',
	'functionBreakPointHitCountAriaLabel',
	'exceptionBreakpointAriaLabel',
	'exceptionBreakpointPlaceholder',
	'breakpoints',
	'disabledLogpoint',
	'disabledBreakpoint',
	'unverifiedLogpoint',
	'unverifiedBreakpoint',
	'dataBreakpointUnsupported',
	'dataBreakpoint',
	'functionBreakpointUnsupported',
	'functionBreakpoint',
	'expression',
	'hitCount',
	'instructionBreakpointUnsupported',
	'instructionBreakpointAtAddress',
	'instructionBreakpoint',
	'hitCount',
	'breakpointUnsupported',
	'logMessage',
	'expression',
	'hitCount',
	'breakpoint',
	'addFunctionBreakpoint',
	{ key: 'miFunctionBreakpoint', comment: ['&& denotes a mnemonic'] },
	'activateBreakpoints',
	'removeBreakpoint',
	'removeAllBreakpoints',
	{ key: 'miRemoveAllBreakpoints', comment: ['&& denotes a mnemonic'] },
	'enableAllBreakpoints',
	{ key: 'miEnableAllBreakpoints', comment: ['&& denotes a mnemonic'] },
	'disableAllBreakpoints',
	{ key: 'miDisableAllBreakpoints', comment: ['&& denotes a mnemonic'] },
	'reapplyAllBreakpoints',
	'editCondition',
	'editCondition',
	'editHitCount',
	'editBreakpoint',
	'editHitCount'
]);