/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Logpoint",
	"Breakpoint",
	"This {0} has a {1} that will get lost on remove. Consider enabling the {0} instead.",
	"message",
	"condition",
	"This {0} has a {1} that will get lost on remove. Consider disabling the {0} instead.",
	"message",
	"condition",
	"&&Remove {0}",
	"{0} {1}",
	"&&Disable",
	"&&Enable",
	"Logpoint",
	"Breakpoint",
	"Remove {0}",
	"Edit {0}...",
	"Disable {0}",
	"Enable {0}",
	"Remove Breakpoints",
	"Remove Inline Breakpoint on Column {0}",
	"Remove Line Breakpoint",
	"Edit Breakpoints",
	"Edit Inline Breakpoint on Column {0}",
	"Edit Line Breakpoint",
	"Enable/Disable Breakpoints",
	"Disable Inline Breakpoint on Column {0}",
	"Disable Line Breakpoint",
	"Enable Inline Breakpoint on Column {0}",
	"Enable Line Breakpoint",
	"Add Breakpoint",
	"Add Conditional Breakpoint...",
	"Add Logpoint...",
	"Run to Line",
	'Icon color for breakpoints.',
	'Icon color for disabled breakpoints.',
	'Icon color for unverified breakpoints.',
	'Icon color for the current breakpoint stack frame.',
	'Icon color for all breakpoint stack frames.'
]);