/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Unverified Exception Breakpoint",
	"Expression condition: {0}",
	"Expression: {0} | Hit Count: {1}",
	"Function breakpoints are not supported by this debug type",
	"Data breakpoints are not supported by this debug type",
	"Read",
	"Write",
	"Access",
	"Function to break on",
	"Type function breakpoint.",
	"Break when expression evaluates to true",
	"Type expression. Function breakpoint will break when expression evaluates to true",
	"Break when hit count is met",
	"Type hit count. Function breakpoint will break when hit count is met.",
	"Type exception breakpoint condition",
	"Break when expression evaluates to true",
	"Breakpoints",
	"Disabled Logpoint",
	"Disabled Breakpoint",
	"Unverified Logpoint",
	"Unverified Breakpoint",
	"Data breakpoints not supported by this debug type",
	"Data Breakpoint",
	"Function breakpoints not supported by this debug type",
	"Function Breakpoint",
	"Expression condition: {0}",
	"Hit Count: {0}",
	"Instruction breakpoints not supported by this debug type",
	"Instruction breakpoint at address {0}",
	"Instruction breakpoint",
	"Hit Count: {0}",
	"Breakpoints of this type are not supported by the debugger",
	"Log Message: {0}",
	"Expression condition: {0}",
	"Hit Count: {0}",
	"Breakpoint",
	"Add Function Breakpoint",
	"&&Function Breakpoint...",
	"Toggle Activate Breakpoints",
	"Remove Breakpoint",
	"Remove All Breakpoints",
	"Remove &&All Breakpoints",
	"Enable All Breakpoints",
	"&&Enable All Breakpoints",
	"Disable All Breakpoints",
	"Disable A&&ll Breakpoints",
	"Reapply All Breakpoints",
	"Edit Condition...",
	"Edit Condition...",
	"Edit Hit Count...",
	"Edit Function Breakpoint...",
	"Edit Hit Count..."
]);