/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Debug',
	"Restart",
	"Step Over",
	"Step Into",
	"Step Into Target",
	"Step Out",
	"Pause",
	"Disconnect",
	"Disconnect and Suspend",
	"Stop",
	"Continue",
	"Focus Session",
	"Select and Start Debugging",
	"Open '{0}'",
	"Start Debugging",
	"Start Without Debugging",
	"Focus Next Debug Console",
	"Focus Previous Debug Console",
	"Open Loaded Script...",
	"Navigate to Top of Call Stack",
	"Navigate to Bottom of Call Stack",
	"Navigate Up Call Stack",
	"Navigate Down Call Stack",
	"Select Debug Console",
	"Select Debug Session",
	"Choose the specific location",
	"No executable code is associated at the current cursor position.",
	"Jump to Cursor",
	"No step targets available",
	"Add Configuration...",
	"Add Inline Breakpoint"
]);