/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Debug",
	"Type the name of a launch configuration to run.",
	"Start Debugging",
	"Type the name of a debug console to open.",
	"Show All Debug Consoles",
	"Terminate Thread",
	"Focus on Debug Console View",
	"Jump to Cursor",
	"Set Next Statement",
	"Inline Breakpoint",
	"Terminate Thread",
	"Restart Frame",
	"Copy Call Stack",
	"View Binary Data",
	"Set Value",
	"Copy Value",
	"Copy as Expression",
	"Add to Watch",
	"Break on Value Read",
	"Break on Value Change",
	"Break on Value Access",
	"Edit Expression",
	"Set Value",
	"Copy Value",
	"View Binary Data",
	"Remove Expression",
	"Run or Debug...",
	"&&Run",
	"&&Start Debugging",
	"Run &&Without Debugging",
	"&&Stop Debugging",
	"&&Restart Debugging",
	"A&&dd Configuration...",
	"Step &&Over",
	"Step &&Into",
	"Step O&&ut",
	"&&Continue",
	"Inline Breakp&&oint",
	"&&New Breakpoint",
	"&&Install Additional Debuggers...",
	"Debug Console",
	"Debug Console",
	"De&&bug Console",
	"Run and Debug",
	"&&Run",
	"Variables",
	"Watch",
	"Call Stack",
	"Breakpoints",
	"Loaded Scripts",
	"Disassembly",
	"Debug",
	"Allow setting breakpoints in any file.",
	"Automatically open the explorer view at the end of a debug session.",
	"Show variable values inline in editor while debugging.",
	"Always show variable values inline in editor while debugging.",
	"Never show variable values inline in editor while debugging.",
	"Show variable values inline in editor while debugging when the language supports inline value locations.",
	"Controls the location of the debug toolbar. Either `floating` in all views, `docked` in the debug view, `commandCenter` (requires `{0}`), or `hidden`.",
	"Show debug toolbar in all views.",
	"Show debug toolbar only in debug views.",
	"Show debug toolbar in the command center.",
	"Do not show debug toolbar.",
	"Never show debug in Status bar",
	"Always show debug in Status bar",
	"Show debug in Status bar only after debug was started for the first time",
	"Controls when the debug Status bar should be visible.",
	"Controls if the Debug Console should be automatically closed when the debug session ends.",
	"Before starting a new debug session in an integrated or external terminal, clear the terminal.",
	"Controls when the debug view should open.",
	"Controls whether the debug sub-sessions are shown in the debug tool bar. When this setting is false the stop command on a sub-session will also stop the parent session.",
	"Controls the font size in pixels in the Debug Console.",
	"Controls the font family in the Debug Console.",
	"Controls the line height in pixels in the Debug Console. Use 0 to compute the line height from the font size.",
	"Controls if the lines should wrap in the Debug Console.",
	"Controls if the Debug Console should suggest previously typed input.",
	"Controls if the Debug Console should collapse identical lines and show a number of occurrences with a badge.",
	"Controls whether suggestions should be accepted on Enter in the Debug Console. Enter is also used to evaluate whatever is typed in the Debug Console.",
	"Global debug launch configuration. Should be used as an alternative to 'launch.json' that is shared across workspaces.",
	"Controls whether the workbench window should be focused when the debugger breaks.",
	"Controls whether the editor should be focused when the debugger breaks.",
	"Ignore task errors and start debugging.",
	"Show the Problems view and do not start debugging.",
	"Prompt user.",
	"Cancel debugging.",
	"Controls what to do when errors are encountered after running a preLaunchTask.",
	"Controls whether breakpoints should be shown in the overview ruler.",
	"Controls whether inline breakpoints candidate decorations should be shown in the editor while debugging.",
	"Controls what editors to save before starting a debug session.",
	"Save all editors in the active group before starting a debug session.",
	"Save all editors in the active group except untitled ones before starting a debug session.",
	"Don't save any editors before starting a debug session.",
	"Controls whether to confirm when the window closes if there are active debug sessions.",
	"Never confirm.",
	"Always confirm if there are debug sessions.",
	"Show Source Code in Disassembly View.",
	"Automatically show values for variables that are lazily resolved by the debugger, such as getters.",
	"Color status bar when debugger is active"
]);