/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'View icon of the debug console view.',
	'View icon of the run view.',
	'View icon of the variables view.',
	'View icon of the watch view.',
	'View icon of the call stack view.',
	'View icon of the breakpoints view.',
	'View icon of the loaded scripts view.',
	'Icon for breakpoints.',
	'Icon for disabled breakpoints.',
	'Icon for unverified breakpoints.',
	'Icon for function breakpoints.',
	'Icon for disabled function breakpoints.',
	'Icon for unverified function breakpoints.',
	'Icon for conditional breakpoints.',
	'Icon for disabled conditional breakpoints.',
	'Icon for unverified conditional breakpoints.',
	'Icon for data breakpoints.',
	'Icon for disabled data breakpoints.',
	'Icon for unverified data breakpoints.',
	'Icon for log breakpoints.',
	'Icon for disabled log breakpoint.',
	'Icon for unverified log breakpoints.',
	'Icon for breakpoint hints shown on hover in editor glyph margin.',
	'Icon for unsupported breakpoints.',
	'Icon for a stackframe shown in the editor glyph margin.',
	'Icon for a focused stackframe  shown in the editor glyph margin.',
	'Icon for the debug bar gripper.',
	'Icon for the debug restart frame action.',
	'Icon for the debug stop action.',
	'Icon for the debug disconnect action.',
	'Icon for the debug restart action.',
	'Icon for the debug step over action.',
	'Icon for the debug step into action.',
	'Icon for the debug step out action.',
	'Icon for the debug step back action.',
	'Icon for the debug pause action.',
	'Icon for the debug continue action.',
	'Icon for the debug reverse continue action.',
	'Icon for the run or debug action.',
	'Icon for the debug start action.',
	'Icon for the debug configure action.',
	'Icon for the debug console open action.',
	'Icon for removing debug configurations.',
	'Icon for the collapse all action in the debug views.',
	'Icon for the session icon in the call stack view.',
	'Icon for the clear all action in the debug console.',
	'Icon for the Remove All action in the watch view.',
	'Icon for the Remove action in the watch view.',
	'Icon for the add action in the watch view.',
	'Icon for the add function breakpoint action in the watch view.',
	'Icon for the Remove All action in the breakpoints view.',
	'Icon for the activate action in the breakpoints view.',
	'Icon for the debug evaluation input marker.',
	'Icon for the debug evaluation prompt.',
	'Icon for the inspect memory action.'
]);