/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'debugCategory',
	'startDebugPlaceholder',
	'startDebuggingHelp',
	'tasksQuickAccessPlaceholder',
	'tasksQuickAccessHelp',
	'terminateThread',
	{ comment: ['Debug is a noun in this context, not a verb.'], key: 'debugFocusConsole' },
	'jumpToCursor',
	'SetNextStatement',
	'inlineBreakpoint',
	'terminateThread',
	'restartFrame',
	'copyStackTrace',
	'viewMemory',
	'setValue',
	'copyValue',
	'copyAsExpression',
	'addToWatchExpressions',
	'breakWhenValueIsRead',
	'breakWhenValueChanges',
	'breakWhenValueIsAccessed',
	'editWatchExpression',
	'setValue',
	'copyValue',
	'viewMemory',
	'removeWatchExpression',
	'run',
	{ key: 'mRun', comment: ['&& denotes a mnemonic'] },
	{ key: 'miStartDebugging', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRun', comment: ['&& denotes a mnemonic'] },
	{ key: 'miStopDebugging', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRestart Debugging', comment: ['&& denotes a mnemonic'] },
	{ key: 'miAddConfiguration', comment: ['&& denotes a mnemonic'] },
	{ key: 'miStepOver', comment: ['&& denotes a mnemonic'] },
	{ key: 'miStepInto', comment: ['&& denotes a mnemonic'] },
	{ key: 'miStepOut', comment: ['&& denotes a mnemonic'] },
	{ key: 'miContinue', comment: ['&& denotes a mnemonic'] },
	{ key: 'miInlineBreakpoint', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNewBreakpoint', comment: ['&& denotes a mnemonic'] },
	{ key: 'miInstallAdditionalDebuggers', comment: ['&& denotes a mnemonic'] },
	{ comment: ['Debug is a noun in this context, not a verb.'], key: 'debugPanel' },
	{ comment: ['Debug is a noun in this context, not a verb.'], key: 'debugPanel' },
	{ key: 'miToggleDebugConsole', comment: ['&& denotes a mnemonic'] },
	'run and debug',
	{ key: 'miViewRun', comment: ['&& denotes a mnemonic'] },
	'variables',
	'watch',
	'callStack',
	'breakpoints',
	'loadedScripts',
	'disassembly',
	'debugConfigurationTitle',
	{ comment: ['This is the description for a setting'], key: 'allowBreakpointsEverywhere' },
	{ comment: ['This is the description for a setting'], key: 'openExplorerOnEnd' },
	{ comment: ['This is the description for a setting'], key: 'inlineValues' },
	'inlineValues.on',
	'inlineValues.off',
	'inlineValues.focusNoScroll',
	{ comment: ['This is the description for a setting'], key: 'toolBarLocation' },
	'debugToolBar.floating',
	'debugToolBar.docked',
	'debugToolBar.commandCenter',
	'debugToolBar.hidden',
	'never',
	'always',
	'onFirstSessionStart',
	{ comment: ['This is the description for a setting'], key: 'showInStatusBar' },
	'debug.console.closeOnEnd',
	{ comment: ['This is the description for a setting'], key: 'debug.terminal.clearBeforeReusing' },
	'openDebug',
	{ comment: ['This is the description for a setting'], key: 'showSubSessionsInToolBar' },
	'debug.console.fontSize',
	'debug.console.fontFamily',
	'debug.console.lineHeight',
	'debug.console.wordWrap',
	'debug.console.historySuggestions',
	'debug.console.collapseIdenticalLines',
	'debug.console.acceptSuggestionOnEnter',
	{ comment: ['This is the description for a setting'], key: 'launch' },
	'debug.focusWindowOnBreak',
	'debug.focusEditorOnBreak',
	'debugAnyway',
	'showErrors',
	'prompt',
	'cancel',
	'debug.onTaskErrors',
	{ comment: ['This is the description for a setting'], key: 'showBreakpointsInOverviewRuler' },
	{ comment: ['This is the description for a setting'], key: 'showInlineBreakpointCandidates' },
	'debug.saveBeforeStart',
	'debug.saveBeforeStart.allEditorsInActiveGroup',
	'debug.saveBeforeStart.nonUntitledEditorsInActiveGroup',
	'debug.saveBeforeStart.none',
	'debug.confirmOnExit',
	'debug.confirmOnExit.never',
	'debug.confirmOnExit.always',
	'debug.disassemblyView.showSourceCode',
	'debug.autoExpandLazyVariables',
	'debug.enableStatusBarColor'
]);