/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"Session is not ready for breakpoints",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"No debugger available, can not send '{0}'",
	"Debugging started.",
	"Debugging stopped."
]);