/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Search",
	"Search",
	"&&Search",
	"Search files by name (append {0} to go to line or {1} to go to symbol)",
	"Go to File",
	"Type the name of a symbol to open.",
	"Go to Symbol in Workspace",
	"Search for text in your workspace files (experimental).",
	"Search for Text (Experimental)",
	"Search",
	"Configure [glob patterns](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) for excluding files and folders in fulltext searches and quick open. Inherits all glob patterns from the `#files.exclude#` setting.",
	"The glob pattern to match file paths against. Set to true or false to enable or disable the pattern.",
	'Additional check on the siblings of a matching file. Use \\$(basename) as variable for the matching file name.',
	"Controls where new `Search: Find in Files` and `Find in Folder` operations occur: either in the search view, or in a search editor.",
	"Search in the search view, either in the panel or side bars.",
	"Search in an existing search editor if present, otherwise in a new search editor.",
	"Search in a new search editor.",
	"This setting is deprecated and now falls back on \"search.usePCRE2\".",
	"Deprecated. Consider \"search.usePCRE2\" for advanced regex feature support.",
	"The search cache is kept in the extension host which never shuts down, so this setting is no longer needed.",
	"When enabled, the searchService process will be kept alive instead of being shut down after an hour of inactivity. This will keep the file search cache in memory.",
	"Controls whether to use `.gitignore` and `.ignore` files when searching for files.",
	"Controls whether to use your global gitignore file (e.g., from `$HOME/.config/git/ignore`) when searching for files. Requires `#search.useIgnoreFiles#` to be enabled.",
	"Controls whether to use `.gitignore` and `.ignore` files in parent directories when searching for files. Requires `#search.useIgnoreFiles#` to be enabled.",
	"Whether to include results from a global symbol search in the file results for Quick Open.",
	"Whether to include results from recently opened files in the file results for Quick Open.",
	'History entries are sorted by relevance based on the filter value used. More relevant entries appear first.',
	'History entries are sorted by recency. More recently opened entries appear first.',
	"Controls sorting order of editor history in quick open when filtering.",
	"Controls whether to follow symlinks while searching.",
	"Search case-insensitively if the pattern is all lowercase, otherwise, search case-sensitively.",
	"Controls whether the search view should read or modify the shared find clipboard on macOS.",
	"Controls whether the search will be shown as a view in the sidebar or as a panel in the panel area for more horizontal space.",
	"This setting is deprecated. You can drag the search icon to a new location instead.",
	"Controls the maximum number of search results, this can be set to `null` (empty) to return unlimited results.",
	"Files with less than 10 results are expanded. Others are collapsed.",
	"Controls whether the search results will be collapsed or expanded.",
	"Controls whether to open Replace Preview when selecting or replacing a match.",
	"Controls whether to show line numbers for search results.",
	"Whether to use the PCRE2 regex engine in text search. This enables using some advanced regex features like lookahead and backreferences. However, not all PCRE2 features are supported - only features that are also supported by JavaScript.",
	"Deprecated. PCRE2 will be used automatically when using regex features that are only supported by PCRE2.",
	"Position the actionbar to the right when the search view is narrow, and immediately after the content when the search view is wide.",
	"Always position the actionbar to the right.",
	"Controls the positioning of the actionbar on rows in the search view.",
	"Search all files as you type.",
	"Enable seeding search from the word nearest the cursor when the active editor has no selection.",
	"Update the search query to the editor's selected text when focusing the search view. This happens either on click or when triggering the `workbench.views.search.focus` command.",
	"When {0} is enabled, controls the timeout in milliseconds between a character being typed and the search starting. Has no effect when {0} is disabled.",
	"Double-clicking selects the word under the cursor.",
	"Double-clicking opens the result in the active editor group.",
	"Double-clicking opens the result in the editor group to the side, creating one if it does not yet exist.",
	"Configure effect of double-clicking a result in a search editor.",
	"When enabled, new Search Editors will reuse the includes, excludes, and flags of the previously opened Search Editor.",
	"The default number of surrounding context lines to use when creating new Search Editors. If using `#search.searchEditor.reusePriorSearchConfiguration#`, this can be set to `null` (empty) to use the prior Search Editor's configuration.",
	"Results are sorted by folder and file names, in alphabetical order.",
	"Results are sorted by file names ignoring folder order, in alphabetical order.",
	"Results are sorted by file extensions, in alphabetical order.",
	"Results are sorted by file last modified date, in descending order.",
	"Results are sorted by count per file, in descending order.",
	"Results are sorted by count per file, in ascending order.",
	"Controls sorting order of search results.",
	"Controls whether search file decorations should use colors.",
	"Controls whether search file decorations should use badges.",
	"Shows search results as a tree.",
	"Shows search results as a list.",
	"Controls the default search result view mode.",
	"Show notebook editor rich content results for closed notebooks. Please refresh your search results after changing this setting.",
	"Controls whether the last typed input to Quick Search should be restored when opening it the next time."
]);