/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Search was canceled before any results could be found - ",
	"Toggle Search Details",
	"files to include",
	"e.g. *.ts, src/**/include",
	"files to exclude",
	"e.g. *.ts, src/**/exclude",
	"Replace All",
	"&&Replace",
	"Replaced {0} occurrence across {1} file with '{2}'.",
	"Replaced {0} occurrence across {1} file.",
	"Replaced {0} occurrence across {1} files with '{2}'.",
	"Replaced {0} occurrence across {1} files.",
	"Replaced {0} occurrences across {1} file with '{2}'.",
	"Replaced {0} occurrences across {1} file.",
	"Replaced {0} occurrences across {1} files with '{2}'.",
	"Replaced {0} occurrences across {1} files.",
	"Replace {0} occurrence across {1} file with '{2}'?",
	"Replace {0} occurrence across {1} file?",
	"Replace {0} occurrence across {1} files with '{2}'?",
	"Replace {0} occurrence across {1} files?",
	"Replace {0} occurrences across {1} file with '{2}'?",
	"Replace {0} occurrences across {1} file?",
	"Replace {0} occurrences across {1} files with '{2}'?",
	"Replace {0} occurrences across {1} files?",
	"Empty Search",
	"The search results have been cleared",
	"Search path not found: {0}",
	"No results found in open editors matching '{0}' excluding '{1}' - ",
	"No results found in open editors matching '{0}' - ",
	"No results found in open editors excluding '{0}' - ",
	"No results found in open editors. Review your settings for configured exclusions and check your gitignore files - ",
	"No results found in '{0}' excluding '{1}' - ",
	"No results found in '{0}' - ",
	"No results found excluding '{0}' - ",
	"No results found. Review your settings for configured exclusions and check your gitignore files - ",
	"Search again",
	"Search again in all files",
	"Open Settings",
	"Learn More",
	"Search returned {0} results in {1} files",
	"The result set only contains a subset of all matches. Be more specific in your search to narrow down the results.",
	" - Search: {0}",
	"exclude settings and ignore files are disabled",
	"enable",
	"Use Exclude Settings and Ignore Files",
	"searching only in open files",
	"disable",
	"Search in entire workspace",
	"Copy current search results to an editor",
	"Open in editor",
	"{0} result in {1} file",
	"{0} result in {1} files",
	"{0} results in {1} file",
	"{0} results in {1} files",
	"You have not opened or specified a folder. Only open files are currently searched - ",
	"Open Folder"
]);