/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'The folder icon for expanded folders. The expanded folder icon is optional. If not set, the icon defined for folder will be shown.',
	'The folder icon for collapsed folders, and if folderExpanded is not set, also for expanded folders.',
	'The default file icon, shown for all files that don\'t match any extension, filename or language id.',
	'Associates folder names to icons. The object key is the folder name, not including any path segments. No patterns or wildcards are allowed. Folder name matching is case insensitive.',
	'The ID of the icon definition for the association.',
	'Associates folder names to icons for expanded folders. The object key is the folder name, not including any path segments. No patterns or wildcards are allowed. Folder name matching is case insensitive.',
	'The ID of the icon definition for the association.',
	'Associates file extensions to icons. The object key is the file extension name. The extension name is the last segment of a file name after the last dot (not including the dot). Extensions are compared case insensitive.',
	'The ID of the icon definition for the association.',
	'Associates file names to icons. The object key is the full file name, but not including any path segments. File name can include dots and a possible file extension. No patterns or wildcards are allowed. File name matching is case insensitive.',
	'The ID of the icon definition for the association.',
	'Associates languages to icons. The object key is the language id as defined in the language contribution point.',
	'The ID of the icon definition for the association.',
	'Fonts that are used in the icon definitions.',
	'The ID of the font.',
	'The ID must only contain letter, numbers, underscore and minus.',
	'The location of the font.',
	'The font path, relative to the current file icon theme file.',
	'The format of the font.',
	'The weight of the font. See https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight for valid values.',
	'The style of the font. See https://developer.mozilla.org/en-US/docs/Web/CSS/font-style for valid values.',
	'The default size of the font. See https://developer.mozilla.org/en-US/docs/Web/CSS/font-size for valid values.',
	'Description of all icons that can be used when associating files to icons.',
	'An icon definition. The object key is the ID of the definition.',
	'When using a SVG or PNG: The path to the image. The path is relative to the icon set file.',
	'When using a glyph font: The character in the font to use.',
	'When using a glyph font: The color to use.',
	'When using a font: The font size in percentage to the text font. If not set, defaults to the size in the font definition.',
	'When using a font: The id of the font. If not set, defaults to the first font definition.',
	'Optional associations for file icons in light color themes.',
	'Optional associations for file icons in high contrast color themes.',
	'Configures whether the file explorer\'s arrows should be hidden when this theme is active.',
	'Configures whether the default language icons should be used if the theme does not define an icon for a language.'
]);