/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'colorTheme',
	'colorThemeError',
	{ key: 'preferredDarkColorTheme', comment: ['{0} will become a link to another setting.'] },
	'colorThemeError',
	{ key: 'preferredLightColorTheme', comment: ['{0} will become a link to another setting.'] },
	'colorThemeError',
	{ key: 'preferredHCDarkColorTheme', comment: ['{0} will become a link to another setting.'] },
	'colorThemeError',
	{ key: 'preferredHCLightColorTheme', comment: ['{0} will become a link to another setting.'] },
	'colorThemeError',
	{ key: 'detectColorScheme', comment: ['{0} and {1} will become links to other settings.'] },
	'workbenchColors',
	'iconTheme',
	'noIconThemeLabel',
	'noIconThemeDesc',
	'iconThemeError',
	'productIconTheme',
	'defaultProductIconThemeLabel',
	'defaultProductIconThemeDesc',
	'productIconThemeError',
	{ key: 'autoDetectHighContrast', comment: ['{0} and {1} will become links to other settings.'] },
	'editorColors.comments',
	'editorColors.strings',
	'editorColors.keywords',
	'editorColors.numbers',
	'editorColors.types',
	'editorColors.functions',
	'editorColors.variables',
	'editorColors.textMateRules',
	'editorColors.semanticHighlighting',
	'editorColors.semanticHighlighting.deprecationMessage',
	{ key: 'editorColors.semanticHighlighting.deprecationMessageMarkdown', comment: ['{0} will become a link to another setting.'] },
	'editorColors',
	'editorColors.semanticHighlighting.enabled',
	'editorColors.semanticHighlighting.rules',
	'semanticTokenColors'
]);