/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Specifies the color theme used in the workbench.",
	"Theme is unknown or not installed.",
	'Specifies the preferred color theme for dark OS appearance when {0} is enabled.',
	"Theme is unknown or not installed.",
	'Specifies the preferred color theme for light OS appearance when {0} is enabled.',
	"Theme is unknown or not installed.",
	'Specifies the preferred color theme used in high contrast dark mode when {0} is enabled.',
	"Theme is unknown or not installed.",
	'Specifies the preferred color theme used in high contrast light mode when {0} is enabled.',
	"Theme is unknown or not installed.",
	'If set, automatically switch to the preferred color theme based on the OS appearance. If the OS appearance is dark, the theme specified at {0} is used, for light {1}.',
	"Overrides colors from the currently selected color theme.",
	"Specifies the file icon theme used in the workbench or 'null' to not show any file icons.",
	'None',
	'No file icons',
	"File icon theme is unknown or not installed.",
	"Specifies the product icon theme used.",
	'Default',
	'Default',
	"Product icon theme is unknown or not installed.",
	"If enabled, will automatically change to high contrast theme if the OS is using a high contrast theme. The high contrast theme to use is specified by {0} and {1}",
	"Sets the colors and styles for comments",
	"Sets the colors and styles for strings literals.",
	"Sets the colors and styles for keywords.",
	"Sets the colors and styles for number literals.",
	"Sets the colors and styles for type declarations and references.",
	"Sets the colors and styles for functions declarations and references.",
	"Sets the colors and styles for variables declarations and references.",
	'Sets colors and styles using textmate theming rules (advanced).',
	'Whether semantic highlighting should be enabled for this theme.',
	'Use `enabled` in `editor.semanticTokenColorCustomizations` setting instead.',
	'Use `enabled` in {0} setting instead.',
	"Overrides editor syntax colors and font style from the currently selected color theme.",
	'Whether semantic highlighting is enabled or disabled for this theme',
	'Semantic token styling rules for this theme.',
	"Overrides editor semantic token color and styles from the currently selected color theme."
]);