/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'contributes.semanticTokenTypes',
	'contributes.semanticTokenTypes.id',
	'contributes.semanticTokenTypes.id.format',
	'contributes.semanticTokenTypes.superType',
	'contributes.semanticTokenTypes.superType.format',
	'contributes.color.description',
	'contributes.semanticTokenModifiers',
	'contributes.semanticTokenModifiers.id',
	'contributes.semanticTokenModifiers.id.format',
	'contributes.semanticTokenModifiers.description',
	'contributes.semanticTokenScopes',
	'contributes.semanticTokenScopes.languages',
	'contributes.semanticTokenScopes.scopes',
	'invalid.id',
	'invalid.id.format',
	'invalid.superType.format',
	'invalid.description',
	'invalid.semanticTokenTypeConfiguration',
	'invalid.semanticTokenModifierConfiguration',
	'invalid.semanticTokenScopes.configuration',
	'invalid.semanticTokenScopes.language',
	'invalid.semanticTokenScopes.scopes',
	'invalid.semanticTokenScopes.scopes.value',
	'invalid.semanticTokenScopes.scopes.selector'
]);