/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'findSelectionIcon',
	'findCollapsedIcon',
	'findExpandedIcon',
	'findReplaceIcon',
	'findReplaceAllIcon',
	'findPreviousMatchIcon',
	'findNextMatchIcon',
	'label.findDialog',
	'label.find',
	'placeholder.find',
	'label.previousMatchButton',
	'label.nextMatchButton',
	'label.toggleSelectionFind',
	'label.closeButton',
	'label.replace',
	'placeholder.replace',
	'label.replaceButton',
	'label.replaceAllButton',
	'label.toggleReplaceButton',
	'title.matchesCountLimit',
	'label.matchesLocation',
	'label.noResults',
	'ariaSearchNoResultEmpty',
	'ariaSearchNoResult',
	'ariaSearchNoResultWithLineNum',
	'ariaSearchNoResultWithLineNumNoCurrentMatch',
	'ctrlEnter.keybindingChanged'
]);